### ISSUE TITLE
WebAssembly version?

### ISSUE THREAD

**Issue by benwiley4000** [chrismaltby/gb-studio#1]
Hey, this project looks super cool! Thanks for working on it, I'm excited to try it out.

I was wondering if you think it would be possible to use Emscripten or similar to pack the C dependencies into WebAssembly that gb-studio can be run in a web browser.

I don't know too much about Electron or Emscripten or WASM but I figured it could be really neat if folks could use this tool without needing to download an executable.

**Comment by chrismaltby** [comment]
The original idea was actually exactly what you're suggesting but I was struggling to get the tools built with Emscripten. I'm going to close this issue for now as it's not something I think I can help with at the moment but if someone wants to fork and give it a try I'm more than happy and could revisit this in the future.

**Comment by benwiley4000** [comment]
Ok cool, thanks for explaining!
