### ISSUE TITLE
[bug] Set camera position and shake camera

### ISSUE THREAD

**Issue by Veund** [chrismaltby/gb-studio#100]
When i set camera position after a trigger and use shake camera it goes everywhere then pans back to the position and continues dialogue but not until it pans back. 

Is it trying to shake at the player's position? 

Im running 1.0 on Windows

**Comment by chrismaltby** [comment]
Hi Veund, 
Think I've found the cause and fixed this with commit 96951966ca16bb23819d2488615256e9d934452d. If you want to upload a sample project with the issue I can confirm. Otherwise this fix will now be in the next release :-)
