### ISSUE TITLE
Converted .uge tracks return error message, cannot compile or edit

### ISSUE THREAD

**Issue by Anima-SodoDev** [chrismaltby/gb-studio#1006]
**Describe the bug**
I have converted my .mod tracks to .uge using hUGETracker (importing the original file and saving as the new format), but they seem to return an error message when trying to compile the game or modify the tracks in the embedded tracker, `Cannot read property '0' of undefined`.

**To Reproduce**
1. Download [this track](https://cdn.discordapp.com/attachments/925126645491302563/933107821522874398/An_Age_Long_Gone_Short.uge).
2. Make a play music event for it.
3. Try to edit or compile.

**Expected behavior**
I should be able to edit the tracks or at least compile the game.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/34885906/149939974-cf71a544-7030-49cf-8d28-7af910744fca.png)
![imagen](https://user-images.githubusercontent.com/34885906/149940166-b3c7ede9-e656-4496-b7ca-c623265051f3.png)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro
 - App version: 3.0.2, built from GitHub, so I have the latest commits.

**Comment by pau-tomas** [comment]
Sorry but I can't reproduce this issue on Mac, the song loads in the tracker and compiles correctly.

**Comment by Anima-SodoDev** [comment]
I noticed that track specifically does work after making this issue, I updated the link to a track that I know doesn't work. My bad.

**Comment by pau-tomas** [comment]
I think I found the issue but it might take a bit to solve in a proper way. Thanks!
