### ISSUE TITLE
Ability to label Event groups

### ISSUE THREAD

**Issue by blurymind** [chrismaltby/gb-studio#1014]
**Is your feature request related to a problem? Please describe.**
Collapsed event groups can become hard to manage since there is no way to label what they do

**Describe the solution you'd like**
A simple way to label event groups would resolve this

**Describe alternatives you've considered**
ability to tag them with a color

**Additional context**
![image](https://user-images.githubusercontent.com/6495061/150578055-a2b51bda-0790-4a78-aa40-d59fcac57982.png)

**Comment by pau-tomas** [comment]
You should be able to rename any event using the menu in the ▼ icon. Isn't that the case for the groups?

**Comment by blurymind** [comment]
one thins that would be amazing, but perhaps out of the scope of this is some way to instance event groups for code re-usability.

Lets say every event group you create in the game also has its own UID. You could then have another action
![image](https://user-images.githubusercontent.com/6495061/150580702-1d7399c2-e587-4b73-9e1b-fd278bedd0e5.png)

**Comment by blurymind** [comment]
> You should be able to rename any event using the menu in the ▼ icon. Isn't that the case for the groups?

ah sorry, should I close this or rename it Event group reusability?

**Comment by maxoakland** [comment]
> > You should be able to rename any event using the menu in the ▼ icon. Isn't that the case for the groups?
> 
> ah sorry, should I close this or rename it Event group reusability?

You can already reuse event groups by making a custom script and including the code in there. Then you call that script wherever you want
