### ISSUE TITLE
Background priority sprites are drawn on top of the background when a sprite is in motion 

### ISSUE THREAD

**Issue by Jeltr0n** [chrismaltby/gb-studio#1029]
**Describe the bug**
When player sprites are set to background priority mode they go in front of the background until they stop moving. Only then do they go behind. 

**To Reproduce**
-Make a sprite that has background priority set on all of the sprites. 

-Walk over background tiles that are supposed to go in front of the actor. 

-Colors 2,3,4 will draw under the actor until it comes to a stop. 

**Expected behavior**
Colors 2,3,and 4 should be drawn in front of the player sprite like this: 
![plugins3](https://user-images.githubusercontent.com/70062490/151413997-68c82e53-b6a3-4c1f-8cc1-f507a947a22b.gif)

**Screenshots**

![robot](https://user-images.githubusercontent.com/70062490/151412134-326ea320-4a9d-4119-aaba-2607e83540b2.gif)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.3

**Comment by um3k** [comment]
Are you 100% certain the background priority is set correctly on all of your sprites/states/frames? I notice it seems to flash back and forth as you move

**Comment by Jeltr0n** [comment]
You are right. I thought that I had triple-checked this but somehow I still missed some frames.
