### ISSUE TITLE
Add "SAVE AS" to save the project as another file

### ISSUE THREAD

**Issue by Audio-Rochey** [chrismaltby/gb-studio#103]
Hello folks,

Often, I want to save a clone of the project and start ripping pages etc out to test an advanced bit of functionality. we only have a "SAVE" function at the moment. It'd be nice to have a "SAVE PROJECT AS" that'd clone everything in the directory to another folder, so I can tinker with that without breaking the main project.

/Dafydd

**Comment by thomas-alrek** [comment]
I agree, however, this is exactly what Git is designed for. If you have your project in source control, you can just create experimental branches, and revert back later.

**Comment by chrismaltby** [comment]
This is finally available in the dev branch now thanks to a recent update by @zdurgan 👍
