### ISSUE TITLE
Add Social Preview Image for Github

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#106]
https://github.com/chrismaltby/gb-studio/settings -> Social preview

E.g: 
<img width="640" alt="social_image" src="https://user-images.githubusercontent.com/14291825/57040678-76f5ef00-6c60-11e9-8355-e2708c9015c1.png">

**Comment by chrismaltby** [comment]
Dropped an image in for social now thanks :-D
