### ISSUE TITLE
Different hitbox sizes for different animation states

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1085]
**Is your feature request related to a problem? Please describe.**
With the addition of larger sprites and animation states, characters hitbox may need to change, e.g. you have a taller than 32px high player who has a jump and a duck states, both halve the visible player sprite to 16px, however only one hitbox can be set and it can't be changed using animation states.

**Describe the solution you'd like**
Different hitboxes for different animation states if required

**Describe alternatives you've considered**
An event to change hitbox size (although perhaps not as neat a solution)

**Comment by maxoakland** [comment]
There’s a plugin that adds an event to change hitbox size

**Comment by godai78** [comment]
^ Can you link it?

**Comment by joeledge** [comment]
Awesome, not sure how I missed that, will have a play around with it. Thanks @maxoakland.

@godai78 it appears to be this – https://github.com/Y0UR-U5ERNAME/gbs-plugin-collection/tree/main/plugins/actorSetCollisionBoxPlugin/events

**Comment by joeledge** [comment]
As Max mentioned, there's a plugin that can achieve this so closing
