### ISSUE TITLE
[Request] Fun with variables

### ISSUE THREAD

**Issue by Igerow** [chrismaltby/gb-studio#109]
At first, I want to thank the developer of this nifty, little editor. It's very easy to use and runs like a charm.

But, unfortunately, it is still very limited in many functions

Would it be hard, to implement something like this:

https://i.imgur.com/K0O1xQE.png

This is just a little sketch, but I hope you understand the concept.

The the same with the "if statements" for variables. Would be really nice to be able to compare variables with each other.

It would also be great to have something like "get_player_x" and "get_player_y", to make things like a menu possible. (https://github.com/chrismaltby/gb-studio/issues/70, https://github.com/chrismaltby/gb-studio/issues/55)

**Comment by thomas-alrek** [comment]
Regarding your last two requests.

PR #84 implements a lot of useful Math functions, including a If Variable Compare, to compare two variables.

PR #81 Implements extended Actor scripting, including Get Actor Position, and Set Actor Position To Value

**Comment by RichardULZ** [comment]
Combining some math or move functions in the script editor might be nice, using a drop down picker to call the dedicated functions in code, for speed.
Drop down box like the compare variable function.

**Comment by Igerow** [comment]
Thank you for your quick answer! I will definitely check this out!

**Comment by Igerow** [comment]
When using "Math Variable Subtract" I found the formulation "Subtract (var1) BY Value (var2)" to be quite irritating. Especially strange when using "Math Subtract", and there it reads ""Subtract (var1) FROM Value (var2)", which is much easier to understand, I think.

I also don't like the fact that some of the functions are named in such an "inconsistent" way.
Like "Actor Move", but then "Hide Actor". Wouldn't it be better, to use one style and keep things sorted?

But I don't want to be petty, as these are probably low priority things. :)

**Comment by thomas-alrek** [comment]
I think it is open for debate. You could make a separate issue with your suggestions
