### ISSUE TITLE
[Request] "Actor Move To" variations

### ISSUE THREAD

**Issue by blazelink3** [chrismaltby/gb-studio#110]
I'd like to preface this that I'm having a lot of fun using this wonderful tool, but, with the "actor move to" command, or it's relative counterpart on the develop branch, it would be nice to implement variations, such as a speed variable that allows objects to move faster or slower, since it's frequently too slow for something things and too fast for others.

I also wonder if a "diagonal" option would be possible, rather than it's "L" shaped movement

**Comment by RichardULZ** [comment]
Movement Speed options were added in the latest Development update from the "Performance" update. 
6423cd4
