### ISSUE TITLE
Select multiple scenes in the editor

### ISSUE THREAD

**Issue by godai78** [chrismaltby/gb-studio#1106]
**Is your feature request related to a problem? Please describe.**  
Managing multiple scenes inside the editor window is a mundane task done one by one.

**Describe the solution you'd like**  
Add the ability to select multiple scenes in the workspace and move them around collectively.

**Comment by chrismaltby** [comment]
Just closing old issues, the ability to select multiple scenes with shift+click was added in v4.0.0 :-)
