### ISSUE TITLE
How do i run it on Solus OS

### ISSUE THREAD

**Issue by arceusisafish** [chrismaltby/gb-studio#111]
I cant run the linux version because none of them support solus

**Comment by thomas-alrek** [comment]
I'm not personally familiar with, but as far as I can tell it seems to be based on Debian. In that case, the DEB file should work for you (it only supports 64-bit though).

**Comment by arceusisafish** [comment]
> I'm not personally familiar with Solus, but as far as I can tell it seems to be based on Debian. In that case, the DEB file should work for you (it only supports 64-bit though).

solus isnt debian based and theres no tar version

**Comment by arceusisafish** [comment]
so if theres a tarball version i should be able to use it since wine doesnt work properly

**Comment by RichardULZ** [comment]
Supported over the [GB Studio Discord](https://discord.gg/bxerKnc).
User attempted to compile the source on Solus OS and was missing and eventually installed:
Yarn, Node.js, Electron-forge, Git.
These all seem essential to source compiling, especially git (on windows too), and should be noted in the docs.
Users issue was resolved.

**Comment by thomas-alrek** [comment]
We should probably add build instructions to the README

**Comment by tommai78101** [comment]
> We should probably add build instructions to the README

If we're to do that, I hoped that all platforms are specified individually, instead of having a README with a general build instructions section. There are some platform-specific nuances some other Github projects tend to gloss over.

**Comment by janogarciardz** [comment]
I do not speak in English, I translated this with Google, I am a Solus user, what I did was download the github repository and follow the instructions of yarn and npm start and it works very well, greetings.
