### ISSUE TITLE
Swappable Font Event

### ISSUE THREAD

**Issue by CHADALAK1** [chrismaltby/gb-studio#1112]
Currently in GBStudio now, it's stuck on using a default font through and through.

I'm not sure if it's the limitation of GBStudio, but swappable fonts at runtime would be super awesome. Say I wanted a more emphatical text for something important. I can't do that with the current state with GBStudio.

**Comment by pau-tomas** [comment]
You can change the font used in a text field dynamically by typing `!f` and selecting from the menu.

To add new fonts check [the docs](https://www.gbstudio.dev/docs/settings/#ui-elements--fonts)

**Comment by CHADALAK1** [comment]
Oohhh gotcha. It's not labeled in the docs about how to get that. Have to right click on the Dialogue of choice Dx

**Comment by pau-tomas** [comment]
It's mentioned in the display dialogue event documentation: https://www.gbstudio.dev/docs/script-glossary/#display-dialogue

**Comment by CHADALAK1** [comment]
Roger that!! Thank you for the clearup :D !! Marking this closed
