### ISSUE TITLE
[Documentation Request] Show all categories in the navigation sidebar

### ISSUE THREAD

**Issue by HeyItsLollie** [chrismaltby/gb-studio#1115]
The documentation can be a bit cumbersome to navigate, as the navigation sidebar only shows the current page's sections plus the next page in the documentation. If you want to see the full table of contents, you have to return to the "Docs" page via the topbar.
![firefox_20220517_11-18-06-223](https://user-images.githubusercontent.com/30498581/168708225-dac41fc2-ba73-40cc-8094-3482ad1df778.png)

What I'm requesting is to show all available subjects in the sidebar, and expand the list based on the page you're currently viewing.
![firefox_20220517_11-21-44-017](https://user-images.githubusercontent.com/30498581/168708449-239e804d-69cb-43fb-97f4-1d1e2971878c.png)

**Comment by DeerTears** [comment]
Could you copy/paste this to https://github.com/chrismaltby/gb-studio-site/issues/new and close this one?

**Comment by HeyItsLollie** [comment]
Oh will do! Didn't realize there was a separate repo for the site ✌
