### ISSUE TITLE
Not able to migrate to 3.0

### ISSUE THREAD

**Issue by XernHackz** [chrismaltby/gb-studio#1118]
I've been tasked with modding a game someone else has made in GB studio. This project started in version 2.0 and was not able to be migrated to 3.0. Now I've taken the blunt of this unfortunate circumstance and cannot migrate the project to version 3.0. It's a bit disheartening because in order to migrate the game the entire thing is going to have to be rebuilt. For reference when i try to run the game it does not run...at all. And, even when trying to re-build the game in 3.0, it seems like the files i've been provided with aren't even compatible (the program just completely crashes/freezes when i try to run the game). I am on Windows OS. The original game was also made on Mac OS, I hope that doesn't contribute to the problem - and it shouldn't - because i can run most of the source files on my laptop.

Needless to say I feel like this issue could've been solved if older versions of GB studio were provided. If anyone can point me in that direction it would be very helpful. The devs have absolutely no contact information so I don't know what to do here. Thanks.

Screenshot of what happens when I try to migrate:

![image](https://user-images.githubusercontent.com/106263273/170305149-a4f58201-f2a7-4a4e-b7fc-39d5bdafcd5d.png)
![image](https://user-images.githubusercontent.com/106263273/170305184-91dd6162-806a-48a7-8e9b-c299b09dd7f7.png)

This orange text just seems to repeat over and over instead of actually running the game.

**Comment by um3k** [comment]
I can't help with the migration issue, but you can indeed download previous
versions on GitHub: https://github.com/chrismaltby/gb-studio/releases

**Comment by XernHackz** [comment]
Thank you, unfortunately the damage has already been done and we've restarted. I think this should be more public knowledge in the future. I appreciate the reply.
