### ISSUE TITLE
# and $ characters do not render in dialogue.

### ISSUE THREAD

**Issue by proximitysound** [chrismaltby/gb-studio#1162]
Adding either a # or $ character to a dialogue window does not render the text either in preview or in game. Assuming this is a big due to how wildcards for variable work. Unsure if this can be escaped with a special character, I haven't been able to find one.

**Comment by chrismaltby** [comment]
Hi @proximitysound Just pushed a fix for this in 9bda3ab69b9e79b1d3f0080c89c181ca4ddf56e3 :-)
