### ISSUE TITLE
Dedicated HUD area

### ISSUE THREAD

**Issue by joe01020304** [chrismaltby/gb-studio#1165]
Being able to pin actors to part of the screen to make a HUD is good, but the player can sometimes be drawn over the pinned actors (at least when making original GB games, I haven't tried with color yet).

It would be great if I could dedicate part of the screen space solely to a HUD like many original Gameboy games do. Something so that only the HUD can be drawn in a section of the screen. Thank you.

**Comment by Anima-SodoDev** [comment]
Sounds like you want to use the overlay, which can be done with GBVM or the advanced dialogue plugin.

**Comment by joe01020304** [comment]
Thank you, that was what i was looking for!

**Comment by sttng** [comment]
> Sounds like you want to use the overlay, which can be done with GBVM or the advanced dialogue plugin.

Well, it'll be nice to "customize" the HUD with tiles similar to a normal scene. Thats a feature still missing in GB Studio.
