### ISSUE TITLE
(UX) Foldable scripts in the panel and flowcharts

### ISSUE THREAD

**Issue by DuendeInexistente** [chrismaltby/gb-studio#118]
Me again with UX stuff.
At the present, it's *very* easy for scripts to become long and cluttered. The panel already suports folding Else statements, so why not add an even that's just to fold other elements, like a [spoiler] tag in bbcode? It could also have an option to name it, for better organizing.

The second thing is more complicated, but flowcharts could also help better visualize script flow and allow for an organized userspace without altering the underlying structure essentially. It would also allow displaying every script in a scene in an easy to review, easy to modify fashion
![](https://i.imgur.com/UYb6Us7.png)

**Comment by chrismaltby** [comment]
Hi @DuendeInexistente I've just pushed an update 626892ac8d39e25723b25bcb9daf30f3a8fad91b which should solve your first issue. It adds "Event Group" as an event type, and also allows any events (event single ones like "Display Text" to be collapsed) it also now saves the opened/collapsed state to the project so it is kept when switching between actors and reloading the project file.

<img width="299" alt="Screenshot 2019-05-07 at 17 45 23" src="https://user-images.githubusercontent.com/16776042/57341781-91144f00-70f0-11e9-95cb-431f894dde8f.png">

I like the second idea, needs a bit more thought but potentially this could be a view you switch to where you see a view of all the scripts in a scene and what triggers them and you can drag them about 
with connections between them in the same way the world view shows the scenes with their connections.
