### ISSUE TITLE
(v3.1) Loop For does not work when the increment is negative

### ISSUE THREAD

**Issue by Y0UR-U5ERNAME** [chrismaltby/gb-studio#1186]
**Describe the bug**
The Loop For event does nothing when the increment is set to negative and the start value is greater than the end value.

**To Reproduce**
1. In a new blank project, add a Loop For event to the scene init, from 10 to 0 with an increment of -1.
2. Inside the loop, add a dialogue to display the variable used in the loop.
3. Run the project and see that there are no dialogues.

**Expected behavior**
When the increment is negative, the variable should loop until it reaches the end value or less.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.1.0

**Comment by patrickmollohan** [comment]
Do you have the latest version of 3.1.0?

**Comment by Y0UR-U5ERNAME** [comment]
@patrickmollohan No, is it fixed in the latest one?

**Comment by patrickmollohan** [comment]
@Y0UR-U5ERNAME yup, and you have the ability to control the comparison and math operation too
