### ISSUE TITLE
FATAL:gpu_data_manager_impl_private.cc(1034)]

### ISSUE THREAD

**Issue by brotenet** [chrismaltby/gb-studio#1198]
**Describe the bug**
After installing latest (v3.0.3) GB Studio on the latest Linux Mint using the DEB package, the application crashes on startup with the following output:
No language pack for user setting, falling back to en
Add a language pack by making the file src/lang/en-US.json
[8125:0831/075201.824021:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)

**To Reproduce**
1. Use DEB installer on Linux Mint 21 (Vanessa)
2. Start the application in terminal (in order to see the error message)

**Expected behavior**
The application crashes on startup with the following output:
No language pack for user setting, falling back to en
Add a language pack by making the file src/lang/en-US.json
[8125:0831/075201.824021:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing.

**Screenshots**
![error](https://user-images.githubusercontent.com/4510965/187596858-2dd667f3-c65f-488e-a163-fbd610139af8.png)

**Platform (please complete the following information):**
 - OS: Linux Mint 21 (Vanessa)
 - Kernel: 5.15.0-46-generic x86_64 bits: 64
 - Desktop: Cinnamon 5.4.11
 - App version: 3.0.3

**Additional context**
*Hardware Specs Used*
 - CPU: Intel Core i7-4800MQ
 - GPU: NVIDIA GK107GLM [Quadro K1100M] driver: nvidia v: 390.154

**Comment by amsinz** [comment]
I can also confirm the bug.

**Platform (please complete the following information):**

- OS: Ubuntu 22.04.1 LTS
- Kernel: 5.15.0-46-generic x86_64 bits: 64
- Desktop: Gnome 42.2
- App version: 3.0.3

**Additional context**
_Hardware Specs Used_

- CPU: Intel Core i5-3470
- GPU: NVIDIA GK107 [GeForce GT 640] driver: nvidia 470.141.03

**Comment by chrismaltby** [comment]
I get the feeling #1202 is related to this, we're using quite an old version of Electron now. I'm working on a branch that will migrate to the latest stable release but this will come after the release of 3.1.0

**Comment by dhollinger** [comment]
As a temporary solution, users can pass `--no-sandbox` to get around the error.

**Comment by brotenet** [comment]
v4.1.3 now works fine. (on Ubuntu, Mint etc.)
