### ISSUE TITLE
[Bug] "If Actor facing direction" doesnt work properly

### ISSUE THREAD

**Issue by dyvap** [chrismaltby/gb-studio#121]
if i use several "If actor facing direction" It doesnt matter from where i trigger the event it only execute the first of them 
For example. In the screenshot case, the only text displayed is "^"

![bug](https://user-images.githubusercontent.com/1201567/57197279-a9a42e00-6f65-11e9-837d-3ff059e105d6.PNG)

**Comment by NelsonSMG** [comment]
The same thing goes for 'if joypad input pressed'
![if joypad input pressed](https://user-images.githubusercontent.com/32785313/57198942-06442080-6f47-11e9-8c14-c382c7c77053.jpg)

**Comment by thomas-alrek** [comment]
@dyvap Is this in the same Actor script?
That won't work. The Player Actor doesn't change direction while you are interacting with the Actor that has that script (unless you do so with scripting), so naturally the second one won't fire.

**Comment by thomas-alrek** [comment]
@NelsonSMG I don't think that should work. I don't think you can check for two inputs because the inputs are registered at the start of the actor interaction, and will not change unless you poll for new input

**Comment by thomas-alrek** [comment]
@dyvap I found a bug, you where right. I have pushed a fix for this, just waiting for @chrismaltby to merge it

**Comment by RichardULZ** [comment]
@NelsonSMG This may be an issue in v1.0 on windows, Fixed on any Dev build.

Side note, since you are only checking 2 buttons, it would be better to 
```
Wait Joypad (left or A)
If Joypad Left,
  Do something
Else (expands with the arrow)
  Do what A should do.
```

**Comment by NelsonSMG** [comment]
@RichardULZ Thanks for answering. Something else I noticed was that after the player being moved I had to press the directional button (or A) again to move freely, thought I should point that out.
