### ISSUE TITLE
A Saved Variable does not get Stored in a Variable upon Resetting.

### ISSUE THREAD

**Issue by Amixofwordscombinedtomakeausername** [chrismaltby/gb-studio#1222]
**Describe the bug**
When resetting, the variable's value from saved data doesn't get stored in a variable, even though the game is saved.

**To Reproduce**
1. Insert a scene
2. Add a trigger and then add a **variable** with a value other than 0 (false) in it
3. Add another trigger with a text box that shows the **variable** using $
4. Add an event that'll attach the START button to a script
5. In said script, add the event, 'Game Data Save'
6. On the scene init add the event, 'Store Variable from Game Data In Variable', put the **variable** in both fields
8. Click on Run
9. In game, click on the first trigger, it'll set the **variable** to a value other than 0
10. Then click on the second trigger, it'll show you the value in the text box
11. Then press START, it'll save the game
12. Restart/Reset the game
13. Click on the second trigger, it'll now show you that the value is 0, even though the **variable** is saved in the game's data.

**Expected behavior**
A variable's value from a saved game slot should've been able to be stored in another variable without loading said game slot.

**Platform (please complete the following information):**
 - OS: Windows 10 Home V21H1 (OS Build 19043.2006)
 - App version 3.1.0

**Additional context**
I want to be able to store a variable's value from a saved data to another variable without having to load it first.

**Comment by RichardULZ** [comment]
Test this in an external emulator, gbstudio clears saves between builds as save data is build specific (load save game will crash if it's not) and it may clear them between runs.

Make sure the standard load/save game events work first, and then try loading var from game data after a title screen, not sure if you need a "game data exists" check. 
Also make sure you're using global variables as local variables may be confusing you (local are per trigger/actor/scene).

**Comment by Amixofwordscombinedtomakeausername** [comment]
I see what I did wrong, I tested it on GB Studio's emulator, which gave me the bug. But, it works fine on an external emulator, thanks!
