### ISSUE TITLE
[Bug] Player locked after a "Await joypad input" + "Actor move to"

### ISSUE THREAD

**Issue by Warxwell** [chrismaltby/gb-studio#124]
If I set up a trigger, normal trigger, with an Await joypad input event and then an actor move to event (with the player being the actor) and a switch scene in the else, after the player is moved I have to press the same input again in order to move freely. It can happen at random.
![if joypad input pressed2](https://user-images.githubusercontent.com/32785313/57205286-a1f78000-6f8b-11e9-9a73-e19f02509ffd.jpg)

**Comment by RichardULZ** [comment]
Could not replicate the issue on windows with latest development build.
Not specified if this was a start scene script, and whether the new scene also had a script.
