### ISSUE TITLE
Organization for assets eg folders or groups

### ISSUE THREAD

**Issue by Z3PHYRUM** [chrismaltby/gb-studio#1244]
**Is your feature request related to a problem? Please describe.**
The lists of sprites, backgrounds, music, variables, and palettes quickly becomes very large and cumbersome.

**Describe the solution you'd like**
Groups or folders for organizing these assets.

**Describe alternatives you've considered**
A strict naming convention for projects is essential but only goes so far. Especially when you have 100s of assets and need to select one in a drop-down list.

**Comment by chrismaltby** [comment]
The ability to organise assets into folders came in v4.0.0 so I think I can close this now :-)
