### ISSUE TITLE
[Request] A way to launch a script on button press "A" or "B" etc

### ISSUE THREAD

**Issue by Zzausch** [chrismaltby/gb-studio#125]
Hi, first of all thanks so much for this awesome new tool and all the hard work going into it!

I want to request a simple feature (or maybe there is already a way to do it) 

->Ability to run a script on the player whenever a button is pressed
or
-> Ability to launch script in an actor without having the player looking at the actor and pressing A/B, this would enable us to move an actor relative to the player whenever the direction buttons are pressed and always check for button presses like "A" or "B" for example.

Thanks so much and have a great day!

**Comment by thomas-alrek** [comment]
This is possible in the experimental build.

https://www.reddit.com/r/gbstudio/comments/bl1nt0/new_experimental_builds_available/

We are just waiting for @chrismaltby to merge that into the develop branch

#117

**Comment by Zzausch** [comment]
Thanks for the heads up!

**Comment by thomas-alrek** [comment]
This was fixed 3659b607bd4770272dbe45c0f362d8628bf4ebc6

**Comment by chrismaltby** [comment]
Attaching scripts to buttons is a feature now included as part of the 1.1.0 release :-)
