### ISSUE TITLE
Do you think you might be able to make it compatible with windows xp in the new update 32 bit

### ISSUE THREAD

**Issue by snes666** [chrismaltby/gb-studio#127]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [all | Windows | macOS | Linux | Other ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by snes666** [comment]
do you think you might be able to make it compatible im having a hard enough time trying to get this to work on my 2008 hp with vista and I can't upgrade to Windows 10 plus this project is for something old why don't you release for multiple versions of windows so more people can enjoy your project I love what your doing otherwise

**Comment by snes666** [comment]
@thomas-alrek

**Comment by WAUthethird** [comment]
That unfortunately is not possible. Windows XP is no longer supported by Microsoft, and XP does not support the libraries and software needed to run GB Studio. You'll need to upgrade your machine if you want to use GB Studio.

**Comment by thomas-alrek** [comment]
@snes666 Windows XP is an 18 year old system that haven't been supported for years.
The project is built with electron, which also doesn't support Windows XP.
