### ISSUE TITLE
okay so i found one of my mac machines it runs yosemite and works  but do you know where i can find custom gameboy sprites

### ISSUE THREAD

**Issue by snes666** [chrismaltby/gb-studio#128]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [all | Windows | macOS | Linux | Other ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by snes666** [comment]
@thomas-alrek

**Comment by thomas-alrek** [comment]
`Please do not submit support request here, see note at the top of this template.`

Please use the [subreddit](https://www.reddit.com/r/gbstudio) or [Discord](https://discord.gg/mkk9GYX) for this kind of requests
