### ISSUE TITLE
Player moving creates a box in front of it that makes the actor in front disappear

### ISSUE THREAD

**Issue by cccretina** [chrismaltby/gb-studio#1290]
I have created a 32x32 player, it ocupies 15 unique spaces, together with the other scene actors it didn't surpass the unique tile limit, neither did the background, yet **wenever I have more than 2 actors on a scene where my player is able to move across, it creates a box in front of the player that makes other actors partialy invisible**. I tested around and I have no idea how to fix this, I put my character in the example scene provided and I still faced the same issue. In a scene without any programing whatsoever, no events, just player and actors, still the same issue. All my sprites are proportional to the player, actors of all sizes have disapered because of this issue, even if my player is 16x16 I still face the same issue. Even if all actors on the scene are the exact same size of the player, still the same issue, even if all the other actors of the scene are identical, the same issue, in none of this events I broke the unique tile limit. I've tried reseting the character sprites multiple times, simplifying my scene, I've tried making a new file and even downloading older versions of Gbstudio, none worked. The only thing that works is removing actors from the scene, but then I would lose so much freedom in creating things. Anyway, sorry for the long text, hopefully someone can help me :)

1. create a 4 directions +movement sprite that ocupies 32x32 box;
2. Must ocupy 15 unique tiles and 8 space tiles;
3. the colision box is 16x16;
4. set the sprite as a player and place it in a scene with other actors;
5. Playtest;

there should be a box that appears around the player that makes other actors partially invisible

![image](https://github.com/chrismaltby/gb-studio/assets/87134840/f4e6c1f8-3446-435a-ac90-1af138150fe6)
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/8fcbcb9a-3de7-436e-9c35-0709fd5d17e5)
when the player is not positioned in front of the actor nothing happens;
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/ec7f4d86-4ff8-44a0-83a2-eeb232b5d4e8)
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/754e5ad1-d471-4f08-b759-98d6d8821b38)
on this scene here, no issue
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/d0b08e95-5764-40da-962a-d618f98169d8)
unless I add another actor
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/9ae5ee63-2ced-40b3-b081-74e4407476f0)
even if my player is 16x16 the issue still happens:
![image](https://github.com/chrismaltby/gb-studio/assets/87134840/c2ccc784-9997-452d-96ac-6f725feb7b3a)

This happens less with 16x16 sprites, but it still happens.
Most of the time it's just a line that appears when the player moves but I am unnable to capture it. 
It only happens if the actor is in the line of sight of the player.
I do have a scene where this doesn't happen but the player doesn't move and it's not aligned with any other actor.
There is no picture of it but even if the other actors are the exact same size as the player, it still happens.

 - OS: Windows 10 Home
 - App version 3.1.0

**Comment by patrickmollohan** [comment]
Unfortunately, this isn't an issue with GB Studio, but rather, limitations of the hardware itself. Per scanline (horizontal row of pixels), you can only have ten 8-pixel wide actors. In the case of your player being 32 pixels wide, that would count as four of the ten actors. When you go over the horizontal limit, some of the sprites will blank out like what you've shown. This is a common limitation with other retro systems as well, such as the NES or Atari 2600, and while some games use creative coding to get around it (such as in Atari 2600's Pac-Man where the sprites are flickered on and off), this sort of functionality doesn't exist in GB Studio. There are also emulators where you can optionally disable the sprite limits, but if you are building your game for real hardware, this limitation is something crucial to be aware of.

I don't know the requirements of your game, but if the benches and outhouses are static and you have no need to interact with them, I would recommend adding them to the background instead to save on actors. If you do have a need to interact with them, you might be able to replicate the functionality with the use of triggers or other events tied to an invisible actor in an area the player can't go, such as in the areas covered in red collision boxes. This would greatly depend on the vision of your game, though, so without more context, I don't know what you'd need specifically.
