### ISSUE TITLE
Cannot create rom

### ISSUE THREAD

**Issue by balika0105** [chrismaltby/gb-studio#13]
Running the program on Windows 10 Build 1809 with Windows Defender Anti-Ransomware stuff enabled, and the console says
`build/rom/game.sym: cannot create.
4294967295`
(Made a test project with the template)
![Screenshot](https://user-images.githubusercontent.com/40917873/56472024-d3cff900-6459-11e9-88e4-a801647a3d93.png)

**Comment by balika0105** [comment]
Fixed it! Defender was blocking an application, and now it runs

**Comment by ISSOtm** [comment]
Please close the issue, then
