### ISSUE TITLE
GBC Double speed mode?

### ISSUE THREAD

**Issue by RodrigoCard** [chrismaltby/gb-studio#1300]
I saw https://github.com/chrismaltby/gb-studio/pull/290
and https://develop.gbstudio.dev/docs/settings/
So, it was working at some point? Is there a good reason it is removed?

**Comment by pau-tomas** [comment]
Since 3.0 Color Mode has the double CPU option always enabled.

**Comment by RodrigoCard** [comment]
Oh, I didnt know that! Thanks!
