### ISSUE TITLE
Display Text garbled...

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#132]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

The Display Text box on the main "Background" Scene is garbled.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Begin the game... In the first Scene, trigger the sign to see the garbled text box.

* **What is the expected behavior?**

 If you go inside the building (door on left), the sign trigger text box appears as expected.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Zip file of project attached:

[Cinematic Arts - The Game.zip](https://github.com/chrismaltby/gb-studio/files/3153750/Cinematic.Arts.-.The.Game.zip)

**Comment by RichardULZ** [comment]
Please search before adding new issue threads. Warning is more visible in newer builds.
#126

**Comment by timsamoff** [comment]
> Please search before adding new issue threads. Warning is more visible in newer builds.
> #126

Apologies, I did a search, but didn't see this bug.

Thank you.
