### ISSUE TITLE
Alpha channel being shown as a solid color in sprites

### ISSUE THREAD

**Issue by Iceman253** [chrismaltby/gb-studio#1327]
Gb studio is turning the transparent parts of my sprite into one of the colors in the color pallets. I have only two sprites so far, but its only happening to one.

1. Make a sprite that doesn't take up the full 16 by 16 space.
2. import it to sprites.
3. Add it as an actor in a scene.
4. See error.

What is happening to me is that in the game world I see a full colored in 16 by 16 square, with my sprite in the middle of it.

**Screenshots**
![image](https://github.com/chrismaltby/gb-studio/assets/81322639/56dab492-b722-4dc6-95d1-e08d6c220cf2)
![image](https://github.com/chrismaltby/gb-studio/assets/81322639/e567a8ee-fe40-4712-a71f-956c7b105833)

I am using:
 - OS: Windows 11
 - App version 3

Additional information:
I tried reinstalling the program, just so you know. Didn't work. The first screenshot is in the sprite editor, and the second is in game.

**Comment by pau-tomas** [comment]
From the [docs](https://www.gbstudio.dev/docs/assets/sprites/#image-requirements)

> Sprite .pngs must only contain the following four colors:

`#071821`
`#86c06c`
`#e0f8cf`
`#65ff00`

The color `#65ff00` is used to represent a transparent background in game and will be invisible in-game and in the World Editor.

**Comment by pau-tomas** [comment]
Yes. The pngs can only use the colors mentioned under the doc. Te colorization happens in GB Studio Sprite Editor by picking palettes for the sprite tiles.
