### ISSUE TITLE
Could you add 5 colors?

### ISSUE THREAD

**Issue by Iceman253** [chrismaltby/gb-studio#1328]
I was wondering why you can make 4 colors in the pallet option when there are only 3 visible colors. The fourth is transparent. Could someone either explain this to me or add it in?

**Comment by nielsderijk** [comment]
For sprites, the Game Boy hardware maps color #0 to transparency. 
For backgrounds, you don't have transparency and can use all 4.

Please refer back to the guides first before you start opening tickets here. ;-) 
- https://www.gbstudio.dev/docs/assets/backgrounds
- https://www.gbstudio.dev/docs/assets/sprites#image-requirements
