### ISSUE TITLE
Not possible to change the animation state of projectiles

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1329]
**Describe the bug**
Currently it seems impossible to change the animation state of projectiles, even though a dropdown is available for it in the "Launch projectile" event.

**To Reproduce**
1. Add a "Launch projectile" event
2. Pick an animation state from the dropdown other than Default
3. Nothing happens, the Default state is shown

**Expected behavior**
The animation state shown is the animation state that was selected.

**Screenshots**
<img width="466" alt="Screenshot 2024-01-19 at 16 00 38" src="https://github.com/chrismaltby/gb-studio/assets/20700995/5d162e63-d74f-4416-89fa-68218bb302ba">

**Platform (please complete the following information):**
 - OS: macOS Sonoma 14.1.1 
 - App version 3.2.0 RC1

**Comment by chrismaltby** [comment]
Ah I'm sure that worked at one point. I've just pushed a fix for this in https://github.com/chrismaltby/gb-studio/commit/af0aa2b723cc05008b2b997e78059a4f0b5e5f4c
