### ISSUE TITLE
Editing a variable's name sometimes triggers an erroneous jump to another variable

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1333]
**Describe the bug**
GB Studio erroneously jumps to another variable in the variables list when I am trying to edit the name of a variable

**To Reproduce**
1. Click on a random variable in the list of variables
2. Jump to a variable by pressing a random key on your keyboard ("C" in the example video)
3. Now click on the variable's name field and then try to edit the name by typing an S or a B
4. GB Studio unexpectedly jumps back to the variables' list and adds an S or a B to another variable (probably to the first name that comes up?)

**Expected behavior**
I expect to be able to edit the variable's name without interruption

**VIdeo**
https://github.com/chrismaltby/gb-studio/assets/20700995/2d71b259-a585-496a-a598-c65be55e51e0

**Platform (please complete the following information):**
- OS: macOS Sonoma 14.1.1
- App version 3.2.0 RC1

**Comment by chrismaltby** [comment]
Hi @nielsderijk this should now be fixed in 9e2966a9d35ed0237d9a4dad5337a3636aca9bb4

**Comment by nielsderijk** [comment]
Nice! This was a nasty one.
