### ISSUE TITLE
Data manager is currently broken in latest dev build of GB Studio after migrating a project from GB Studio 3.1.0

### ISSUE THREAD

**Issue by Amixofwordscombinedtomakeausername** [chrismaltby/gb-studio#1338]
**Describe the bug**
In the latest dev build of GB Studio (3.2.0-rc.1), when you migrate a project created in GB Studio 3.1.0 then build the project from there. It seems to not work as intended and breaks after the data manager fails to identify 'allocated_sprite_tiles' in certain parts of the script.

**To Reproduce**
1. Migrate any project created in GB Studio 3.1.0 to the latest dev build.
2. Choose any option to build the project.
3. See data manager error.

**Expected behavior**
Should be able to build as normal.

**Screenshots**
![GBStudioErrorWhenBuilding](https://github.com/chrismaltby/gb-studio/assets/112746887/84ac576c-5a89-4d5b-9ef1-7010acb950d7)

**Platform (please complete the following information):**
 - OS: Windows 10 Home
 - App version 3.2.0-rc.1

**Additional context**
Not sure if this problem is just only occurring for me.

**Comment by pau-tomas** [comment]
This is due to one of the plugin used in your project modifies the `actor.c` file from the engine and needs to be updated to work with the latest version.

**Comment by Amixofwordscombinedtomakeausername** [comment]
Ah, I see then. Thanks!
