### ISSUE TITLE
Several Triggers in a row "cancel each other out".

### ISSUE THREAD

**Issue by Iceman253** [chrismaltby/gb-studio#1345]
**Describe the bug**
In a room in my game (a kitchen) I have several appliances set right next to each other, and since I didn't want to turn them into actors, I used triggers for the interaction. I did this by attaching a "Add Script to A Button" event and a "Remove Script" event when you walk out. When you walk into the trigger right next to it, with no room in between, the trigger doesn't work. Neither does the one that you had just used when you walk into it or anything along the line of triggers. I also tried removing the script before adding a script, but it didn't work either.

**To Reproduce**
1.  Create a scene.
2. Add several triggers next to each other with no space in between.
3. Attach the same program to each, I'm not sure if this is a bug with just adding a script to a button or anything. Walk in between them without moving outside of the trigger area and attempt to activate the code.

**Expected behavior**
Nothing should happen after you walk in between them.

**Screenshots**
In all of these, I am pressing the "A" button.
![image](https://github.com/chrismaltby/gb-studio/assets/81322639/1656ee80-200b-4e5e-ae5a-a407b2e1e5b4)
![image](https://github.com/chrismaltby/gb-studio/assets/81322639/ffa504c6-16c8-409e-91b9-5091695a046f)
![image](https://github.com/chrismaltby/gb-studio/assets/81322639/afd22a84-93d0-4c87-a9e7-b001f8f71d95)

**Platform (please complete the following information):**
 - Windows 11 Pro 23H2
 - GB Studio 3.2

**Comment by pau-tomas** [comment]
What I think it's happening here is that when moving from Trigger A to Trigger B, `Trigger B.On Enter` executes before `Trigger A.On Leave`. 

Meaning that order of execution is:

```
Trigger B.On Enter
  - Attach Script to Button
``` 
replacing whatever was attached when entering Trigger A, and then
```Trigger A.On Leave
  - Remove Script
```
and thus removing whatever was attached when entering Trigger B.


I think it's still the case that there's no guarantee about the execution order of scripts (as mentioned in https://github.com/chrismaltby/gbvm/pull/160) but assuming in your case `On Enter > On Leave` it's consistent, then you should be able to delay the execution of `On Enter` by adding a GBVM block before the `On Enter` event like the one below:

<img width="446" alt="image" src="https://github.com/chrismaltby/gb-studio/assets/54246642/71e8a786-0e4c-4963-8d1f-4998ad861d1f">
