### ISSUE TITLE
The transfer data link event no longer functions in the latest release.

### ISSUE THREAD

**Issue by Amixofwordscombinedtomakeausername** [chrismaltby/gb-studio#1349]
**Describe the bug**
Since the release of GB Studio 3.2.0, the transfer data link event no longer works as expected and now freezes the game without anyway to procced.

**To Reproduce**
1. Create or open a project with link cable events in GB Studio 3.2.0.
2. Build the rom and use an emulator like BGB that supports link cable.
3. Host a link on one window while having the other window join the host.
4. Transfer data to see error.

**Expected behavior**
The transfer data link event should work after the host initiated the transfer and the person joining the host completes the transfer.

**Video Example**
https://github.com/chrismaltby/gb-studio/assets/112746887/78c276ae-0b26-4a31-b566-97b0923a0341

**Platform (please complete the following information):**
 - OS: Windows 10 Home
 - App version 3.2.0

**Additional context**
This event was working fine in previous versions of GB Studio.

**Comment by FirewallFury** [comment]
Yes, please fix this, I need it for me new game
