### ISSUE TITLE
Plugins no longer work (latest develop, 25a44b0)

### ISSUE THREAD

**Issue by animasodo** [chrismaltby/gb-studio#1364]
**Describe the bug**
After updating to the latest develop build, plugins no longer seem to compile. They *do* show up in the IDE but the compiler complains that there's no plugin matching the name.

`No compiler for command "EVENT_TEXT_FANCY". Are you missing a plugin? {"scene":"Scene 3","scriptType":"actor","actor":"Chest"}`

Here's a minimal example project, it's extremely easy to reproduce as it seems to affect all plugins I tried:
[NoPlugin.zip](https://github.com/chrismaltby/gb-studio/files/14396014/NoPlugin.zip)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro
 - App version: develop, commit 25a44b0

**Comment by chrismaltby** [comment]
Hi @animasodo This should be fixed in the latest develop builds now. I'm just in the middle of a large refactor of this part of the codebase which is needed to move to the latest versions of Electron so it's likely things like this might break again in develop before I'm done though
