### ISSUE TITLE
[Develop branch] Issues on windows after clearing recent projects

### ISSUE THREAD

**Issue by pau-tomas** [chrismaltby/gb-studio#1373]
**Describe the bug**
[Reported by Tronimal via Discord DMs]

Projects appear with wrong title in the Project window and songs won't load after clearing recent projects.

Might be related to paths like https://github.com/chrismaltby/gb-studio/pull/1372

**To Reproduce**

1. Start the latest develop build on Windows
2. If there's no recent projects, create a new project.
3. Open one of the recent project and check everything works ok
4. Close the project and clear recent projects
5. Open a project from the "Open Project" option
6. Navigate to Music and try to load a song. Observe error.
7. Switch projects. Observe that the project doesn't appear in the recent list with the right title.

**Expected behavior**
Projects appear with the right title in recent projects and songs load without error.

**Screenshots**

![image](https://github.com/chrismaltby/gb-studio/assets/54246642/bade7481-6d4b-48d9-8087-1fba1fcd8dd5)

![image](https://github.com/chrismaltby/gb-studio/assets/54246642/d238c78a-d367-41fb-a28e-c14ded097e30)

**Platform (please complete the following information):**
 - OS: Windows
 - Latest develop build

**Comment by chrismaltby** [comment]
I think we fixed this one but forgot to close :-)
