### ISSUE TITLE
Play a specific scene

### ISSUE THREAD

**Issue by Audio-Rochey** [chrismaltby/gb-studio#138]
My game is growing exponentially.
I'd like the ability to jump to a specific scene that i've developed to test it's logic, rather than jump back to the start of the game.
My workaround so far is to change the pointer after the startup to the scene I'm debugging, but it'd be easier if there was a right-click "test scene" that load the emulator appropriately.

Cheers

Rochey

  - Version: 1.0.0
  - Platform: Windows

**Comment by chrismaltby** [comment]
Hi @Audio-Rochey did you know that you can hover over any scene and press "P" on your keyboard to reset the player start to just under your cursor. I tend to just use that to quickly set the player start position then "Ctrl+B" to run (so should just be hover then two keypresses). I guess the problem with with a test scene function is you'd need to set where you want the player to start anyway so it probably be as many key presses.
Did you know about that feature and if you didn't do you think that solves your issue?

**Comment by Audio-Rochey** [comment]
solved. thank you.
apologies for wasting your time on that one.
