### ISSUE TITLE
There is currently no GBVM command to remove SFX from text

### ISSUE THREAD

**Issue by VRMLNism** [chrismaltby/gb-studio#1391]
VM_SET_TEXT_SOUND allows sounds to be added to text (which works great, might I add), but there is no way to remove this functionality once it is set. If there were an additional command that allowed the sound to be removed similar to the way that timers can be started and stopped, it would be very helpful.

Thanks!

**Comment by pau-tomas** [comment]
Does `VM_SET_TEXT_SOUND 0, 0` work?

**Comment by VRMLNism** [comment]
It did work. Thank you!
