### ISSUE TITLE
Bug with resetting zoom.

### ISSUE THREAD

**Issue by arronhunt** [chrismaltby/gb-studio#14]
**Steps to reproduce:**

1. In "Game World" view, zoom to 200%
2. Switch to another view, like "Sprites"
3. Switch back to "Game World" view

Note that the zoom level displays `200%` but the actual zoom view is at 100%. Cursor positions also don't align with the actual cursor position. 

![Apr-21-2019 11-38-07](https://user-images.githubusercontent.com/298336/56474108-03670d00-642a-11e9-9b24-462cd76e9c11.gif)

**Comment by chrismaltby** [comment]
Hi Arron thanks for this, I spotted the same issue and was hoping to sneak in a fix before anyone noticed! This should be fixed in the develop branch from commit c1dc58a4de514875a1ec1a919db8facd8448437b. Getting a few other bug fixes together ready for a 1.0.1 release.

**Comment by chrismaltby** [comment]
This zoom bug is now fixed as part of the 1.1.0 release :-)
