### ISSUE TITLE
[Request] Colour and Bold the Save variable button.

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#140]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the current behavior?**
![image](https://user-images.githubusercontent.com/34431457/57496045-1718db80-7325-11e9-82ba-911068f2af60.png)
When renaming a variable, some people (including myself) have clicked off or not hit return before saving, and not realized that the variable needed to save, some have had compile issues because of this. Rename and Save currently have the same styling.

* **Solution**
Perhaps Bold and colour the **Save** text red so that it is more obvious when you have missed it.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [all]

**Comment by chrismaltby** [comment]
Updated as suggested in 30b987c723b3af5ffc2e12613f131b10ed1e6a1f it should have also been saving when the input lost focus which I've fixed now also.
Recently added the ability to rename events using the dropdown on the right and this update now also matches the style of variable renaming

<img width="270" alt="Screenshot 2019-05-10 at 12 02 22" src="https://user-images.githubusercontent.com/16776042/57522945-7eca2900-731b-11e9-8e3b-d978dc44cf46.png">
