### ISSUE TITLE
Bug: Flags appear not to be setting/working correctly in GB Studio 4 Beta 1

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1407]
**Describe the bug**
Changing flags on a variable seems to cause them to break.

**To Reproduce**
1. Create an if flag 1 is set event and leave blank, on the else of it add a dialogue 'flag 1 set'
2. After this set flag 1
3. Bind a button to reload the scene
4. Check that the flag 1 set message only appears the first time, before the set flag 1 is set
5. Now change flag 1 to flag 4 and repeat

**Expected behavior**
The dialogue should only show up once, because the flag has been set. This only happens with flag 1 before it being changed to flag 4, see video –

https://github.com/chrismaltby/gb-studio/assets/28432913/4710aab4-51f1-448e-ada9-4b6066251eb5

**Platform (please complete the following information):**
 - OS: 14.2.1 (23C71)
 - App version 4 beta 1

**Additional context**

**Comment by pau-tomas** [comment]
Thanks for reporting @joeledge  , I think I fixed the issue with #1408 will ping you once it merges and can be tested
