### ISSUE TITLE
Clicking on the effect column in tracker mode seems to freeze GB Studio 4 Beta 1.

### ISSUE THREAD

**Issue by Amixofwordscombinedtomakeausername** [chrismaltby/gb-studio#1409]
**Describe the bug**
In the current beta build of GB Studio 4, I've encountered a bug where entering tracker mode in the music editor and clicking on the effect column would freeze GB Studio until I close out of the program.

**To Reproduce**
1. Go to 'Music'
2. Click on any song
3. Enter tracker mode
4. Click on the effect column
5. See Bug

**Expected behavior**
Clicking on the effect column in tracker mode shouldn't freeze GB Studio.

**Platform (please complete the following information):**
 - OS: Windows 10 Home
 - App version: 4 Beta 1

**Additional context**
This issue was absent in previous versions of GB Studio.

**Comment by pau-tomas** [comment]
Investigating, seems like the first change where this broke is 16d252d1704b62b82f5e033aecda7fbad52fc001

**Comment by pau-tomas** [comment]
Thanks for reporting @Amixofwordscombinedtomakeausername ! I think I fixed the issue with https://github.com/chrismaltby/gb-studio/pull/1411, will ping you once it merges and can be tested

**Comment by gregtour** [comment]
Thanks Pau!!
