### ISSUE TITLE
Leaving "Enable Super GB Mode" enabled when switching to "Color Only" prevents build from running

### ISSUE THREAD

**Issue by mauired** [chrismaltby/gb-studio#1431]
When changing the color mode in the color options in settings to "color only", if the game previously had the "enable super gb mode" option enabled, the build may error out when attempting to run. This appears to only happen on the first instances of attempting to build following correction by the user.

**To Reproduce**
1. Create a new project in a pre-4.0 version of GB Studio.
2. Enable the "Enable Super GB Mode" option.
3. Open the project in the 4.0 beta release.
4. Change the color mode to "Color Only"
5. Attempt to run the game.
6. See error.

**Expected behavior**
Super GB options should not effect running of color only games. This error can be fixed by the user by switching back to a non-color only mode, disabling super gb mode, and then switching back. Restarting the program will not fix this error. Following the error being fixed, going back to enable super gb mode again does not replicate the initial issue.

**Platform:**
 - OS: Windows 11
 - App version: v4.0.0-beta1

**Comment by chrismaltby** [comment]
Thanks for raising this issue, I've confirmed this is happening for me too and have implemented a fix in https://github.com/chrismaltby/gb-studio/commit/c65c1cc45aa28ba7103e32f2adabb9dce636217e which will become part of beta 3
