### ISSUE TITLE
Copy / Paste stops working when debugger is open

### ISSUE THREAD

**Issue by attackemartin** [chrismaltby/gb-studio#1440]
**Describe the bug**
The function to copy and paste objects like triggers or enemies stops working after opening the debugger. 
It functions again, after closing it, or after deselecting "build log" 

**To Reproduce**
1. Open GB Studio
2. Open the debugger in the bottom
3. Try to copy and paste an enemy or trigger via CMD C and CMD V
4. Nothing happens
5. Close the debugger in the bottom
6. Copy & Paste works again

**Expected behavior**
Copy and Paste should work just fine

**Platform (please complete the following information):**
 - OS: MacOS 14.5 (23F79) (M1 Macbook)
 - App version: v4.0.0-rc.1

**Additional Informations**
Tested in color only mode

**Comment by chrismaltby** [comment]
Looks like if you ever clicked into the build log it would take the focus and all copy/paste events were being handled there, and clicking out of the log wasn't causing it to lose focus. Found a few other places where this could happen too.

I've made an update so if you click into the build log copy/paste will work there (so you can copy error messages for example) but if you click back into the World view copy/paste scenes, actors triggers etc will work again. This will be included in v4.0.0-rc.2
