### ISSUE TITLE
Actor "Change Sprite" changes sprites on multiple Actors

### ISSUE THREAD

**Issue by attackemartin** [chrismaltby/gb-studio#1442]
**Describe the bug**
If I have more than 2 enemies in a level with the same sprite, and they should switch to another sprite on-hit with the player (via custom script, given to every enemy on hit), then, when hitting the second enemy, the third and all other enemies after that will have their sprite changed as well. 

If you do that without the use of a custom script, but rather give every enemy the same functions (on hit: change sprite to x), then all three will change the sprite on hitting the first enemy.

**To Reproduce**
1. Add three or more enemies to a scene with the same sprite
2. Give them a script, that changes their individual sprite on hit with the player
3. Run a build and hit two enemies

**Expected behavior**
It should just change the sprite from the enemy that was hit

**Screenshots**
Custom script:
![Bildschirmfoto 2024-06-07 um 16 01 34](https://github.com/chrismaltby/gb-studio/assets/1195020/04fca84f-2855-4871-a3b2-13d9ab94de21)

On hit enemy calling custom script:
![Bildschirmfoto 2024-06-07 um 16 02 11](https://github.com/chrismaltby/gb-studio/assets/1195020/ce3f85ed-9d8f-4495-b812-b44cfe32ff2f)

Screen capture: 
https://github.com/chrismaltby/gb-studio/assets/1195020/4f47cd92-b593-429a-844a-06956c911ed3

**Platform (please complete the following information):**
 - OS: macOS 14.5 (23F79)
 - App version v4.0.0-rc.1

**Additional context**
Worked in 3.2.1

**Comment by pau-tomas** [comment]
Thanks for the report! Could you upload the project to the issue?

**Comment by attackemartin** [comment]
wrote you on discord, but just for documentary reasons:
[test-4-0.zip](https://github.com/user-attachments/files/15754412/test-4-0.zip)

**Comment by chrismaltby** [comment]
Thanks @attackemartin that project was very useful in tracking down the issue, a fix will be included in v4.0.0-rc.2

**Comment by attackemartin** [comment]
awesome!
