### ISSUE TITLE
Long branch labels create empty spaces in the code panel

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1445]
**Describe the bug**
When there's long branch labels, unwanted gaps appear in the code panel (making scroller harder instead of easier).

**To Reproduce**
1. Create a long if expression
2. Create some more events after that

**Expected behavior**
Abbreviation of the branch labels when the label overflows the height of the branch.

**Screenshots**
<img width="969" alt="Screenshot 2024-06-09 at 20 59 07" src="https://github.com/chrismaltby/gb-studio/assets/20700995/a5ae8853-b0a1-4573-b5ab-882ef0ea5e4a">

**Platform (please complete the following information):**
 - OS: MacOS 14.5
 - GB Studio 4.0.0 RC1

**Comment by chrismaltby** [comment]
Ah yes, good point! I've updated the labels to trim with ellipsis now if there's not enough vertical space rather than creating these gaps. This will be included in v4.0.0-rc.2 hopefully within the next few days
