### ISSUE TITLE
#1462 Breaks compilation

### ISSUE THREAD

**Issue by Hellscaped** [chrismaltby/gb-studio#1465]
**Describe the bug**
Notorization fails while compiling the package, this began with the zh-CN.json PR merge.

**To Reproduce**
1. Compile the package

**Expected behavior**
It should compile correctly
**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. macOS 10.14.1] Irrelevant, all builds are failing.
 - App version [e.g. 1.1.0]

**Additional context**

I was trying to update the gb-studio-git AUR package PKGBUILD before you merged the PR, and it was compiling fine. Now with this zh-CN.json merge its failing.
[CI](
https://github.com/chrismaltby/gb-studio/actions/runs/9659266357/job/26642290348)

**Comment by Hellscaped** [comment]
a solution would be to revert it for now

**Comment by Hellscaped** [comment]
My PKGBUILD problem is solved, but I'm leaving this open since this is still a problem for the mac users

**Comment by chrismaltby** [comment]
Looks like the Apple notorization was just temporarily down (logs were saying the API was returning a HTTP error earlier today), was nothing to do with the recently merged localisation PR. I've re-run the GitHub Action on the develop branch with no code changes and it's working now. Thanks for raising this though
