### ISSUE TITLE
Music files with space in their name breaks compiling

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#147]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
If one of the .mod files has a space in its filename, the project wont build anymore.

```log
- Multiple definition of _music_track_110
- Multiple definition of _music_track_111
- Multiple definition of _music_track_112
- Multiple definition of _music_track_113
-
- make: *** [build/rom/game.gb] Error 1
-
- 2
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Rename sample.mod to have a space in its filename.

* **What is the expected behavior?**
This should "just work"

* **What is the motivation / use case for changing the behavior?**
Users shouldnt't need to consider what their files are named.

* **Please tell us about your environment:**

  - Version: 1.1.0-rc.2
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Unable to reproduce this on Mac or Windows, both are accepting .mod files with spaces in the filenames for me, could you attach a small project with the issue?

**Comment by thomas-alrek** [comment]
This issue was originally reported by user "Kazy" on Discord. Can send the project privately to you, as I don't know if it's okay to post it publicly.

**Comment by KitF** [comment]
Just so you know you're looking for a project from "Krazy Productions", I uploaded a bugged project but it was for a different issue.

**Comment by thomas-alrek** [comment]
This was not related to the file name, but a separate issue with mod2gbt, because the tracks didn't get unique ids.
