### ISSUE TITLE
When an actor reach X0 , it moves to right .

### ISSUE THREAD

**Issue by alexspector** [chrismaltby/gb-studio#1472]
When any actor placed on the scene goes on X=0, whatever the script or if it's the player character, it will automaticaly moves at a regular speed to the right.

**To Reproduce**
1. Add a new actor into a scene
2. Add a move relative to left X-1
3. Play the game and wait.
4. See that when the actor reach X=0 it will moves on right.

https://github.com/chrismaltby/gb-studio/assets/30384861/f34754b2-2444-48d9-8845-1cb42c5cfa91

**Comment by chrismaltby** [comment]
Thanks @alexspector I've spotted what the issue was and have merged a fix into the develop branch. You can get a dev build including the fix here https://github.com/chrismaltby/gb-studio/actions/runs/9765019090 I think this should fix the issue you're seeing

**Comment by alexspector** [comment]
Thanks @chrismaltby, that's a great news.  Congrats for your amazing work on GB Studio.

**Comment by chrismaltby** [comment]
Just closing this as it should be fixed now as of 4.1.2 :-) https://chrismaltby.itch.io/gb-studio
