### ISSUE TITLE
Actor Tile X/Y reference in custom script is returning value from different actor

### ISSUE THREAD

**Issue by janoi152** [chrismaltby/gb-studio#1486]
**Describe the bug**
I created a custom script which has an Actor as an input parameter and uses a reference to this actor's tile position in a Move To event. When I call this script from two actors at the same time the returned value from this reference is from one of the actors in both instances of the script.

**To Reproduce**
Create a custom script like this:
![script](https://github.com/user-attachments/assets/332a8d61-9b6f-4ce3-b369-b66821fbdca4)

Then add two actors with a Call Script event and reference to self as input parameter:
![actor](https://github.com/user-attachments/assets/43e88877-c658-4059-8018-cc9e2346f232)
![actor2](https://github.com/user-attachments/assets/b236faa2-b042-4618-a5c1-142c8520da49)

**Expected behavior**
When player presses an arrow key the actors should move to the screen border based on the arrow that was pressed.

**Buggy behavior**
But what happens is:
- If I press right arrow key then one of the actors goes to the right border as it should but the other one goes to the final position of the first one (it goes right to the border and then down to the position of the first actor).
- If I press up arrow key one of the actors goes right to the X position of the other one and then up to the screen border (the other one goes straight up). Then if I press left arrow key they both go to the left border and the game freezes. At least the rendering is freezed but from debugger I can see that the scripts are still running and they both seem to have the same input (the input contains reference to one of the actors in both instances of the script when it should be one actor for the first instance and the other actor for the second insance).

**Platform (please complete the following information):**
Windows 10, GB Studio 4.0.0 (I just updated from 3.2.1 in hope that it would fix this issue but it didn't)

**Comment by janoi152** [comment]
I found out that the freezing is probably a separate bug. When I place the events directly to the actors' On Update then the target movement positions are correct (the Tile X/Y references work correctly). But nevertheless the game keeps freezing. I have 3 actors all with the same events. When I press left arrow key they all start moving to the left border. Once two of them hit the border the game freezes. Once again I can see in the debugger that the scripts are running but the game rendering is stuck on the frame where two actors hit the border.

**Comment by chrismaltby** [comment]
Hi @janoi152 GB Studio 4.0.1 has just been released and contains fixes for actor references within scripts so your first issue now seems to be fixed. You're right that it seems like the freezing issue is something else though which doesn't appear to be fixed with 4.0.1 so I'll investigate this to try and fix in the next release

**Comment by janoi152** [comment]
Thank you for the information, I'll check the new version out.

**Comment by chrismaltby** [comment]
Hi @janoi152 testing this example again in 4.1.2 released today I think this issue is fixed now :-) https://chrismaltby.itch.io/gb-studio
