### ISSUE TITLE
Minor accessibility/contrast issue

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1489]
**Describe the bug**
The label appearing when moving the mouse around a scene showing the X/Y values (super useful) is a lot harder to read in v4 due to low contrast, perhaps the wrong font colour? See attached.

Setting it to the dark grey/black as 'Preview as Monochrome' is set in would increase legibility (as would bumping up the font size a little but not sure if this has UI knock on effects, so just the font colour would be an improvement).

<img width="416" alt="Screenshot 2024-07-24 at 13 17 07" src="https://github.com/user-attachments/assets/9ec98e05-d144-4a0a-88f0-60ac16150f30">

**Comment by chrismaltby** [comment]
Hi @joeledge I've increased the contrast of that label in 4.0.2 which hopefully should be easier to read. The font size looks a little smaller than normal in your screenshot though, by any chance have you set you UI Elements Scaling to be less than 100% in the application Settings?

**Comment by joeledge** [comment]
Excellent, that's nice and clear for me now, thanks for including in the latest version! – <img width="685" alt="Screenshot 2024-07-29 at 17 11 42" src="https://github.com/user-attachments/assets/7f53a6aa-9f28-4dd2-8967-3dc5b9088055">

Application settings UI Elements Scaling is set to 100%, perhaps it's the resolution of my second (fairly big) monitor, the above screenshot is from my laptop screen.
