### ISSUE TITLE
Using the Random function in a Value in an If event causes a stack error

### ISSUE THREAD

**Issue by kinostl** [chrismaltby/gb-studio#1492]
**Describe the bug**
Using the Random function via the new Value system inside of an If statement will cause the following error:
`Error: Compiling failed with error "Error: Script was not stack neutral! Stack shrank by 1". {"scene":"Scene 1","scriptType":"scene"}`

**To Reproduce**

Create an "if rnd()==0" event and attempt to run, build, or export project source.
Project will not do action due to error.

**Expected behavior**
Using a math function in a Value in an If statement should not cause a compilation error.

**Screenshots**
![image](https://github.com/user-attachments/assets/9496a29c-6353-4aa8-a9bd-8b05ee847748)

**Platform (please complete the following information):**
 - OS: Linux
 - App version 4.0.1

**Comment by kinostl** [comment]
Work arounds such as using temp to evaluate math or use a random in a value works as expected.

**Comment by chrismaltby** [comment]
Thanks @kinostl was a one word change to fix the problem 🤦‍♂️ Implemented this fix now in 4.0.2 which I've released today
