### ISSUE TITLE
Script builder inserting incorrect symbol when using local vars

### ISSUE THREAD

**Issue by Steinbeuge** [chrismaltby/gb-studio#1495]
**Describe the bug**

Cannot use local vars as inputs to plugins in some cases, the script builder places the wrong symbol in when using a local
`?ASlink-Warning-Undefined Global 'L0' referenced by module 'actor_4_update'`

An example of the generated VM code:
```
_actor_4_update::
1$:
        VM_PUSH_VALUE           L1 ; no good
        VM_PUSH_REFERENCE       1
        VM_CALL_NATIVE          b_beugs_actor_move_bounce, _beugs_actor_move_bounce
        VM_SET                  VAR_S1A1_LOCAL_1, .ARG1 ; but this one is correct?
        VM_POP                  2
        ; Idle
        VM_IDLE
```

**To Reproduce**
Make a plugin that pushes a variable to the stack, or assigns one var to another. Set one of the variables to a $local value on the actor running the event.
Example project supplied.

**Expected behavior**
I would expect locals to work exactly the same as global vars.

**Screen Shot**
![image](https://github.com/user-attachments/assets/a83c5012-a5f6-4123-8c44-938a2d5d2b7d)

**Platform (please complete the following information):**
Win 10 Version	10.0.19045 Build 19045
Processor	Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)
Tested on both GB Studio 4.0.0 and 4.0.2

**Additional context**
It would be nice if there was a shorthand to locals in GBVM and/or native that was performance focused (doesn't require constructing a string every frame or the likes).
Or if GBVM actually adopted this symbol eg "VM_SET .L0, .ARG1" to allow designers to make reusable scripts

[plugin test beugs.zip](https://github.com/user-attachments/files/16449090/plugin.test.beugs.zip)

**Comment by chrismaltby** [comment]
Hi @Steinbeuge in the project you supplied it looks like you're using the wrong function to assign the value of one variable to another.
You were using `variableSetToValue(variable, value)` which sets the variable to a constant value, so if this had worked Test1 would have contained the address of Test2, not the value of it. I think the function you wanted was `variableCopy(setVariable, otherVariable)`

e.g. 
```
export const compile = (input, helpers) => {
    const { variableCopy } = helpers;
    const { Test1, Test2} = input;
    variableCopy(Test1, Test2);
  }; 
```
would copy the value of Test2 into Test1

I'm not sure the code you were using to push values onto the stack but one thing to be careful about there is that you need to account for the differences when your plugin is being used in a script when the variables are being passed by reference vs just being used normally. 

When you use your plugin like this 

<img width="418" alt="Screenshot 2024-08-06 at 15 28 03" src="https://github.com/user-attachments/assets/af653d44-a5ec-46a0-96c7-58784efc59f1">

Test1 and Test2 will no longer be simple strings, but objects that define indirectly referenced values. Confusing I know but if you wanted to push a variable to the stack what you'd actually want is something like this 
```
    const variableAlias = getVariableAlias(variable);
    if (_isIndirectVariable(variableAlias)) { 
      // Handle variable being an argument passed to a script
     _stackPushInd(variableAlias);
    } else {
     // Variable is a normal id 
      _stackPush(variableAlias);
    }
```
To make matters worse it looks like `_isIndirectVariable` isn't currently exposed to plugins right now so you would have to define it manually by adding this into your plugin
```
const isObject = (value) => {
  return typeof value === "object" && value !== null;
};

const _isFunctionArg = (x) => {
  return isObject(x) && typeof x["type"] === "string" && x.type === "argument";
};

const _isIndirectVariable = (x) => {
  return _isFunctionArg(x) && x.indirect;
};
```
I'm going to make an update to [ScriptBuilder](https://github.com/chrismaltby/gb-studio/blob/develop/src/lib/compiler/scriptBuilder.ts) to 
1. Expose `_isIndirectVariable` to plugins
2. Add a `stackPushVariable(variable)` function which will handle the case where the variable is an indirect script argument automatically
Which will be part of the next GB Studio release.

One of the big problems though is that the functions exposed to plugins aren't currently documented. My plan over the next few versions is to start stabilising the API given to plugins, and to provide more helper functions for common tasks (like pushing a variable onto the stack). If you've got some thoughts on functions that would be useful I'd be happy to hear about them

**Comment by chrismaltby** [comment]
The develop build now exposes `_isIndirectVariable` and `_stackPushVariable` to plugins added in 220c88ea848dcf1e560fc61d55b6bced13b36b69 the build can be downloaded for testing at https://github.com/chrismaltby/gb-studio/actions/runs/10269594936
