### ISSUE TITLE
[Missing option/feature] missing translation ?

### ISSUE THREAD

**Issue by ReptiIe** [chrismaltby/gb-studio#1496]
EDIT: 
### ISSUE 1: missing feature

THIS ONE IS SOLVED

**Describe the bug**
Reading docs at the moment, I am in section: Project Editor > Player > Scripting.
There is mention that we can change player graphics, by using events.

I notice that there are 2 event commands for this:
1) set actor sprite sheet
2) set player sprite sheet

Both commands are able to change the sprite sheet, cool. But as in docs it is mention, this is only temporary. Once I will hit a different scene, sprite sheet will go back to normal. OK. Going on with the docs, there is mention that I need to ... (??)
Check option/Set option/Use option/Use command - not sure what - but it should be:
**Replace Default For Scene Type**

And yes, this is the thing that, I am not able to notice where is?
I am blind here, or I am missing something?

**Platform (please complete the following information):**
 - OS: Win11
 - App version: 4.0.2

### Issue. 2 Missing translation?
It seems like there is a missing translation (or it is linked not properly) 
The word is "**If**" and you can find it in the Control Flow
![image](https://github.com/user-attachments/assets/1c051ece-9c56-498a-9bd9-e62a2acf9646)

As I see it is translated in the file, but here it does not show.

Also another one is **NONE** in the collision group
![image](https://github.com/user-attachments/assets/1cccff97-fd96-4e40-8ac2-3b77f0387e5b)

**Comment by pau-tomas** [comment]
The "Replace Default For Scene Type"  was removed in [4.0.1](https://github.com/chrismaltby/gb-studio/blob/develop/CHANGELOG.md#removed) as it never worked in the past. The [documentation](https://www.gbstudio.dev/docs/project-editor/player#scripting) should be updated to reflect that.

**Comment by ReptiIe** [comment]
@pau-tomas THANK YOU! That make sense! 😄 
And I am looking for something that does not exist.

**Comment by ReptiIe** [comment]
So I notice for now there are 2 words (or even 3) that are not translated...

1) it is **IF** in the add event section (you can see it in the screen, in post 1)
2) it is **NONE** in the collision group (also in the post 1)

I believe I also notice "Player", but right now I can not notice where it was, so once I will find it again I will write it down (it also might be my imagination and I mistake this "Player" as the name of the sprite now that I think about it...)

**Comment by chrismaltby** [comment]
Hi @ReptiIe I've updated the docs to remove that reference to the removed "Replace Default For Scene Type" feature now.

I've also fixed the collision mask picker localisation for "None", and "Player" (it was in the "Launch Projectile" event version of the input)

And the IF event, looks like you managed to fix that one in your latest localisation file.

Think that's everything for now! Not sure if you saw but gave you a shout out on Twitter the other day :-) https://x.com/maltby/status/1817985618800165094

**Comment by ReptiIe** [comment]
Silly me @chrismaltby  😄 
That is true (about IF), I did now recall that there was this in the file and I did not update it yet (but notice it, and change it before making even PL Docs).
OK So here we have all clear, we can close this section.

On Twitter -
Yes I did notice, thank you! People from my community told me and were quite surprised.
