### ISSUE TITLE
Multiple choice bad view

### ISSUE THREAD

**Issue by mschenatti** [chrismaltby/gb-studio#15]
(1167cfad161cc6394b11eab05400d978b508bbe0)
Using the "Multiple Choice" event, I get the view error shown below
![image](https://user-images.githubusercontent.com/28539105/56474665-1f47ce80-647d-11e9-8ce9-a175365040e2.png)

**Comment by DerekLF** [comment]
What is it supposed to say?

**Comment by chrismaltby** [comment]
Oh I see, it looks like you didn't provide any text for the two choices in the event

<img width="297" alt="Screenshot 2019-04-22 at 13 39 19" src="https://user-images.githubusercontent.com/16776042/56500868-6d53e500-6504-11e9-950e-e567cc38fdd4.png">

Setting the text for Choice A and Choice B should make this work.

I've fixed this in dd32a42494c9a324135e8839007721bb471978ee so if left blank the text will match the placeholders in the editor

<img width="479" alt="Screenshot 2019-04-22 at 13 39 36" src="https://user-images.githubusercontent.com/16776042/56500904-95dbdf00-6504-11e9-91e8-99e66e50f82c.png">

**Comment by mschenatti** [comment]
Thanks a lot
