### ISSUE TITLE
[Request] Allow user to override language

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#150]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

The user should be able to change language from a menu

**Comment by RichardULZ** [comment]
@chrismaltby Any idea how hard / easy a language select would be? 
Helpful for testing and for people who dont want to keep changing the system language.

**Comment by chrismaltby** [comment]
This is in the latest dev builds now 👍
