### ISSUE TITLE
See where scripts have been used (like with variables)

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1501]
**Is your feature request related to a problem? Please describe.**
Often on big projects scripts may need to be replaced or you wonder if a script is actually in use, knowing it wasn't referenced anywhere would allow it to be deleted and keep big projects more manageable, rather than the current fear of introducing an issue.

**Describe the solution you'd like**
It'd be super helpful to be able to see where a script has been used like you can by clicking on a variable in the left hand menu, which is incredibly useful, this could be in a tab next to [ Script ], [ Script Uses] and should match up with [Variable Uses].

![Screenshot 2024-08-12 at 09 48 46](https://github.com/user-attachments/assets/bb7ea6bf-f149-4830-a7a2-f2f0966ca641)
![Screenshot 2024-08-12 at 09 48 42](https://github.com/user-attachments/assets/cfa3a8ea-7309-4bad-bbbf-3c7d2aa2b960)

**Describe alternatives you've considered**
If these aren't set up to be like tabs it could be at the bottom or collapsed at the top under description? (with an expand option).

**Additional context**

**Comment by chrismaltby** [comment]
Good idea, I've just added it today, added a few ways to get to it. You can either right click on the script list and select "View Script Uses" or click the "Script Uses" panel that will be at the bottom right of the sidebar

<img width="382" alt="Screenshot 2024-08-12 at 12 27 44" src="https://github.com/user-attachments/assets/04dfc85d-5317-4952-8842-be02976367de">
<img width="523" alt="Screenshot 2024-08-12 at 14 40 54" src="https://github.com/user-attachments/assets/d03b0bb7-620f-4281-9a60-2345796ce17e">

<img width="503" alt="Screenshot 2024-08-12 at 14 40 59" src="https://github.com/user-attachments/assets/3c58bf7c-2794-4679-a596-47c853236b79">

One thing to note is that it's not possible to see the panel AND the script editor onscreen at the same time. I purposefully did this as every time you modified the script while the panel was open it would recalculate the uses on every change. So if you left the panel open the sidebar would get quite slow, especially for large projects.

**Comment by mxashlynn** [comment]
Amazingly fast work!  Thanks much, Chris and Joel!
