### ISSUE TITLE
Statements like “If Variable False” will not show up in the Variable Uses page

### ISSUE THREAD

**Issue by KirbyKing186** [chrismaltby/gb-studio#1504]
**Describe the bug**
When placing an event like “If Variable Is True”, the chosen variable will show up in the project’s “Variable Uses” page. This is a relatively new feature that I love, however I found one big issue: statements like “If Variable False” will not show in that menu. Same goes with If Variable Compare with Value events, like “If (ShakeOFF ==3”.

**To Reproduce**
1. Place a “If Variable is False” event anywhere (For example, let’s use “ShakeOFF”)
2. On the left tabs go to the Variable page and find the aforementioned variable (find “ShakeOff”)
3. On Variable Uses, there should be no mention of it being used by the “If Variable is False” event.

It’s possible to repeat this with another event like “If Variable Compare with Value”, and it will also not show up (at least in my testing).

**Expected behavior**
I believe it is an oversight or bug that the “If Variable Is False” events do not show up in the variable uses. Using a “If Variable is True” event will show up just fine.

**Screenshots**
![IMG_2281](https://github.com/user-attachments/assets/c0be3c73-a8e2-4df9-95a9-c87135f757b3)
![IMG_2282](https://github.com/user-attachments/assets/e309a08b-fd68-460c-b9ec-2be11c63ade4)

**Platform (please complete the following information):**
 - OS: Windows 11
 - GB Studio 4.0.2 (latest as of now)

**Additional context**
The images above are from my game. “If ShakeOFF is False” events are used all over my game, like this custom script named “Knockback (Hurt Less X)”, but it only shows that it’s used in the scene “Options”.

**Comment by chrismaltby** [comment]
Hi @KirbyKing186 yeah we noticed this a few weeks back, a fix is in place in the develop branch which I'm hoping to release soon as part of 4.1.0 :-) I've just run through the steps you listed in my local version and can confirm the variable appears in the Variable Uses list now

**Comment by KirbyKing186** [comment]
Great!
