### ISSUE TITLE
4.1.0 reports as 4.0.2

### ISSUE THREAD

**Issue by kinostl** [chrismaltby/gb-studio#1507]
4.1.0 reports as 4.0.2

![image](https://github.com/user-attachments/assets/e6858f1b-2c76-4f41-b64d-39ef250d875f)

**Comment by pau-tomas** [comment]
See https://github.com/chrismaltby/gb-studio/issues/1490#issuecomment-2252235289 for an explanation

**Comment by chrismaltby** [comment]
Yeah I normally increment just before doing an official release but to avoid confusion I've set it to 4.1.0-beta in the develop builds now :-)
