### ISSUE TITLE
[Bug] TypeError: Cannot read property 'movementType' of undefined

### ISSUE THREAD

**Issue by KitF** [chrismaltby/gb-studio#151]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When building a project from 1.0.0 (and 1.1.0 RC1), I get an error while building that says "TypeError: Cannot read property 'movementType' of undefined"

Rolled back to 1.1.0 RC1 and the build is fine

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I think it has to do with importing my script that hides an actor to make it look like it's going under a bridge.
Here is a project with the scene in question:
https://www.dropbox.com/s/ggvpr51q0ry9ryx/test_case.zip?dl=0

* **What is the expected behavior?**
No error while building the project.

* **What is the motivation / use case for changing the behavior?**
Being able to run my project on RC2

* **Please tell us about your environment:**

  - Version: 1.1.0 RC2
  - Platform: [Windows]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Fixed in 83be72eb0e77674c56b8a8df7c4a5f1817d47cab. There was an issue introduced in rc2 where events setting the direction of the player would prevent compiling. Nice bridge script by the way! Have fun making FFXI
