### ISSUE TITLE
Small issue - translation not linked for "If" command and "None" collision group (EVENT_IF/FIELD_NONE ?)

### ISSUE THREAD

**Issue by ReptiIe** [chrismaltby/gb-studio#1510]
**Describe the bug**
It seems that `If` command is not linked properly. I double checked and yes current translation already have it covered.
My guess this is from `EVENT_IF`

Edit:
On this screen, I had notice another missing translation: missing word `None` in the Collision group of an actor.

**To Reproduce**
In whatever language, just go to events, choose a new event, control flow, and there you will see `If` instead of proper translation
(Screen below)

**Expected behavior**
Guess it should show proper translation for those terms.

**Screenshots**
![image](https://github.com/user-attachments/assets/87b8992b-5fd1-4562-a0c8-51d12d96aa51)

(1) Missing `If` translation in the event command (on the screen it is highlighted as gray) [`EVENT_IF` field?]
(2) Missing `None` in the collision group of an actor, on the screen it is chosen (pink color) [`FIELD_NONE` field perhaps? or this one is term for the "pop up"]

**Platform (please complete the following information):**
 - OS: W11
 - App version 4.0.2

**Additional context**
This is a small issue, just take a look in your free time to fix it.
Once it will be fixed, this issue can be closed.
Simple as that.

**Comment by chrismaltby** [comment]
Hi @ReptiIe You've fixed this one already I think :-) 
This is what I see on the develop builds
<img width="336" alt="Screenshot 2024-08-15 at 18 00 24" src="https://github.com/user-attachments/assets/c22dedf3-c7dc-4cd4-847e-ff43668d8f36">
but the change was made after 4.0.2 was released, so it should appear in the next release. Unless I'm missing something!

**Comment by ReptiIe** [comment]
@chrismaltby a yes, if the changes were after 4.0.2, that would make sens. Right.
How about that `None` (should be `Brak`) in the collision group.
Is that fixed as well? (it is on the screen)

**Comment by chrismaltby** [comment]
Yeah it's showing as Brak now too
<img width="474" alt="Screenshot 2024-08-21 at 21 35 29" src="https://github.com/user-attachments/assets/79028f22-0d27-4a67-bd14-ea0f2e78545e">

I just found some more hard coded text by the way "Pin To Screen", I've added this using the key `FIELD_PIN_TO_SCREEN`
<img width="337" alt="Screenshot 2024-08-21 at 21 37 05" src="https://github.com/user-attachments/assets/305fe6b2-84ab-4562-8630-db622a7398c6">

I've also added a bunch more fields, mostly relating to the Prefabs feature that I merged into the develop branch today, I'll try not to add too many more before the next release :-)

**Comment by ReptiIe** [comment]
For sure we will catch them all 😄 
OK I think we can close this topic, if something new get in the way I will let know.
