### ISSUE TITLE
Deleting a script to remove empty call script event

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1513]
**Is your feature request related to a problem? Please describe.**
Currently if you delete a script, the object, scene etc retains a blank call script event (see screenshots)

**Describe the solution you'd like**
If possible and not complicated, it'd be nice to remove these too

**Describe alternatives you've considered**
A list of instances of empty scripts so you can manually remove them, but this could also be gotten from the initial warning before deleting and carried out manually.

![Screenshot 2024-08-15 at 21 02 31](https://github.com/user-attachments/assets/03da659f-f127-4d85-9844-d41313d1a895)
![Screenshot 2024-08-15 at 21 02 49](https://github.com/user-attachments/assets/97b15b0c-92de-4779-91b7-fcc4b6d84fdd)

**Comment by maxoakland** [comment]
I don't think it should be deleted. If I did that, I wouldn't want it to delete that call script. Maybe a good compromise would be to automatically disable the call script

**Comment by joeledge** [comment]
I'm curious why you'd want it to stay there, as there would be empty script calls left referencing nothing across probably multiple actors and triggers that would require the extra work of hunting down and cleaning up.

**Comment by nielsderijk** [comment]
I agree with @maxoakland the event of calling a script should not be removed (not by default any way), even if the called script itself is removed. You don't want to end up in a situation where you deleted a script by mistake, and need to add all calls manually again.

If possible, I would introduce a dialog that asks if you want to remove all calls/references when you are about to delete a script. "No" should be the default answer.

**Comment by chrismaltby** [comment]
I've just pushed 2f510e3765ca1d2f611e381e93d80d8dec07e1cb to develop which added a "Delete Script and References" button to do this @joeledge 

<img width="315" alt="Screenshot 2024-08-21 at 20 00 22" src="https://github.com/user-attachments/assets/6ecc8051-24f0-4476-9169-71cf510a922c">

- "Delete Script" does the same as the current Delete button (though I fixed the issue where it was saying `||custom-event:||` in the title of the old call events)
- "Delete Script and References" will fully delete any Call Script events that referenced this script

**Comment by joeledge** [comment]
Awesome
