### ISSUE TITLE
Sound effect preview only plays after pressing the Play button twice

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1514]
**Describe the bug**
After changing the Effect Index number of a HammerFX sound effect, the Play button needs to be pressed twice to play the sound.

**To Reproduce**
1. Add a "Play Sound Effect" event and pick a sav file
2. Change the Index number
3. Press play
4. Press play again to actually hear the sound

**Expected behavior**
The sound effect plays immediately after pressing the Play button

**Screenshots**
<img width="249" alt="Screenshot 2024-08-15 at 23 00 23" src="https://github.com/user-attachments/assets/0abe8261-5142-4da9-8592-9b22b98b0a24">

**Platform (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - All versions of GB Studio 4

**Comment by maxoakland** [comment]
This happens to me too on Mac

**Comment by chrismaltby** [comment]
I managed to reproduce this issue too and have added a fix in 5e9522982cd1779b1f7b6123568d21f44c2d9488 which will be included in the next release. Thanks for spotting this

**Comment by chrismaltby** [comment]
This issue was fixed in the 4.1.0 release :-)
