### ISSUE TITLE
Split Project Beta: Move cosmetic settings to `user_settings.gbsres` file

### ISSUE THREAD

**Issue by Deab22** [chrismaltby/gb-studio#1518]
Having the `user_settings.gbsres` file for settings that don't impact the project itself is great, especially since using `gitignore` lets them get auto-generated for each dev, but i feel like some more settings should be brought over to it, specifically:

#### `navigatorSplitSizes`, `showNavigator`

These get moved around a lot during development, and are purely based on personal preference, a no-brainer

#### `showCollisions`, `showConnections`, `previewAsMono`

Not changed as often, but still purely cosmetic, so safe to move to a separate file

#### `showCollisionSlopeTiles`, `showCollisionExtraTiles`

A bit more difficult, these would usually be the same between collaborators because of the project itself, but also very easy to toggle yourself, so it doesn't really need to be shared between collaborators

#### `favouriteEvents`

Some projects might use these to mark specific custom functions, but i believe it's purely personal preference for most projects

#### Debugger Settings

This one is tricky, since sharing debugger settings like watched variables might be useful for teams, but having them automatically committed would overwrite the other dev's breakpoints and other settings.
I personally think this one should either be in `user_settings.gbsres`, but i'd like to discuss this in the comments if you disagree.

**Comment by chrismaltby** [comment]
Agreed :-) I should have done a full audit of settings keys it made sense to put in user_settings, it was mainly the scroll and zoom ones that bothered me whenever I needed to edit the inbuilt sample projects but that's a good point on the others too.

I've pushed an update with this change to the develop branch to be included in the next release. I've also tidied up the code that handled this so now there's just a single array of user setting keys here https://github.com/chrismaltby/gb-studio/blob/7fe98ea30b029653de5172f2a816e83448c06c39/src/shared/lib/resources/save.ts#L45-L66 that can be updated a bit easier as needed.
