### ISSUE TITLE
Variable changes when changing "Engine Field" field in "Store Engine Field in Variable" event

### ISSUE THREAD

**Issue by sharkeylaser** [chrismaltby/gb-studio#1521]
**Describe the bug**
When you use the "Store Engine Field in Variable" event, the variable selected reverts to "Local 0" any time you change the field.

**To Reproduce**
1. Add the "Store Engine Field in Variable" event to your project.
2. Set the "Engine Field" field to something.
3. Set the variable to something other than "Local 0".
4. Set the "Engine Field" field to something else.
5. The variable field reverts to "Local 0".

**Expected behavior**
It should not revert your choice of variable when you change the engine field.

**Platform (please complete the following information):**
 - OS: Arch Linux
 - All versions of GB Studio 4

**Comment by chrismaltby** [comment]
This was actually intentional, but in testing this out again I think you're right that it should keep the chosen variable. I've pushed an update to develop and this will be included in the next release

**Comment by sharkeylaser** [comment]
Awesome, thank you so much!
