### ISSUE TITLE
Setting background palettes to "Restore Default" works incorrectly when placed inside a custom script

### ISSUE THREAD

**Issue by KirbyKing186** [chrismaltby/gb-studio#1545]
**Describe the bug**
Setting background palettes to "Restore Default" works incorrectly when placed inside a custom script. Note that there is no nesting going on in the script, and this is the only custom script in the test project I worked on. The `.zip` file for that project is linked below.

**To Reproduce**
1. Make a project that includes many scenes that have differing background palettes.
2. Make a custom script, and put a singular event inside: "Set Background Palettes". Set all the palettes (1-8) to "Restore Default".
![image](https://github.com/user-attachments/assets/981bdac8-00aa-4c48-b2bb-504cb2621a32)
4. Place the custom script in each scene, and place the script before the Fade In.
5. Compile the game, and see that the palettes were incorrectly restored.

**Expected behavior**

**Screenshots**
*Image 1*
![image](https://github.com/user-attachments/assets/f1afa6f2-1b61-4072-9463-6916ac2e5a02)
Photo of all three scenes used in the test. Each scene has only two events on the OnInit, which are to call the custom script that has "Set Background Palettes, restore default to all eight", and to fade in.

*Image 2*
![image](https://github.com/user-attachments/assets/4305d1f8-6038-4f12-8dc6-ed9b60bfd698)
Photo of Scene 2 after the custom script is called. Although the background palettes were set to restore the default palettes, they are instead changed to Scene 1's background palettes.

*Image 3*
![image](https://github.com/user-attachments/assets/d1e61bbe-bb29-4b67-a40e-bc9297f9a0f3)
Photo of Scene 3 after the custom script is called. Like with Scene 2, it changed to Scene 1's background palettes.

**Platform (please complete the following information):**
 - OS: Windows 11
 - GB Studio 4.0.2

**Additional context**
Side note, there is no "Restore Default" for sprite palettes. Potentially an oversight?
[Restore Default BG Test.zip](https://github.com/user-attachments/files/16800325/Restore.Default.BG.Test.zip)

**Comment by chrismaltby** [comment]
Hi @KirbyKing186 Thanks for providing that sample project, it was very useful. I've managed to fix this and have also implemented "Restore Default" as an option for sprite palettes. The fix + update will be included in 4.1.0 when it releases

**Comment by KirbyKing186** [comment]
Thanks!
