### ISSUE TITLE
Build time doesn't show seconds if seconds are 0

### ISSUE THREAD

**Issue by sharkeylaser** [chrismaltby/gb-studio#1548]
**Describe the bug**
If you have over a minute in build time, but the seconds are 0, it leaves an awkward blank, resulting in something that looks like "2m s".

**To Reproduce**
1. Compile project.
2. Hope it ends with 0 seconds.
3. Notice output.

**Expected behavior**
I would think either it should show "2m 0s" or just "2m" without the additional " s".

**Screenshots**
![image](https://github.com/user-attachments/assets/9dd71605-a046-46cd-8c4b-14e52470e7cd)

**Platform (please complete the following information):**
 - OS: Arch Linux
 - App version 4.1.0 beta 4

**Comment by chrismaltby** [comment]
How embarrassing! That's why I should write tests no matter how simple the function seems 😅 It was a two character fix, I've made the change and written a number of tests to cover this here https://github.com/chrismaltby/gb-studio/commit/93aff097016d51083a66c037547b66b2e2c48b71

**Comment by sharkeylaser** [comment]
Such a large oversight! /s

I'm glad it was a simple fix! Thanks for taking a look into it!
