### ISSUE TITLE
Global Variable in Evaluate Expression Event doesn't show in Variable Uses

### ISSUE THREAD

**Issue by lkcampbell** [chrismaltby/gb-studio#1557]
**Describe the bug**
When you check where a global variable is used in your project, by clicking on the variable and looking at the Variable Uses list, you won't see any variable use from the free text area part of the Evaluate Expression Event.

**To Reproduce**
1. Create a global variable `foo`.
2. Add a Evaluate Expression Event to an On Init part of a `test` scene.
3. Set `$Local0` variable to expression `$foo + 1`.

**Observed behavior**
The Variable Uses list says "Variable hasn't been used in project".

**Expected behavior**
The `test` scene should be listed in the Variable Uses list.

**Platform (please complete the following information):**
 - OS: macOS 14.6.1 (23G93)
 - App version 4.0.2

**Additional context**
This bug also applies to any text in a `Display Dialogue` event and, potentially, any other event where the variable reference can be entered in a free text area. I just didn't want to file numerous bugs for what is *probably* a similar problem in each case.

**Comment by lkcampbell** [comment]
It looks like the `If Math Expression` event part of this bug has been fixed in v4.1, so I am going to edit the Additional context section above and remove that part.

**Comment by lkcampbell** [comment]
The bug I submitted has been fixed in version v4.1.1. I can file the `Display Dialogue` bug I mentioned in **Additional context** separately. Closing as fixed, thanks.

**Comment by chrismaltby** [comment]
Is the Display Dialogue bug still happening for you? That should have been fixed with 4.1.1 also :-)

**Comment by lkcampbell** [comment]
Yeah, here is my setup:
![Screenshot 2024-09-04 at 7 15 43 AM](https://github.com/user-attachments/assets/10c924fb-a144-4b33-9aa2-6f2b8cf36901)

 and my result:
![Screenshot 2024-09-04 at 7 15 55 AM](https://github.com/user-attachments/assets/ada11b0a-dbb1-48d3-85e6-443d80926dc7)

**Comment by lkcampbell** [comment]
I went ahead and filed the Dialog Box Event part of this issue as a separate issue because I still see it in v4.1.3:
https://github.com/chrismaltby/gb-studio/issues/1628
