### ISSUE TITLE
Bug: Changes/commits being lost

### ISSUE THREAD

**Issue by joeledge** [chrismaltby/gb-studio#1562]
**Describe the bug**
I've noticed since using 4.1.0 beta and files being split into individual rather than on big project file, that some changes I've made, saved and committed have been lost. Previously some drawn on collisions for levels were gone, I assume this was my mistake and recreated. Just now I noticed GBVM tile swapping code I added three days ago was gone, as were the some dialogue changes I made. I've attached the commit as a PDF where this then went missing afterwards.

I'm not sure how often this has occurred as usually fire through a separate commit for each change or small batch of changes, I'm not a GitHub expert so don't really stray from – git add ., git commit -m "blah", git push.

**To Reproduce**
I'm not sure how to reproduce yet, but it has occurred multiple times.
A theory from Rulz in the GBS Discord is that it's because I often have two versions of GB Studio open. So it _could_ be that which is causing the problem.

Because it's not possible to open two custom scripts and I often need to be able to compare two when making a new one, troubleshooting or editing, I have a duplicate of the same version of the GBStudio App (MacOS), open the project file and avoid saving this duplicate, instead just using it to look at and occasionally copy and paste.

**Expected behaviour**
Changes not to be missing.

**Screenshots**
PDF attached of changes that were missing but previously committed (and hadn't been deleted manually).
[Comparing bcd3f013c685c03576dc0bcc7a150de250288ca3...9bc75602d0f4500dd47f3b16e317bad5736d30e5.pdf](https://github.com/user-attachments/files/16847134/Comparing.bcd3f013c685c03576dc0bcc7a150de250288ca3.9bc75602d0f4500dd47f3b16e317bad5736d30e5.pdf)

**Platform (please complete the following information):**
 - OS: 14.5 (23F79)
 - App version 4.1.0

**Additional context**
If it is caused by having multiple versions over, perhaps either 'open in read only mode' or the ability to open up another window with custom scripts in it, or break out to a modal, although understand this is a big UI change to how GBS works.

**Comment by chrismaltby** [comment]
Hi @joeledge hmm, yeah it's possible that you're accidentally saving the older version of the project in the second window... If you save with the one version you're modifying it will bring the new changes back.

I had a go at allowing break out windows but I think I don't think it's going to be possible without a lot of changes, it seemed promising at first but I think lots of the UI (not just my code but third party components I'm using) expects to be run in a single window (see here where the modal window's select options are unstyled, and the options are loading, styled correctly, but positioned weirdly in the main window)
<img width="1301" alt="Screenshot 2024-09-03 at 12 40 56" src="https://github.com/user-attachments/assets/2521b798-8b3e-40df-a648-5d81d85a9a2a">

Potentially a read only mode might be more achievable, it could be hidden behind a keyboard shortcut maybe (hold shift while opening file menu?) and some colour changes made to the window style to make it clear that it's the read only window.

**Comment by joeledge** [comment]
Okay I don't think it's caused by having two windows open now so sorry for any time wasted. Rather something strange that was happening with my GIT folder on MacOS as I could reproduce if I –

1. Download a previous commit of the project, open that in GBS 4.1.0 from my downloads folder, all changes to date made intact
2. If I close this, copy the files into the GIT folder (blank with all the other content deleted), when I open the project from the GIT folder, despite having the same files, none of the changes show

So the problem was when within the GIT folder, it wouldn't show new changes, the closest analogy I have, not understanding GIT really is temporary/cached files somewhere? A fresh clone didn't work but showing the hidden .git folder and deleting it meant the latest changes all showed up.

If I had to guess this is down to my lack misunderstanding of how Git works, perhaps using every version of the betas complicated things somehow, but either way that issue seems to have been fixed.

In terms of a solution for comparing scripts, I can continue the way I worked previously as I don't think I hit save and if I do, it's user error, but a possible solution/nice to have for a future feature could be right clicking the script and having an option to 'open in new panel', 'open in comparison panel'? So they'd stack together side by side. Whether you want more than the two side panels or it causes more complications I'm not sure.

![Screenshot 2024-09-03 at 13 58 26](https://github.com/user-attachments/assets/19d28503-d4c8-4c34-881b-fa4239c399fe)

**Comment by joeledge** [comment]
I'll close this issue as I don't think it seems to have been some sort of issue with the hidden git folder locally and something going wrong in it, and will open a new one if I have reason to believe it's something else.

**Comment by maxoakland** [comment]
> Hi @joeledge hmm, yeah it's possible that you're accidentally saving the older version of the project in the second window... If you save with the one version you're modifying it will bring the new changes back.
> 
> I had a go at allowing break out windows but I think I don't think it's going to be possible without a lot of changes, it seemed promising at first but I think lots of the UI (not just my code but third party components I'm using) expects to be run in a single window (see here where the modal window's select options are unstyled, and the options are loading, styled correctly, but positioned weirdly in the main window) <img alt="Screenshot 2024-09-03 at 12 40 56" width="1301" src="https://private-user-images.githubusercontent.com/16776042/363967602-2521b798-8b3e-40df-a648-5d81d85a9a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MDU4MTcsIm5iZiI6MTcyNTQwNTUxNywicGF0aCI6Ii8xNjc3NjA0Mi8zNjM5Njc2MDItMjUyMWI3OTgtOGIzZS00MGRmLWE2NDgtNWQ4MWQ4NWE5YTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDIzMTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYmRhZTc0OThiYzgyZmQ3MmYzNjdlNzM4MTU3ZTZmYTdkZDA0ZWVjNzk4OGExMzI1NGFiNjYyYzA1MmM2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E6MlwaLsg5tF0yzM6y_oNTfvomk3-zioHPzxuvyYGb0">
> 
> Potentially a read only mode might be more achievable, it could be hidden behind a keyboard shortcut maybe (hold shift while opening file menu?) and some colour changes made to the window style to make it clear that it's the read only window.

Breakout Windows would be really cool. Hopefully someday!
