### ISSUE TITLE
Sound Effect Referred to As Song

### ISSUE THREAD

**Issue by maxoakland** [chrismaltby/gb-studio#1564]
**Describe the bug**
If you right click on a sound effect on the Sound Effects page, it will say "Delete Song" Instead of "Delete Sound Effect"
<img width="407" alt="Screenshot 2024-09-03 at 4 26 55 PM" src="https://github.com/user-attachments/assets/dae4837a-943d-4329-aaa5-48c7ca8a9deb">

**Comment by chrismaltby** [comment]
Hi @maxoakland this now fixed in 4.1.1 :-)
