### ISSUE TITLE
Project migration dialog appears under main window on Linux

### ISSUE THREAD

**Issue by pcmdx** [chrismaltby/gb-studio#1569]
**Describe the bug**
When loading a pre-4.1 project the dialog "GB Studio Project Requires Migrating" appears under the main window making it look like it's loading but nothing is happening (and waits forever).

**To Reproduce**
1. Load GB Studio 4.1 or above
2. Load a pre-4.1 project
3. Move the main window to see the dialog behind

**Expected behavior**
Dialog appears on top

**Screenshots**
![image](https://github.com/user-attachments/assets/3209c52b-ff3a-49ca-95fa-d22582f24a56)

**Platform (please complete the following information):**
 - OS: Linux Mint 21.3 Cinnamon
 - App version: 4.1.1

**Additional context**

**Comment by chrismaltby** [comment]
I've confirmed on a Linux VM that this also happens for me. I've pushed a fix here 2ffc0cbf6e8a7b6cb1689a4b4b905493a80d3ac6 that will be included in the next release

**Comment by pcmdx** [comment]
Legend! Thanks @chrismaltby.
