### ISSUE TITLE
4.1.2 EPREM error for any 3.2 project and above

### ISSUE THREAD

**Issue by MACK-GB** [chrismaltby/gb-studio#1578]
**Describe the bug**
GBS 4.1.2 will show the following error message (see screenshot below) when attempting to open any project file that contains a "plugin" folder. In my tests, this affects any project from GBS 3.2 and above.
When right clicking on the project file and selecting GBS 4.1.2 to open it, nothing happens (note that this has been a separate, continual problem for me with any version of GBS 4). It only shows signs of opening (aka, displaying the error message seen below) when opening through the app's startup UI.

**To Reproduce**
1. Go to 'Recent' on GBS 4.1.2's startup menu
2. Click on any project that includes a plugin folder
3. See error

**Expected behavior**
It was expected that the project would load without an error message that is preventing access to the project in-engine.

**Screenshots**
<img width="620" alt="Screenshot 2024-09-11 at 7 14 04 AM" src="https://github.com/user-attachments/assets/492190f7-9c36-4b12-bf61-d2de6a9da84c">

**Platform (please complete the following information):**
 - OS: macOS 14.6.1 (23G93)  [also happened on Ventura]
 - App version [4.1.2]

**Additional context**
- MacBook M1 Pro
- I have checked 'System Settings' > 'Privacy & Security' and unfortunately could not find any sign of a permissions issue.
- To my knowledge, I do not have any antivirus software installed or running on this device.
- I have had trouble with reopening projects from any version of GBS 4 so far, but sometimes was able to get it to work and was able to skate by with keeping those projects open. I will write a separate report for that, but note that 4.1.2 is the only version to show this EPREM error message.

**Comment by chrismaltby** [comment]
Hi @MACK-GB very odd... Does this happen for all project containing plugins folders? Would you be able to provide a small example project where you see the issue?

One thing I'm wondering, do you use iCloud?

It shouldn't be an issue as I'm also storing all my projects in iCloud but wondering if the permissions there aren't right, it could rule out some options if you tried loading the same project from a folder that isn't included in iCloud.

You could try just adding the project directly to the root of you home directory `/Users/Eric/Sample Project v3.2.0` for example, if that folder did work then maybe it's something about iCloud permissions, if it still doesn't work there's something else to investigate which I could look at if you provide that project as a zip.

**Comment by chrismaltby** [comment]
it might also be worth confirming what you see under the "Files and Folders" section of "Privacy & Security" in System Preferences (I know you say you've already looked so I apologise if you've already done this)
<img width="789" alt="Screenshot 2024-09-11 at 14 07 17" src="https://github.com/user-attachments/assets/bcb5bb4d-b250-489d-88c1-0b53fe0fb45b">
while doing that I just found out why I can't load projects from my Downloads folder 😅

**Comment by MACK-GB** [comment]
That worked!!

Thank you so much, the issue was indeed that "Desktop Folder" wasn't toggled! Didn't know that was there; I was only looking for GB Studio mentioned on the main options page. Not only did it fixed the EPERM error, but it seems like it eliminated my other prompt-less problem of not being able to open any projects in GBS 4! This is a life saver, thank you again.
