### ISSUE TITLE
Missing Background Error Not Showing Up

### ISSUE THREAD

**Issue by thejohnston7** [chrismaltby/gb-studio#1584]
**Describe the bug**
If a scene has no background assigned to it, the error won't show up in the build log.

**To Reproduce**
1. Create a new scene with any background
2. Save your project and close GB Studio
3. Move or delete the background file that your new scene uses
4. Reopen your project and try to run or export

**Expected behavior**
The build will be automatically canceled with no error given.

**Screenshots**
<img width="210" alt="Screenshot 2024-09-15 at 6 56 25 PM" src="https://github.com/user-attachments/assets/001209b7-d060-4429-b0b8-885be02abb45">

**Platform:**
 - Tested on macOS 14.6.1 and Windows 10
 - App version 4.1.2

**Additional context**
In the previous version (4.1.1), the error would be shown in the build log.

**Comment by chrismaltby** [comment]
Thanks @thejohnston7 this error will now appear again as expected in 4.1.3 released today https://chrismaltby.itch.io/gb-studio
