### ISSUE TITLE
Version 4.1.3 won't run or build games

### ISSUE THREAD

**Issue by DecaTilde** [chrismaltby/gb-studio#1594]
I tried to run a WIP game, but it always cancels the build in the debugger.

1. Go to Run
2. Click on Run
3. Scroll down to Debugger
4. Error: EPERM: operation not permitted, unlink 'C:\Users\xxx\AppData\Local\Temp\_gbstools\gbdk\bin\sdcc.exe'

I wait about a minute for the ROM to run, but it gives me an error message in the debugger.

![Screenshot 2024-09-23 215813](https://github.com/user-attachments/assets/2297560e-9dea-41ac-b8ef-69f2c147ae0c)

Platform:
 - OS: Windows 11 23H2
 - App version 4.1.3

In the next update for GB Studio, please fix this.

**Comment by DecaTilde** [comment]
I had to change the folder, and the ROM ran.

**Comment by smfhacking** [comment]
I have a problem exporting

also
