### ISSUE TITLE
[Request] Dark Theme for Windows

### ISSUE THREAD

**Issue by JasonB32** [chrismaltby/gb-studio#16]
That would be awesome. I seen someone paste a photo of their Mac version and it looked like they already had a dark theme on it, please don't forget us Windows users :D

**Comment by delacannon** [comment]
In the Mac Version only toggles to dark mode when you have enabled "use dark menu bar and dock" in the general tab of the system preferences.

In this [fork](https://github.com/delacannon/gb-studio) I just crated an explicit button to swap between themes directly from the studio bar.

![ezgif-3-29155e0562cd](https://user-images.githubusercontent.com/12370858/56614996-818a0600-661a-11e9-80e7-eb944ed9c62c.gif)

**Comment by chrismaltby** [comment]
Implemented this in a53bb606eca01ef95d0793077b596ce47c133db4 and c2926d7fdd289c3ce61ec36e53446d7212ed6227.

Next release will allow setting the dark theme on Windows and Linux from the view menu.

<img width="1087" alt="Screen Shot 2019-04-29 at 2 35 05 PM" src="https://user-images.githubusercontent.com/16776042/56899788-40677b00-6a8c-11e9-80d5-66dc0c74efd7.png">

**Comment by JasonB32** [comment]
I'm shocked, I can't believe how fast you are at implementing these requests, where as if it was a big company it would take 6 months to release it.
