### ISSUE TITLE
Allow the use of a variable (and not only a fixed value) in the Play Sound Effect event

### ISSUE THREAD

**Issue by nielsderijk** [chrismaltby/gb-studio#1604]
**Is your feature request related to a problem? Please describe.**
I am creating a game in which the sound effect's tone/pitch goes up depending on the number of moves you make (a count stored in a variable). Preferably, I want to use that variable to call the right Hammer sound effect.

**Describe the solution you'd like**
Instead of using a static value, I would like to use a variable in the Effect IDX field.

**Describe alternatives you've considered**
I am now using a switch (if else statements) and attached a "Play Sound Effect" event to each of the 20 steps the tone can be in. This feels less elegant and performant than just calling the right IDX with 1 event.

**Additional context**
<img width="605" alt="Screenshot 2024-10-11 at 15 29 58" src="https://github.com/user-attachments/assets/7dac1603-04f6-4ded-8ccf-7ca24f30ad05">

**Comment by chrismaltby** [comment]
Hi @nielsderijk so while it would be possible to do this I think the generated code would end up being pretty much identical to what you're doing already.

If you look at the generated GBVM for playing effect 0, 1 and 2 on the same file

```asm
; Effect 0
VM_SFX_PLAY ___bank_sound_gbstudio_sfx_sav_00, _sound_gbstudio_sfx_sav_00, ___mute_mask_sound_gbstudio_sfx_sav_00, .SFX_PRIORITY_NORMAL
```

```asm
; Effect 1
VM_SFX_PLAY ___bank_sound_gbstudio_sfx_sav_01, _sound_gbstudio_sfx_sav_01, ___mute_mask_sound_gbstudio_sfx_sav_01, .SFX_PRIORITY_NORMAL
```

```asm
; Effect 2
VM_SFX_PLAY ___bank_sound_gbstudio_sfx_sav_02, _sound_gbstudio_sfx_sav_02, ___mute_mask_sound_gbstudio_sfx_sav_02, .SFX_PRIORITY_NORMAL
```

See how the only difference is in the symbols, meaning we'd probably need to do something like:
- if you pass in a variable value as the index
- figure out how many effects are in the file
- then generate a big switch that takes the variable and plays the right effect based on the value

which would in practice be identical to what it sounds like you're doing already. It would be very easy to not realise that using a variable here is increasing the code size substantially too so you could always pass in a variable index, and not be using a call to a custom script, so every sound effect could potentially have 30x generated GBVM than was needed.

I suppose the event could make it very explict that the code generated could be quite large when you pass in a variable index but I try to avoid things like that to make it easier for people new to the app.

Maybe this is a good idea for someone to make an advanced sfx plugin instead?

**Comment by nielsderijk** [comment]
@chrismaltby That's a pretty solid explanation on why it's probably better to keep it this way. Fully agree! :-)
Thanks for taking time. I will close the request.

**Comment by nielsderijk** [comment]
Will complicate the use of SFX event, won't result in more compact or efficent code
