### ISSUE TITLE
[Bug] Script review page breaks editor when using new multi page text.

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#161]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Open any project, try the script review tab, 
If it's working, go to an actor, and use + on a text box to add more dialogue,
Try to access the script review page.
The editor will become blank and you will have to close and reopen your project.

* **What is the expected behavior?**
Show the script review page as normal, with support for these cool multi page text boxes.

* **Please tell us about your environment:**

  - Version: 1.1.0 rc2
  - Platform: [Windows]

![ScriptReview](https://user-images.githubusercontent.com/34431457/57694521-09a27f00-76a0-11e9-8bbc-63b3a04981e1.gif)

**Comment by chrismaltby** [comment]
This should now be fixed as of a208a83feac16057eaa19dada3f2accedc0f7474
