### ISSUE TITLE
In “Set Animation Frame”, the frame value cannot go above 25, but the event supports higher values.

### ISSUE THREAD

**Issue by KirbyKing186** [chrismaltby/gb-studio#1618]
**Describe the bug**
On an actor who’s animarion state has more than 25 frames, attempt to set the

**To Reproduce**
1. Add an actor to a sample project, or use the player.
2. Add a “Set Animation Frame” event, and select an actor.
3. Try and add a value higher than 25.
4. See that it resets to 25.

**Expected behavior**
This event supports values higher than 25, but you will need to click “+” in the value box, and add the desired value. For instance, to set the frame to 60, 25 + 35 works great, but trying to add 60 will just reset to 25.

**Platform (please complete the following information):**
 - OS: [Windows 11]
 - App version [4.1.3]

**Comment by chrismaltby** [comment]
Very strange, I wonder if I had a reason for setting that limit at some point, definitely doesn't seem needed now so happy to remove :-) thanks for spotting. This is fixed now in 1810fcb89abebbf7628e40a148e24eb1a361d88a and will be included in the next release
