### ISSUE TITLE
Random Rotation (Direction) doesn't seem to work

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#162]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Setting an actor to Random Rotation doesn't seem to be working. (Note: This is still documented as Random DIrection.)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Add an Actor Sprite to a Scene and set it to Random Rotation.

* **What is the expected behavior?**

The Sprite randomly rotates based on the set Speed.

* **What is the motivation / use case for changing the behavior?**

For Sprites to look around.

* **Please tell us about your environment:**

  - Version: 1.0.0 (Downloaded May 9)
  - Platform: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Looks like they broke around the time the rendering was rewritten to allow animated sprites, they were changing direction but you just couldn't see it :-D fixed in 26eaeed103892daee5c2413f2002dd6931b2a744
