### ISSUE TITLE
[Request] Add a "Display Random Text" option

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#163]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

Strings (Display Text) are hard-coded at this point.

* **What is the motivation / use case for changing the behavior?**

It would be great to be able to have a "Display Random Text" option where an array of strings were chosen from to display.

**Comment by thomas-alrek** [comment]
You can already implement this using the provided contructs available in 1.1 rc builds.

You could e.g set a Variable to a Random number in a range, and then just use If Variable event to display different strings based on what number you got

**Comment by timsamoff** [comment]
I saw the Random number feature -- seems a bit convoluted for this particular feature. But I understand how it works. Thanks.

**Comment by thomas-alrek** [comment]
I personally find it more important to have "generic" methods like that, so that it can be used for multiple use cases, instead of one specific case.

**Comment by timsamoff** [comment]
Sure. Makes sense.

At some point, though, the "No knowledge required," heading on the website may have to be reevaluated due to implementations that are far more like computer programming than drag-and-drop.
