### ISSUE TITLE
Screen Glitch with Instant Fade Transition

### ISSUE THREAD

**Issue by kill99999-dev** [chrismaltby/gb-studio#1630]
**Description:**
When using the instant fade transition in GBStudio, the screen glitches and does not display correctly. This issue occurs consistently regardless of the project size or number of scenes. The bug has been observed across all versions of 4.x.

**Steps to Reproduce:**
1. Create or open a project in GBStudio (version 4.x).
2. Add at least 2 scenes to the project.
3. Set up a scene transition with the "instant" fade option.
4. Execute the transition in-game.
5. Observe the screen glitch.

**Expected Behavior:**
The screen should transition instantly without any graphical glitches.

**Observed Behavior:**
The screen shows graphical glitches and does not transition correctly.

**Affected Versions:**
- GBStudio 4.x (all versions tested so far)

**Additional Context:**
This issue appears consistently across projects of all sizes, with no minimum number of scenes required to trigger the glitch.

**Comment by chunkysteveo** [comment]
That's how the GB hardware works - the fade is needed to hide the loading of the scene tiles into RAM, otherwise you see glitches. You can get an 'instant' effect only in V4 onwards if you use the common tileset functionality. 

It's in the documentation - https://www.gbstudio.dev/docs/project-editor/scenes#common-tilesets

**Comment by chrismaltby** [comment]
Closing as @chunkysteveo says unfortunately this is just how the hardware works and the common tilesets feature was added as way to allow instant transitions without seeing the tile loading
