### ISSUE TITLE
Dragging a sprite with the Collisions tool selected draws collisions

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#164]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Collisions are drawn if the Collisions tool is selected and a sprite is selected with the tool.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Select the Collisions tool and then drag a sprite. A Collision will be drawn.

* **What is the expected behavior?**

Either (1) the tool switches to the Select tool when a sprite is clicked or (2) the sprite is unselectable until the Select tool is chosen. (Preference is option 1.)

* **What is the motivation / use case for changing the behavior?**

Editing efficiency.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Good point, this is now fixed in d675a1f667748dec59db434fe7e7974579567d0d
