### ISSUE TITLE
[Request] Add a Hotkey for the "Run" function

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#165]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

Must click the "Run" button to compile/run the emulator.

* **What is the expected behavior?**

Use Ctrl+P (Win)/Cmd+P (Mac) to trigger Run function.

* **What is the motivation / use case for changing the behavior?**

Editor efficiency.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
This has been present since the first public release as Ctrl/Cmd + B and is listed in the documentation  https://www.gbstudio.dev/docs/keyboard-shortcuts/ also the shortcut is listed against the menu item under the Game menu. You can also export the ROM using Ctrl/Cmd + Shift + B

**Comment by timsamoff** [comment]
Thank you. Sorry -- maybe the bug report should be for a hover element on the Run button then (the tools have them).
