### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by PixelDud** [chrismaltby/gb-studio#169]
Hello, I have created the following script:
![Screen Shot 2019-05-14 at 6 01 09 PM](https://user-images.githubusercontent.com/45052326/57738679-1ad69600-7676-11e9-943e-2d6fe82f74ee.png)
But it doesn't work as it is supposed to, here's the file for you to look at.
[Murder Mansion.zip](https://github.com/chrismaltby/gb-studio/files/3180450/Murder.Mansion.zip)
I'm on a 64-bit Mac running the Development version of GB Studio.

**Comment by KitF** [comment]
Are you using BGScript? Right now I don't think GBStudio supports using input scripts this way.

**Comment by AsherGomez** [comment]
I'm not sure how to use BG Script...

**Comment by thomas-alrek** [comment]
Oh yeah, my bad, I thought you where doing this inside an Attach To Input Script. This won't work standalone, but if you register this script as an Knout Script I think it should work

**Comment by chrismaltby** [comment]
Hi Asher, I had a look at your project, unfortunately what it looks like you're trying to do isn't yet possible.
Your "If joypad input pressed" event only fires once as the scene loads (so it's currently checking was the player pressing a direction button exactly when the scene loaded). There is currently no way to run a script in the background to check if a direction is being pressed to switch back to an idle animation in the official release. There's an experimental release by RichardULZ that has this support but I'm not sure yet if this implementation will become part of the main project.

**Comment by AsherGomez** [comment]
Oh, ok.

**Comment by AsherGomez** [comment]
@thomas-alrek How do I use Knout Script?
