### ISSUE TITLE
[Request] Zoom in/out using CTRL-Middle Mouse Scroll in Game World

### ISSUE THREAD

**Issue by JasonB32** [chrismaltby/gb-studio#17]
It would make it so much easier to navigate, then constantly using the left/right up/down scroll bars.

**Comment by JasonB32** [comment]
Also when you zoom in currently you can't target on a particular scene, if your zoomed out 200% then have a scene in the middle of the screen then try to zoom in using CTRL+ it doesn't zoom in on that location.

**Comment by chrismaltby** [comment]
Zoom in/out with ctrl+middle mouse focusing on target is now part of the 1.1.0 release :-)

**Comment by JasonB32** [comment]
Thank you so much Chris. AMAZING v1.1.0 UPDATE!!!!
