### ISSUE TITLE
Web-built index.html file should contain a <title> tag

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#170]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

Building for Web outputs an index.html file that doesn't contain a <title> tag within the <head> section.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Build for Web.

* **What is the expected behavior?**

That the <title> tag wouldbe included in the HTML code.

Preferred: A method of creating a human-readable name to be injected into the tag.

* **What is the motivation / use case for changing the behavior?**

This information shows up in the Web browser's tab.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chrismaltby** [comment]
Good idea, I've added this and also a meta author tag using the project name/author values in commit 6f81541f485fd16eeed5846db456f9a9bf2d8382
