### ISSUE TITLE
[Crazy Feature] Conditional to select Scene based on platform

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#171]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [X] **(Crazy)** feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Feature.

* **What is the current behavior?**

Game starts as intended.

* **What is the expected behavior?**

I know that this is probably a pie-in-the-sky idea, but it would be amazing to be able to create a conditional that would select a Scene branch based on what platform the game is being played on. For instance, if the game was a ROM, it would choose "Title_ROM"; if Desktop Web, it would go to "Title_Web"; and if Mobile Web, it would go to "Title_Mobile." (Names in quotes are just made up names for Scene nodes.)

* **What is the motivation / use case for changing the behavior?**

The use cases for each platform are distinct (e.g., D-Pad, A, B for ROM/Mobile Web and Keyboard for Desktop Web).

I know I could just make a branch of my project and develop one for ROM/Mobile and one for Desktop Web, but it would be great to be able to handle this within one project.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by thomas-alrek** [comment]
I think this is a bit out of scope for GB Studio, as it focuses on being cross platform

**Comment by timsamoff** [comment]
I figured it might be. Although emulator, web, mobile web already makes it cross-platform with different user experiences. Thanks for responding, though.
