### ISSUE TITLE
MOD file tempo commands (Fxx) not interpreted correctly

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#176]
> @RichardULZ and @WAUthethird: I have composed some music that is working perfectly now, EXCEPT that none of the tempo data is saved in the file. Is this possible? Or am I stuck at 125 BPM?

Sorry! Just figured out the Fxx commands!

_Originally posted by @timsamoff in https://github.com/chrismaltby/gb-studio/issues/83#issuecomment-493292900_

**Comment by timsamoff** [comment]
To elaborate: Set some commands in your MOD file to F03 (speed) and F80 (BPM). The music will play at a different speed in the tracker than in the game. The Fxx commands do seem to be working to some extent, just not properly...

Likewise, I have found that once a tempo is set with the first song, the temp can't be changed when a new song begins with new tempo settings.

**Comment by RichardULZ** [comment]
@timsamoff there are a ton of issue threads open now, and i feel this is an issue related to documentation that was recently fixed.
https://www.gbstudio.dev/docs/music/

You can not use bpm, you must use the lower range from 1 - 20 (in hex, the actual value max is 32) for tick speed / notes per frame.


Extra inaccuracies come from mod trackers working in 50 fps/ticks and the Gameboy using 60, which the maker of gpt player has tried their best to fix.

Thread for improving docs.
https://github.com/chrismaltby/gb-studio-site/pull/5

I have also not encountered the speed being locked, every song should set the speed at the start of a song, default speed will not restore, haven't tested if speed can change mid song, but that should work.

If you're ok with this answer, could you close this thread?

**Comment by timsamoff** [comment]
I am using the hex method of controlling tempos. When I get a chance, I'll upload two songs that are giving me trouble to test with.
