### ISSUE TITLE
Music will not play in-game until a Joypad Input is pressed

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#177]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

Can't get music to play in a Scene until a Joypad Input is pressed. (Or, at least, that's what my tests have shown.)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This can be tested with the GB Studio demo files...

1. Add a Music: Play Track to the Title Screen Scene... Test the game and it won't work.
2. DO the same thing on the Outside Scene and it will.

* **What is the expected behavior?**

Music will play whenever called.

* **What is the motivation / use case for changing the behavior?**

To provide music on Scenes when the game loads.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by timsamoff** [comment]
The music will begin on the Title even if you press a Joypad button that's not being listened for.

**Comment by timsamoff** [comment]
This is confirmed as a Web-only issue -- works fine when emulated.

**Comment by RichardULZ** [comment]
This sounds like an issue with general web features that prevent sounds from auto playing unless interacted with, not really an issue with the html5 emulator.
Try uploading to Itch.io, where they have a built in "Click to play" feature on html games that meets these conditions. 
If this resolves your issue, please close it.

**Comment by timsamoff** [comment]
Is it's "Click to Play" functionality different from mine?

http://samoff.com/CATG/

If so, I'll test it, but in my experience, clicking a button on a webpage is not within the same "domain" interacting within the "app."

In any case, it's a pretty bad UX issue, since 4 of my playtesters (who knew there was music) didn't do anything on the titlescreen for several seconds because they thought the game was still loading.

Is there a way to implement an "invisible click" function or some other form of game-instigated interaction that does not require user interactions to kick the music into gear?

**Comment by RichardULZ** [comment]
Right, this happens on itch.io too, Issue is with the js-emulator on all versions.

A temporary hackey solution i've come up with, is modifying the **GameBoyCore.js** to run ` initSound();`
Somewhere after `generateAudioFake` line 5325.

This will overide the built in handler for "when sound is disabled by user/browser", not sure of side effects.

If you would like this hack, replace the file in **web/js/GameBoyCore.js** with the one i've modified below.
[GameBoyCoreJS.zip](https://github.com/chrismaltby/gb-studio/files/3194988/GameBoyCoreJS.zip)

**Comment by timsamoff** [comment]
Thank you. I will try this!

**Comment by timsamoff** [comment]
@RichardULZ: This new JS file seems to break audio altogether (i.e., no music plays at all, even with Joypad interaction).

**Comment by RichardULZ** [comment]
@timsamoff Auto play audio should be working on Chrome, firefox, and hopefully more with the latest dev build as of 17195e7 ( see #298 )
Note the browser still needs to meet a certain 'site engagement' threshold for autoplay sound to run. Clicking anywhere in the game window will now also begin audio.

Would be great to hear how this works on your end.

**Comment by thomas-alrek** [comment]
Generally, the only guaranteed to be able to play audio, is to do it through user interaction. If you say capture a `click` event, you will be able to start audio, as it is considered as a user interaction.
However, this will only work if the event is a real event initiated by the user, a synthetic event will not work.

**Comment by RichardULZ** [comment]
@thomas-alrek That's right, a user `click` on the page is usually required.
But if the page is used enough or was clicked on recently, it may reach the media engagement index,  https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei

Itch.io includes a Click to run feature as default on all html games, so our auto play should work with that, without interaction in the game as such. 
Otherwise, any `click` on the player now also kickstarts our sound, it was previously limited to keyboard or touch buttons only.
