### ISSUE TITLE
Emotes appear behind actor sprites

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#178]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

When an emote is triggered on in the same area as an Actor Sprite, it appears behind it.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Add an emote to an interaction with another Actor. Then stand under the Actor and trigger the interaction.

* **What is the expected behavior?**

Emotes should always appear over other Actor Sprites.

* **What is the motivation / use case for changing the behavior?**

UX.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by RichardULZ** [comment]
Please test on the latest develop build, this was brought up on discord and may be resolved as of 1d22af9

**Comment by chrismaltby** [comment]
This issue is fixed now as part of the 1.1.0 release :-)
