### ISSUE TITLE
[Request] Panning around Game World with holding SPACEBAR

### ISSUE THREAD

**Issue by JasonB32** [chrismaltby/gb-studio#18]
Panning around the Game World to see all the different scenes with the SPACEBAR would help to navigate around the Game World.

**Comment by max89ac** [comment]
This would be amazing!

**Comment by chrismaltby** [comment]
Very similar to https://github.com/chrismaltby/gb-studio/issues/27 which I've just closed with commit 5d0b40821fa198e547cfb315edef28ad9ee1ca82.
This version allows panning with middle mouse, or alt+left click. You can also pan by dragging the space between scenes.

**Comment by JasonB32** [comment]
Thank you so much, anything's better than dragging those sidebars around, awesome!
