### ISSUE TITLE
Store sidebar width in project "bug"

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#188]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug.

* **What is the current behavior?**

Adjusting the sidebar width in a project without making any other changes causes GB Studio to popup "unsaved changes" dialog box when quitting.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Open a project, adjust a sidebar width, try to close project.

* **What is the expected behavior?**

Sidebar adjustments only get saved when the user saves the project.

* **What is the motivation / use case for changing the behavior?**

Easier project review.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Code commit:

https://github.com/chrismaltby/gb-studio/commit/e57237d48830d3b74d9ae245e5d729584d38ba51

**Comment by chrismaltby** [comment]
Reszing the sidebar no longer marks the document as modified in 6d63185502880ed6519ca961ec937672b1a9e140. On further thought I think this should really be stored as a per user, rather than per project setting (like the dark/light theme) so I'll probably update this again later.
