### ISSUE TITLE
[Request] Create in the menu dropdown HELP>ABOUT section

### ISSUE THREAD

**Issue by JasonB32** [chrismaltby/gb-studio#19]
It would be great to be uniform with most software by having a HELP>ABOUT window dropdown so users would know what version of GB Studio their working with.

**Comment by chrismaltby** [comment]
Good point! This is implemented now in the develop branch 94560f6d373b643a8074d0557a1f1ab3a9609ef4

**Comment by JasonB32** [comment]
Thank you!
