### ISSUE TITLE
[Bug] Actors Abscond when a Multiple Choice (Or Dialog?) box pops up on a certain frame 

### ISSUE THREAD

**Issue by KazyEXE** [chrismaltby/gb-studio#190]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When a Multiple Choice box appears, Actors set to Random Walk can sometimes run away

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Attach script invoking a Multiple Choice (or maybe Dialog) box to a joypad input, and invoke it on a certain frame (took me a few tries to reproduce)
Actor will run away.

![Example Image](https://i.imgur.com/Snhoi73.gif)

* **What is the expected behavior?**
Actors pause movement

* **What is the motivation / use case for changing the behavior?**
Not having actors run away!

* **Please tell us about your environment:**

  - Version: 1.1.0
  - Platform: Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by timsamoff** [comment]
I can verify this bug as well.

**Comment by RichardULZ** [comment]
I had this my first day on 1.0 windows too, used to be a step every second, but 1.1 made this continuous.

@timsamoff you are on 1.1 mac os correct? It's not just a windows issue.

The brute force solution is to run through every actor on script start and set actor movement to false (and forcing them to the nearest tile so they are not mid tile).

To test for this bug, i recommend running in an emulator at a lower speed, like Bgb with vsync over multiple frames, and activating a script when an actor randomly moves.

**Comment by timsamoff** [comment]
Correct -- I'm running 1.1.0 on a Mac.

**Comment by chrismaltby** [comment]
Thought this one was gone with 1.1.0... guess not.
