### ISSUE TITLE
Text: Display Multiple Choice

### ISSUE THREAD

**Issue by CastleTiles** [chrismaltby/gb-studio#191]
When using Text: Display Multiple Choice it seems that the cursor input is not bound to a single button while in game.  Pressing the "B" button  while in the multiple choice menu is immediately setting the assignment variable to false regardless of the selection the cursor is currently pointing to.  Inputting with "A" button only is behaving as expected.

**Comment by RichardULZ** [comment]
With emulators always having different buttons, i can understand how this could get confusing.

**Comment by KitF** [comment]
I'm pretty sure this is intentional, was mentioned in #158 that "B" is usually the cancel button in games.

**Comment by CastleTiles** [comment]
My apologies. I did not see that thread.
