### ISSUE TITLE
play sound effect then go back to background music

### ISSUE THREAD

**Issue by Audio-Rochey** [chrismaltby/gb-studio#194]
Wouldn't it be awesome if:

We could define music as "background" for a scene, then define "sound effects".

A sound effect could be called once (not looped), then the system should drop back to playing the background music for the scene.

**Comment by RichardULZ** [comment]
**Zalo's ZGB Simultaneous sound effects with channel mute.**
Reference docs from ZGB for possible implementations.
https://github.com/Zal0/ZGB
https://github.com/Zal0/ZGB/wiki/Sounds

https://github.com/Zal0/ZGB/blob/master/common/src/Sound.c
linked to music mute frames in main.
https://github.com/Zal0/ZGB/blob/master/common/src/main.c

It seems with this method, you may have to set Gameboy sound channel registers manually for sound fx.
It has a program for designing sounds,  https://github.com/Zal0/GBSoundDemo  
If you press A and select, it will display the registers you've set up.
Music continues while the sound plays.

**Using GBT for sound effects, and reloading song data,**
If you want to use gbt to play mod files as sound effects, it needs to be modified to store the last position, song, and likely a lot more.
```
gbt_current_step::
	.ds	1
gbt_current_pattern::
	.ds	1
gbt_current_step_data_ptr:: ; pointer to next step data
	.ds 2
```
And load these when re-played, 
there will likely be artifacts when the song re initializes until volumes, notes, or instruments are set again, May not re-trigger speed modifiers? 
Would this be told to re trigger automatically with a check on sound end in gbt?

**Comment by Audio-Rochey** [comment]
as we go from screen to screen, being able to pickup the song where we left off would be pretty useful. 
What would it take to get this implemented?

Even having some kind of put to stack that would save the current bakground song, and position would be useful. I could then call a sound effect, then pop from the music stack.

/R
