### ISSUE TITLE
[Bug] Can't build the sample project when installed with Itch app

### ISSUE THREAD

**Issue by bguyl** [chrismaltby/gb-studio#195]
**The bug**
I created a new sample project and when I tried to build. I had errors.

**To reproduce**
I installed GB Studio x64 on Windows through the Itch app.
It's installed on my 2nd HDD.

**Logs**
[Full logs](https://gist.github.com/bguyl/cc47e88c81e89cc4862f8791cfbffa52)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version: 1.1.0 Windows x64

**Comment by bguyl** [comment]
It works when installed directly

**Comment by RichardULZ** [comment]
@bguyl Do you have a space in your username? We've had issues with that before.

**Comment by bguyl** [comment]
No, I don't

**Comment by bguyl** [comment]
I tried to install it on my main disk, I had a other issue : [Logs](https://gist.github.com/bguyl/028d899da3fb3168a6b8d6cf49c7b421)

**Comment by chrismaltby** [comment]
I've reached out to leaf @ itch.io to ask about this, it seems using the Itch app launcher modifies a few environment variables I think it's TMP/TEMP specifically that's causing the problem

**Comment by chrismaltby** [comment]
This one should hopefully fixed now with version 1.1.1 which is only available on Itch.io (the only change is this fix). The Itch launcher was setting the TMP environment variable to a value that the GBDK C compiler didn't like.
