### ISSUE TITLE
why only 9 actors?

### ISSUE THREAD

**Issue by seiyria** [chrismaltby/gb-studio#196]
**Is your feature request related to a problem? Please describe.**

I'm curious why there's a limit of 9 actors. There didn't seem to be any documentation in a source code, besides a commit I found increasing them from 7 to 9.

**Describe the solution you'd like**
Some documentation either here, in a readme (maybe a description of limitations and why they exist), and/or in the code.

**Comment by schme16** [comment]
I could only find: 8c96f8b6404e0c62923764f0835f2197f179d2c9 relating to actor number. I assume that there's some hardware issue regarding this, but would also love an official explanation

**Comment by schme16** [comment]
Ok, I've played around in the source code, anything above like 11 seems to start corrupting the game (sprites lose animations, some sprites turning into others, some missing entirely, etc), and from 15 the game just straight up won't load that scene.

**Comment by Q-Bert-Reynolds** [comment]
I don't see anywhere in the source where they set sprite mode to SPRITES_8x16. The GameBoy has a hard upper limit of 40 sprites. If sprite mode is SPRITES_8x8 (the default) and all actors are 16x16, then GB Studio uses 4 sprites for each actor (therefor a maximum of 9 actors).

If this is the case, then changing the sprite mode to SPRITES_8x16 would allow for a max of 20 actors.

**Comment by Q-Bert-Reynolds** [comment]
Nevermind. Looks like they're setting it to 8x16 mode in [game.c line 33](https://github.com/chrismaltby/gb-studio/blob/master/appData/src/gb/src/game.c#L33). They're setting LCDC to 0b01100111. Bit 2 is set to 1 which is 8x16 mode.
