### ISSUE TITLE
Add proper "Unsaved Document" dialog box to MacOS app

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#198]
**Is your feature request related to a problem? Please describe.**

The currently used MacOS "Unsaved Document" dialog box is unhelpful.

**Describe the solution you'd like**

Implement the MacOS HIG dialog box when closing unsaved projects.

![gb_studio_dialog](https://user-images.githubusercontent.com/62411/58503019-989da580-813c-11e9-9eb3-312cb5f074a4.jpg)

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

**Comment by KitF** [comment]
Seconding this, even on Windows the close dialog only lets you either don't close or close losing changes. It doesn't let you save and close.

**Comment by chrismaltby** [comment]
Agreed, I've just done a bit of research through the mac apps that I'm running to work out the exact wording to go with but commit 7f6a6629b2f1aa8e85386600e9ea924420d36bd9 changes the dialogue window to the following allowing Save+Quit functionality (Icon will appear as expected on release builds)

<img width="453" alt="Screen Shot 2019-05-29 at 4 20 23 PM" src="https://user-images.githubusercontent.com/16776042/58569499-1d1c2100-822e-11e9-8e2d-cb8be03c05ac.png">

**Comment by timsamoff** [comment]
Awesome. I got my wording from Photoshop, btw, but your new dialog is much more helpful.
