### ISSUE TITLE
Username with Space

### ISSUE THREAD

**Issue by husan93** [chrismaltby/gb-studio#2]
I cannot compile the ROM because my username has a space in it.
I tried the manual installation version too, no luck.
![image](https://user-images.githubusercontent.com/49792957/56435747-df94b180-62d9-11e9-9774-37c18bc31fed.png)

**Comment by chrismaltby** [comment]
Ohh, that's not cool. Will look into this!

**Comment by caHarkness** [comment]
Same here. Even though my boot drive is drive C:, I have certain software installed in an identical location in my D: drive. For example, I have a `C:\Users\Conner Harkness` folder and a `D:\Users\Conner Harkness` folder, although the D: drive folder's name is arbitrary. Nothing in the D: drive was created from Windows.

GB Studio is accessing 'D:\Users\Conner' which tells me it must be referencing something that was previously defined as a PATH variable, and not something local to GB Studio itself. I hope that helps solve the problem...

I suspect it's related to either `%TEMP%` or `%TMP%` so maybe wherever temp files are written to, so whatever is referencing either environment variable, that path needs to be surrounded in double quotes.

![Pathvars](https://user-images.githubusercontent.com/499553/56882992-93a4e380-6a22-11e9-8e25-a77a553831c2.PNG)

**Comment by chrismaltby** [comment]
Think I've found this one, the music compilation process needed double quotes like @caHarkness said. Fixed in 1803487f6d8b5143c5b862c01c742641c45516b7

**Comment by chrismaltby** [comment]
Nevermind, music compiles now but it might still have issues compiling the engine.

**Comment by chrismaltby** [comment]
I believe this issue is now fixed in the current dev builds and also [the 1.1.1 release](https://chrismaltby.itch.io/gb-studio) (only on Itch.io right now)
