### ISSUE TITLE
[Request] Images should have indexed palettes

### ISSUE THREAD

**Issue by vince94** [chrismaltby/gb-studio#20]
Hello! Just want to say thank you so much for putting this together! One little thing I noticed is that in the sample project, the assets are RGB-mode png files, and don't have four-color palette restrictions. I opened the `logo.png` file in GraphicsGale, but wasn't sure which colors were valid.

This is nitpicky, though, I can't wait to sink my teeth into this tool & see it improve over time! Also shoutouts to using Amiga MOD files for music, I love using OpenMPT <3

**Comment by MarioLiebisch** [comment]
Feeling similar, although from a quick look at the code (and without really reading everything) it seems like there's color normalization, so they wouldn't have to be exact, but don't quote me on that. I guess the big thing is that some editors might screw around with the palettes, so just interpreting RGB images might be the more reliable way to do it.

Besides that, from the docs, the only "valid colors" are these four:

- █ #071821
- ▓ #306850
- ▒ #86c06c
- ░ #e0f8cf

**Comment by blurymind** [comment]
would be nice if support is expanded to game boy color and even game boy advance some day :D

**Comment by Lokathor** [comment]
game boy color is very similar and it's easy to imagine expanding to that.

game boy advance is wildly different and it's basically not possible to get there from here. you'd just have a whole different project for that.

**Comment by chrismaltby** [comment]
I've run a Photoshop action across all the default assets converting them to indexed PNGs using the palette defined in the docs. From commit 6e5cc00661996507d86146b11aa5ab235e6354ef these images will appear as you expected @vince94. Also uploaded the Photoshop swatch to https://www.gbstudio.dev/assets/swatches/gb-studio-photoshop.aco if it's useful to anyone, will add this to the docs, along with any other swatch files that might be useful (like Aseprite) when I next update the site.
