### ISSUE TITLE
"Script Review" view should be renamed to "Dialogue Review"

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#202]
**Describe the bug**
When I read "Script Review," I assume it refers to the game's scripting (code).

**To Reproduce**
1. Open GB Studio
2. Click on View Main Menu
3. Choose "Script Review"

**Expected behavior**
I get that this is, in effect, the "script" of the game. In this case, it only outputs game dialog, so "Dialogue Review" makes more sense to me.

**Screenshots**

**Platform (please complete the following information):**
 - OS: macOS 10.14.5
 - App version 1.1.0

**Additional context**
Pure semantics, but since there may be cause for an actual "Script Review" view in the future...

**Comment by chrismaltby** [comment]
Agreed, latest dev builds have this change in place now
