### ISSUE TITLE
[Feature] Ability to "comment-out" (mute) events

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#203]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to be able to comment-out events within a Script.

**Describe the solution you'd like**
Along with the Copy, Delete, etc., options under the context menus within each event, add a "Comment-Out Event" option.

**Comment by chrismaltby** [comment]
Hi Tim, 
In commit 03bf72d89149a7462808b18e5b212752b53d9e20 I've added this as "Disable/Reenable Event".

<img width="328" alt="Screen Shot 2019-06-25 at 1 33 14 PM" src="https://user-images.githubusercontent.com/16776042/60098730-178ef980-974e-11e9-8da4-fdca42a0b61d.png">

Disabled events have "//" in front of their name and have their contents faded (and wont be compiled when building the game)

Not too sure on the wording, I like "Mute" but was thinking if the same functionality was brought to Actors and Triggers for example "Disable/Reenable" seems to be language that would adapt to those situations too.

**Comment by thomas-alrek** [comment]
I prefer Disable / Enable myself

**Comment by timsamoff** [comment]
Thank you!

@thomas-alrek poses a good option for the wording that's not redundant.
