### ISSUE TITLE
[Feature] When Actor leaves Trigger

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#204]
**Is your feature request related to a problem? Please describe.**
Setting Events based on an Actor leaving a Trigger would be helpful.

**Describe the solution you'd like**
An Event called "When Actor leaves Trigger" with a function space for adding new Events.

**Comment by KenneyNL** [comment]
I'd very much like to see this, it would allow for more gameplay types and help the development of my point 'n click game immensely.
