### ISSUE TITLE
[Feature] Store player direction (like position)

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#216]
**Is your feature request related to a problem? Please describe.**
We can already store the player's position as variables, so why not their direction as well?

(Not quite the same as #33.)

**Describe the solution you'd like**
It would be nice to be able to store the player's direction as a variable to use when placing the player in other locations based on the stored position.

**Comment by Veund** [comment]
you could accomplish this with the if player direction function and a variable

if player direction >
set variable 1
else
if player direction ^
set variable 2

etc

**Comment by timsamoff** [comment]
I guess so, but it's pretty convoluted. A simple "get" and "set" (as with the player position) would be much more elegant.

Thanks, for the workaround, though! I'll try it out in the meantime.

**Comment by ManuGamesDev** [comment]
I programmed it in and made a pull request for it: https://github.com/chrismaltby/gb-studio/pull/276

**Comment by chrismaltby** [comment]
Closing, since this is merged in now 👍
