### ISSUE TITLE
[Optimize] the release version download .

### ISSUE THREAD

**Issue by urmyfaith** [chrismaltby/gb-studio#22]
The Release version download in China (due to GFW.)is very low, 20 KB/s maybe, which will result almost need 1h to download.

But i can be failed  when i retry  download for 3~4 times.

If there will be on https://sourceforge.net/  or  via  DropBox or some direct download links.

**Comment by chrismaltby** [comment]
Could you confirm if the downloads on the Itch.io page have the same issue? https://chrismaltby.itch.io/gb-studio
If they work I can add a link to that in the README and on the downloads page on gbstudio.dev
Definitely would like to help but want to avoid maintaining too many different sites for each release if possible.

**Comment by urmyfaith** [comment]
It's the same result, almost one hour to download. 

Maybe the quickest way is build from source?

**Comment by chrismaltby** [comment]
Closing this one as I don't think there's much more that can be done.
