### ISSUE TITLE
[Feature Request] Fade to Black option in Switch Scene

### ISSUE THREAD

**Issue by Josh-McMillan** [chrismaltby/gb-studio#220]
**Problem**
There is no way to fade in and out from black during a Switch Scene event (instead of white, which is the current behavior). You can overlay, but it does not switch scenes.

**Describe the solution you'd like**
I would like for a toggle on the Scene Switch event for "Fade to Black", and when the Scene Switch event is called, the room transitions to black instead of white. When "Fade to Black" is not toggled, the current behavior is applied and the Scene Switch fades in and out from white.

**Alternatives**
I considered using an overlay to black and then switch scene, but it would add unnecessary complexity to the scripts I'm trying to work with and not really solve the issue.

**Context**
I'm currently implementing a Day/Night cycle and when the sun goes down and the time is night, I would like for the scenes to switch by fading to black instead of white (which would be more like daytime.)

**Comment by RichardULZ** [comment]
Scene switch takes a lot of power to load and place all the new background tiles,
To improve performance and faster vram access, the screen is turned off during these sections, which is white on a gameboy, (you can still notice a small hitch in audio when this happens). 

Not turning off the screen and setting palettes black causes almost a second of lag for any scene switching, becuase the vram is still being accessed. This also makes the audio hitch a lot longer.

Things to look into,
Loading the tiles over multiple frames to reduce audio hitch.
