### ISSUE TITLE
Bug Pixel line

### ISSUE THREAD

**Issue by maarcello** [chrismaltby/gb-studio#23]
![2019-04-22-11-07-56](https://user-images.githubusercontent.com/49162677/56493363-1a236780-64ef-11e9-9386-bd1b14d5f8e0.gif)

When I walk around I have this weird-looking line on top of the game..
tbh it's hard to see in a GIF just check the edges from the house it has some distortion when I walk around.. any ideas?

**Comment by MarioLiebisch** [comment]
Yeah, really odd. At first I thought it's just the emulator drawing without vsync (i.e. screen tearing), but it also happens in other emulators (in my case VisualBoyAdvance from 2013).

**Comment by RichardULZ** [comment]
#137 Change Render order to Fix Vsync on game boy

**Comment by chrismaltby** [comment]
This issue is fixed now as part of the 1.1.0 release :-)
