### ISSUE TITLE
I can't run the game anymore because of an error.

### ISSUE THREAD

**Issue by RohanRamdhan** [chrismaltby/gb-studio#238]
[Game Test.zip](https://github.com/chrismaltby/gb-studio/files/3346594/Game.Test.zip)
![Game](https://user-images.githubusercontent.com/52421589/60452861-da37d980-9c2f-11e9-85fe-0d7aa1f647ea.PNG)

Hey so I got this bug today. I can't run my game anymore.
To get this you have to click run and it will show the error messages.

I expected to run the game and I also put an screenshot showing it.

App version is 1.1

There is also a download link of the project.

I hope you can help me.

Kind regards,

Rohan Ramdhan

**Comment by chrismaltby** [comment]
Hi Rohan,
There was a single 8x8px file `cursor.png` in the sprites folder where all sprites need to be at least 16x16px. I've added some space to the sides of this image to make it 16px and that works for me on version 1.1.0 now
[Game_Test_fixed.zip](https://github.com/chrismaltby/gb-studio/files/3346796/Game_Test_fixed.zip)
I'm going to make a change so this will give better errors in the future.

**Comment by chrismaltby** [comment]
Commit b8cc82418fd85f6b632263fc21c2b2c26a23d1b3 adds better errors when this happens now, so this will be improved for the next release :-)
