### ISSUE TITLE
[Request] a couple of things

### ISSUE THREAD

**Issue by DerekLF** [chrismaltby/gb-studio#24]
first of all, I've been playing around with the program. It's easy to use and it has got a lot of options. So overall, Great job!
But I'm missing some minor things, I'm probably the only one who's missing them :/.

First thing:
an in-game menu, the only problem is it would use a considerable amount of storage. This could be combined well with the Save-Load data idea #5. Editing the menu also probably needs it's own working field, not in Game World.

Second thing:
The ability to make an actor follow another actor. Make them walk beside each other or behind them through a pre-programmed path(Start point, way point,.. , End point). For example: Make the Player follow an actor who's telling you stuff about the game and it's world. OR an actor who's following the Player because you have to take it somewhere.

Third thing:
This one is a lot easier than the other 2.. When you boot  up GB Studio and you want to Open your last project. I'll have to search for some time before I find it. So perhaps when you boot GB Studio it will open you last project. OR when you go to the Open project you will see your recent projects.

fourth thing:
That you could show the actors name above the text field when talking to an actor.

**Comment by AlmondWhite** [comment]
The fourth point made in particular I feel should be relatively straightforward to incorporate, if we were to create a custom ui element such as the text _frame.png_ that had our target characters name or even just a different styling of the frame itself and have a the option to asign a different frame to each _Display Text,_ event, would be an adequate solution I'm sure.
