### ISSUE TITLE
[Bug] BANKED_DATA_TOO_LARGE

### ISSUE THREAD

**Issue by Liddell-afk** [chrismaltby/gb-studio#248]
**Describe the bug**
I have quite a big amount of events attached to the "attach script to button" event. I created a big event group with nested if statements and if I copy this group to a bunch of different places within the mentioned button event at some point it wouldn't compile and gives the following error message:

![image](https://user-images.githubusercontent.com/52892390/61187935-4971ec80-a678-11e9-981d-e06d3feb626a.png)

If I remove those groups one by one it compiles again at some point. Kazy suggested I should post my project here. One theory is, that if there is too much in one single event, it might cause the above error.

**To Reproduce**
I expanded my groups and events in the project file just until the event group (named "set waypoint") that causes the error. If you delete this one, it works. The same event group is placed a few more times further up but I collapsed everything. It only breaks after adding this one.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version: most recent 1.2 dev version

[Pathfinding Prototype.zip](https://github.com/chrismaltby/gb-studio/files/3390320/Pathfinding.Prototype.zip)

**Comment by Polyducks** [comment]
A temporary fix, perhaps - but instead of copying and pasting the same code across many scripts, perhaps you could attach it to an actor and activate that actor's script. This gives it a more DRY approach.

**Comment by thomas-alrek** [comment]
I think this is a perfect candiate for the [Custom Events](https://github.com/chrismaltby/gb-studio/pull/296) feature that was merged a while ago. Have to tested this in the [development builds](https://github.com/chrismaltby/gb-studio#documentation)?

**Comment by pau-tomas** [comment]
Worth a try, but it might not help. At compile time the “instances” of Custom Events are replaced by copies of all the Events in the Custom Event script. So, in the end, if a Custom Events contains lots of Events this problem will most likely happen anyway.

**Comment by LiddellOdd** [comment]
> 
> 
> A temporary fix, perhaps - but instead of copying and pasting the same code across many scripts, perhaps you could attach it to an actor and activate that actor's script. This gives it a more DRY approach.

Possibly, but I already use actors this way in this prototype and will most likely run out of actors :) But I was away from GB Studio for awhile and was just following the dev updates on discord. So I will probably begin anew with the new build and see where I get with a fresh mind.

As long as this isn't a common occurence and more of an edge case, I guess you guys can keep this in the back of your heads and don't spend time on it right now ;)
