### ISSUE TITLE
Timed Dialogue

### ISSUE THREAD

**Issue by N47h** [chrismaltby/gb-studio#251]
It would be nice to have dialogue that goes away automatically after a specified amount of time, rather than waiting for input.

I personally hope to use this with a timer of 0, so I can continue the script immediately, with the dialogue kept visible by the overlay.

(Similar to #200, but I think this is a more elegant method with more versatility.)

**Comment by RichardULZ** [comment]
This could probably have been added to post #200 instead of a separate issue.

**Comment by N47h** [comment]
Yeah, I found the other post afterward, unfortunately. ^^;

**Comment by thomas-alrek** [comment]
@N47h you can delete your own issues. So you can just delete this and add a comment on post #200 if you'd like

**Comment by N47h** [comment]
Can I? I'm looking all over and not seeing a way.
