### ISSUE TITLE
IF statement without ELSE

### ISSUE THREAD

**Issue by hangedmandesign** [chrismaltby/gb-studio#253]
**Is your feature request related to a problem? Please describe.**
Lacking a FOR loop function, I tend to prefer using multiple IF statements in sequence, rather than nesting each IF statement into each previous ELSE because then I'd have to click eight times to uncollapse them all. This means that my scripts are getting extremely cluttered by ELSE statements that don't do anything; I can collapse them but they still take up vertical and visual space. 

**Describe the solution you'd like**
I'd love if there was a checkbox on any IF script object that would simply show/hide the ELSE portion below. Maybe it could delete the contents of the ELSE, or just leave it as is, presumably empty.

**Describe alternatives you've considered**
I would actually prefer that it not be a different script object, because that just lengthens the list and doesn't allow a user to change their mind later. And just hiding it in the editor seems to have the least impact in terms of UI.

**Additional context**
I've worked with a bunch of tools that use scripting abstraction and while I love them, the really fiddly bits are the things that slowly make them unusable, so I'm glad you've done a lot to consider UX; I hope you'll consider this.

**Comment by timsamoff** [comment]
The latest versions of GB Studio fold the Else statement so that it is not "open," which is convenient. It is up to the dev to use it or not.

I'm not trying to negate your request, but if you haven't been using the latest versions, you might not have seen this.

**Comment by hangedmandesign** [comment]
I haven't tried the indev version, I will check it out!

**Comment by hangedmandesign** [comment]
It's still adding an expanded ELSE by default in the 1.20 latest build, as far as I can tell.

**Comment by timsamoff** [comment]
Which OS?

**Comment by hangedmandesign** [comment]
Windows 10.
![iferror](https://user-images.githubusercontent.com/15364939/62141461-9d0c4900-b2ba-11e9-9d90-15fbcf720c2b.gif)

**Comment by timsamoff** [comment]
Interesting... I'm using Mac OS and this was working in some previous version, but it's definitely expanded for me now too.

**Comment by chrismaltby** [comment]
Hi @hangedmandesign Just to let you know I'm currently working on an update in #318 that will add the ability to remove the Else path from conditional statements

<img width="400" alt="Screenshot 2019-11-08 at 18 01 33" src="https://user-images.githubusercontent.com/16776042/68502299-01df2400-0258-11ea-9a23-5b2e982ba457.png">

The update also adds Switch statements and a number of other usability improvements.

**Comment by RichardULZ** [comment]
This can be closed 🎉

**Comment by hangedmandesign** [comment]
Sorry for the delay in closing, thanks for the update!
