### ISSUE TITLE
'Comment' scripting object

### ISSUE THREAD

**Issue by hangedmandesign** [chrismaltby/gb-studio#254]
**Is your feature request related to a problem? Please describe.**
I've been using Event Groups sometimes as 'comments', leaving notes for myself where to add sounds or to structure things. They're very handy in this way, but they're also the same colour as other collapsible objects so they don't really stand out.

**Describe the solution you'd like**
I'd love if there was a 'comment' object that was functionally like an Event Group, but had nothing beneath it, and was always a bright unique colour that other nested objects can't be.

**Describe alternatives you've considered**
It just being a standard script object colour would also work too, but having it stand out is a big part of the value.

**Comment by timsamoff** [comment]
I think this is a great idea.

**Comment by ManuGamesDev** [comment]
I programmed it in and made a pull request for it: https://github.com/chrismaltby/gb-studio/pull/268

**Comment by ManuGamesDev** [comment]
I am new to github and i messed this up a little bit, here is the new pull request: https://github.com/chrismaltby/gb-studio/pull/274

**Comment by ManuGamesDev** [comment]
@gregtour people on the discord seem to like it better
