### ISSUE TITLE
Scenes won't be created in develop build

### ISSUE THREAD

**Issue by MonoDj2017** [chrismaltby/gb-studio#256]
**Describe the bug**
No scenes will spawn in at all. It happens with both pressing S and clicking over to add a scene.

**To Reproduce**
1. Make a project
2. Press S or move over and select new scene
3. Click on the main field

**Expected behavior**
The scene should appear where I click on the main field.

**Screenshots**
(Had to zip the video.)

[2019-08-03 21-57-35.zip](https://github.com/chrismaltby/gb-studio/files/3464502/2019-08-03.21-57-35.zip)

**Platform (please complete the following information):**
 - OS: Windows 10 Home 64bit
 - App version : Dev 1.20-Alpha 1

**Additional context**

**Comment by RichardULZ** [comment]
Can you include a zip of the project folder? 

Does this happen when starting with a new template project?

**Comment by MonoDj2017** [comment]
This happened with a project I brought over from 1.1.0, two new blank projects, and a sample project.

Here is the zip for the main project.
[FAITH THE REIMAGINING.zip](https://github.com/chrismaltby/gb-studio/files/3464511/FAITH.THE.REIMAGINING.zip)

**Comment by chrismaltby** [comment]
Looks like this was introduced when fixing a copy/paste scene bug recently, I've just pushed an update in commit c7e5724395a677e85029e9a15c27f36149f534c2 that should fix the issue for you.
