### ISSUE TITLE
Project saves with `.DS_Store` on windows

### ISSUE THREAD

**Issue by josefnpat** [chrismaltby/gb-studio#26]
![image](https://user-images.githubusercontent.com/646162/56510109-7df96080-64ee-11e9-97cc-629866d8201c.png)

For some reason projects have the macOS `.DS_Store` file included.

**Comment by chrismaltby** [comment]
Oh those pesky things get everywhere... I've fixed this in the develop branch so next release shouldn't have this problem 2554bf4ba7375dce5aeaed5a9d1cffede2020130
