### ISSUE TITLE
Allow movement like GIMP and Photoshop

### ISSUE THREAD

**Issue by josefnpat** [chrismaltby/gb-studio#27]
This is a feature request.

I would really like to be able to pan around the viewing area by holding the middle mouse button, like GIMP and Photoshop.

Instead holding the middle mouse button moves the content around like a website.

Here's an example!

![gd_move](https://user-images.githubusercontent.com/646162/56510313-08da5b00-64ef-11e9-8296-15b1f88e4985.gif)

**Comment by chrismaltby** [comment]
Implemented in develop commit 5d0b40821fa198e547cfb315edef28ad9ee1ca82.
I've made it work with middle click like you suggest but also while holding Alt key and left click. You can also just left click and drag on the space between scenes to drag the view around.
