### ISSUE TITLE
Actor: Set Animation Frame no longer previews frame correctly in dev version

### ISSUE THREAD

**Issue by proximitysound** [chrismaltby/gb-studio#271]
In the stable version (1.1) when using the "Actor: Set Animation Frame" event, incrementing the frame number updates the preview next to the actor name, which is very helpful. This feature appears to be broken in 1.2, as it will only show the 1st frame.
<img width="326" alt="Screen Shot 2019-08-27 at 9 57 26 AM" src="https://user-images.githubusercontent.com/37381082/63777439-1b0b4200-c8b1-11e9-97f8-5d836fd752a9.png">
^Three different actors using the same sprite sheet, and with different frames indicated, but only showing the first frame in the preview next to the actor name.

**Comment by chrismaltby** [comment]
Hi @proximitysound This should be fixed in the latest development build with the changes I've made in commit a47a25d495f62948ac84399d590fff803c69c5f3
Let me know if this works for you now :-)

**Comment by proximitysound** [comment]
Works! Thank you!!!
