### ISSUE TITLE
Avatar + Text Overflow Corrupting Background Graphics

### ISSUE THREAD

**Issue by SetsuneW** [chrismaltby/gb-studio#291]
**Describe the bug**
Filling the text box with Avatars enabled eventually overwrites background tiles.

**To Reproduce**
1. Actor -> Text: Display Dialogue
2. Apply an Avatar
3. Fill text box with 3 lines of "1234567891234567" (the limit in the editor).
4. Build and talk to Actor.

**Expected behavior**
Either the text to display correctly, or the Editor text box to truncate the text, as it did previously to 18/18/16.

**Screenshots**
![GBStudioTextSpriteBug20190916](https://user-images.githubusercontent.com/50024836/64941973-f06c3380-d835-11e9-800a-c3540eca45e6.png)
(I skipped 0 in my text string.)

**Platform (please complete the following information):**
 - OS: Windows 10 Build 18362
 - App version Commit 8366701 (Dev Build)

**Additional context**
N/A

**Comment by RichardULZ** [comment]
This issue was fixed by pau-tomas, and can now be closed.
