### ISSUE TITLE
Text Overflow on line 3 when pasting from line 2

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#293]
**Describe the bug**
When pasting starting from line 2 of a text box, it is possible to write more than 16 characters on line 3.

**To Reproduce**
1. Make a new dialogue box
2. Paste this text 3 times `farm. Your father`
3. It should result in this
![image](https://user-images.githubusercontent.com/34431457/65103806-78fbf700-da23-11e9-8037-e1e6802170a8.png)
4. This will overflow into the background tile storage as the last line contains 17-18 char

**Expected behavior**
The 3rd line to be cut to 16 characters after pasting.

**Screenshots**
![image](https://user-images.githubusercontent.com/34431457/65103744-4651fe80-da23-11e9-9eda-420f25a9d67d.png)

**Platform (please complete the following information):**
 - OS: [Windows]
 - App version [1.1.0]

**Additional context**
Typing anything new in the box will crop it to 18,18,16 again.
Discovered by "Hatch Was Here" on discord.

**Comment by RichardULZ** [comment]
@pautomas has a change in #292 that makes this bug a feature.

It allows for any length on the last line, as long as the maximum characters (including spaces) is 52 or less.
For example, lines like 17,18,17 in length will not break as in 1.1
![image](https://user-images.githubusercontent.com/34431457/65146025-0b75b800-da6f-11e9-8c3e-74f0e925817a.png)

It is possible under one circumstance to get 53 and cause the issue, though this could not exactly be reproduced on mac.
![image](https://user-images.githubusercontent.com/34431457/65145991-f436ca80-da6e-11e9-8b98-a982d5c6abef.png)

Since this is still about being able to rarely paste more than 16 characters in the 3rd line, is it instead  possible to **limit all lines to 18**, with **52 maximum** characters per box?

**Comment by chrismaltby** [comment]
Hi @RichardULZ I've just merged in f79c2041a7f7e74c5f7100f77e2cc5afc9dfbaa3 which limits all lines to 18 characters (16 if an avatar has been set) and 52 characters maximum allowing lines to be 17/18/17 or 18/16/18 whichever combination you want. Wasn't able to reproduce the 53 character issue, could you maybe give it a try and see if this fixes it for you?
Thanks

**Comment by RichardULZ** [comment]
Perfect, all lines are cropped to the 52 max characters, no matter how I try to paste, and the project seemed to be automatically fixed upon opening.
Fantastic! Closing now.
