### ISSUE TITLE
Sprite Overlay Error - HEX #306850 to HEX #071821

### ISSUE THREAD

**Issue by Re-Crix** [chrismaltby/gb-studio#297]
**Bug Description**
Not sure what causes this, but it seems to happen when a sprite using HEX #306850 is placed on top of a background tile that uses HEX #071821, the overlaid sprite turns black besides the color HEX #e0f8cf which stays the same. This happens all the time even if only a half or even a fourth of the sprite is overlaid. This ONLY affects HEX #306850 on the sprite, not HEX #86c06c, HEX #071821, or HEX #86c06c.

**To Perform the Error**
1. Create a background using the Gameboy color palette, making sure HEX #071821 is used on a tile for at least a fourth of the tile's size.
2. Go to '+'.
3. Click on 'Scene'.
4. Add a scene.
5. Select the created background containing HEX #071821.
6. Create a sprite using the Gameboy color palette, making sure HEX #306850 is used. Size: (16 x 16).
7. Go to '+'.
8. Click on 'Actor'.
9. Place the actor on a background tile using HEX #071821.
10. Go to 'Sprite Sheet'.
11. Click on the created sprite using HEX #306850.
12. Make sure when the game boots, you get shown the screen with the background using HEX #071821 with the sprite using HEX #306850
13. Go to 'Game'.
14. Click 'Run'.
15. There is the issue.

**What the Expected Result is**
The expected behavior was that when the sprite using HEX #306850 is overlaid on a background tile using HEX #071821, the HEX #306850 on the sprite should remain the same and not become HEX #071821.

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/47164485/65790646-5356a800-e11d-11e9-81c1-cd24b3b86e03.png)
![Screenshot_3](https://user-images.githubusercontent.com/47164485/65790642-52be1180-e11d-11e9-894e-e954aa032a7b.png)
![Screenshot_4](https://user-images.githubusercontent.com/47164485/65790644-52be1180-e11d-11e9-9288-aa66ae247cc0.png)
![Screenshot_5](https://user-images.githubusercontent.com/47164485/65790645-5356a800-e11d-11e9-9e70-bed24ba65691.png)

**Platform**
 - OS: [Windows 10 x64 Build: 1714.1006]
 - App version [v.1.1.0]

**Comment by RichardULZ** [comment]
For anyone else that comes across this issue, dark green is not a supported color for sprites. 

Alternatively, you can bake the sprite into the background and use a 2 frame sprite, one being transparent for interaction, and another as base background/revealed color. 

This will not let you walk through as the sprite must be enabled to be visible, a request for disabling collision is already open. #205
