### ISSUE TITLE
Running a scene event only once

### ISSUE THREAD

**Issue by AlmondWhite** [chrismaltby/gb-studio#3]
I have an event that runs once my player enters a scene, however if the player leaves and returns the event assigned to that scene runs each time.

I tried using an if statement by assigning a value to a variable and removing it after the event runs but this makes no difference. 

Is there a way to have a scene's event run just once?

**Comment by AlmondWhite** [comment]
Found a workaround by creating a trigger and asigning the desired event to that and calling a "stop script" event by changing the calling variables value. This is as opposed to adding events to the scene directly as these are most likely intended to be run each time the scene is called in to view.

**Comment by chrismaltby** [comment]
If I understand correctly you should have been able to do a scene start script with "If Variable Is False" and putting your entire script you want to run once within that and as the last event set the variable to be true. That way the first time you go to the scene the variable is false, the script runs, then it's true so next time you go to the scene it won't run.

But if you've found another way then that's cool too!
