### ISSUE TITLE
[Feature] Track GB Studio version in project file and disallow back-porting

### ISSUE THREAD

**Issue by timsamoff** [chrismaltby/gb-studio#307]
**Is your feature request related to a problem?**
Currently, projects created in newer versions of GB Studio can be opened in older versions with unexpected results (e.g., missing art, scripts, etc.). This is especially problematic in an academic environment where schools cannot update as frequently as students.

**Describe the solution you'd like**
Ideally, when newer project guile files are opened in older versions of GB Studio, a message would pop up stating something like:

This project was made in GB Studio version x.x.x and you’re attempting to open it in an earlier version. Please download the latest version from [[link to latest build]].

**Describe alternatives you've considered**
A pop up warning that opening newer versions in older versions may have unexpected results.

**Comment by chrismaltby** [comment]
Hi Tim, Completely agree. I actually implemented this already in the dev builds for 1.2.0 a few months back. So if you try to open a future project file using 1.2.0 you'll see a message like the following:

<img width="571" alt="Screenshot 2019-10-26 at 15 14 09" src="https://user-images.githubusercontent.com/16776042/67620956-148f3d00-f804-11e9-997b-de4dc8eed181.png">

Unfortunately there's no much I can do about the existing installs of 1.0 and 1.1 but going forward this shouldn't be an issue.
