### ISSUE TITLE
Change default GBC Palette Colors

### ISSUE THREAD

**Issue by proximitysound** [chrismaltby/gb-studio#308]
When loading the default palette for the custom palette colors in the dev version, the end result is somewhat dark and washed out compared to the emulated colors both for the web and the GBStudio Build and Run (assuming they use the same GameBoyCore.js).

Not using any Custom Palette yields this:

<img width="480" alt="Custom_Off" src="https://user-images.githubusercontent.com/37381082/67332211-c5d46100-f4ec-11e9-8b52-967efb74fd67.png">

Which looks great. Using the custom palette's default yields this:

<img width="480" alt="Custom_Default" src="https://user-images.githubusercontent.com/37381082/67332300-d97fc780-f4ec-11e9-8230-f88db3ad1f4e.png">

The 5-bit color values for the GameBoy Color make a perfect copy of this palette impossible, but I feel these values are a more accurate representation:

<img width="480" alt="Custom Palette By Eye Final" src="https://user-images.githubusercontent.com/37381082/67332418-f9af8680-f4ec-11e9-9d03-0ea913b6ccd7.png">

Colour 1: 29,31,28
Colour 2: 22,30,17
Colour 3: 10,19,15
Colour 4: 4,5,10

**Comment by RichardULZ** [comment]
@proximitysound Can you double check this works as you expect and close? Thanks for your help!

**Comment by proximitysound** [comment]
Works great! Thanks for implementing/reminding me.
