### ISSUE TITLE
MBC1 problem

### ISSUE THREAD

**Issue by cubicstyle** [chrismaltby/gb-studio#317]
"MBC1" can be selected in the cartridge settings, but it only affects the gb header flag.
Bank switching method is different between MBC1 and MBC5, MBC1 should be used "SWITCH_ROM_MBC1"  function in GBDK.
And MBC1 cannot use Bank 20h,40h,60h, do not map data to this bank.
It has not been tested, probably it may not work with actual MBC1 cartridge.

**Comment by chrismaltby** [comment]
Thanks for letting me know, shouldn't be too difficult to fix this. I'll have a go over the next few days.

**Comment by chrismaltby** [comment]
I need to test this fully on the Windows build but I have a fix for this now in PR #321

**Comment by cubicstyle** [comment]
Thank you for the fix. 
I'll test with a mbc1 cartridge later.
