### ISSUE TITLE
Uncaught Error: spawn cmd ENOENT / events.js:L167C:7

### ISSUE THREAD

**Issue by Locherdev** [chrismaltby/gb-studio#319]
I can compile the game to play just fine but when i try to export as ROM or WEB, I'll get this error.

This is the stack trace:
`
Error: spawn cmd ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
at onErrorNT (internal/child_process.js:407:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
`
The "build" folder is produced regardless and the .gb file that is found inside can be opened and played.

I am using the develop version of GBStudio, the last commit of that branch is 3ef5be3f5346d45eb702164116723b5e2e6c90b4

I think the export process was ultimately successful and the javascript error is due to something different not connected to my game.

![grafik](https://user-images.githubusercontent.com/45494626/68506875-d74a9680-026a-11ea-93ab-d8c07892e61c.png)
![grafik](https://user-images.githubusercontent.com/45494626/68506888-e16c9500-026a-11ea-9008-4eeb5ebc8a2a.png)

**Comment by locherunderscore** [comment]
I just realized that this error also appears when I press on this button here. 
So i think it's not limited to exporting the project.

![grafik](https://user-images.githubusercontent.com/45494626/68528276-e2480a00-02f0-11ea-8c0f-b0f7468108b3.png)

**Comment by chrismaltby** [comment]
It looks like this is an issue with the module I was using to open the project folders after a successful build. I found this open issue https://github.com/sindresorhus/open/issues/56 which seems to be the same problem.

I was unable to reproduce this on any OS but I've tried removing the `open` module entirely and replacing it with Electron's `shell` API https://electronjs.org/docs/api/shell

This has been added to the develop build in commit 19b251c4fb0e6904558d0bad301d2f9a5547b71f 

Could you give this version a try and see if it fixes the issue for you?

**Comment by Locherdev** [comment]
closing due to outdated issue, 
Although I am unable to test the solution, as of now I will assume that this behavior is fixed
