### ISSUE TITLE
Scene resizing issue

### ISSUE THREAD

**Issue by Artistblock307** [chrismaltby/gb-studio#323]
**Describe the bug**
I'm running into an issue while trying to resize a scene from 160x144 to 256x256

**To Reproduce**
0. Use Linux with GBS 1.2dev 
1. Start a new project
2. Delete all scenes larger than 160x144
3. Start planing out your project by adding scenes.
4. Get stuck because you can't change the scene to a 256x256 background

**Expected behavior**
To be able to use larger backgrounds

**Screenshots**
![Peek 2019-11-11 11-52](https://user-images.githubusercontent.com/11469244/68608946-bd32d300-0479-11ea-9f58-22e13ac0a6c7.gif)

**Platform (please complete the following information):**
 Linux Manjaro

**Comment by chrismaltby** [comment]
Did you download your Linux build today by any chance? This like it could be a bug I fixed yesterday afternoon in ddbfa00d7575b227314b71cc06324550b5775e7a  which should be available if you download again.

The issue there was after deleting any scene you were unable to change the backgrounds on any existing or new scenes. Does the bug only prevent changing to a 256x256 background or can you not change any backgrounds at all?

**Comment by Artistblock307** [comment]
It works now. Thanks 👍
There was also an issues with copy and paste (copying scenes) but I think
it's fixed now. The "Add" thing would pop-up and think I wanted to paste
another scene.
