### ISSUE TITLE
Add button elements are not localized

### ISSUE THREAD

**Issue by marcosecchi** [chrismaltby/gb-studio#329]
**Describe the bug**
The _Add_ button elements (Actor/Trigger/Scene) are not localized.

**To Reproduce**
1. Go to GBStudio
2. Switch on any non-english language
3. Click on '+' (_Add_ button)
4. The four buttons are not localized

**Expected behavior**
The three selections should be localizable.

**Screenshots**
![Schermata 2019-11-17 alle 16 40 11](https://user-images.githubusercontent.com/752514/69009985-e3b1ac00-095a-11ea-83f2-f9b6f020ef49.png)

**Platform (please complete the following information):**
 - Any platform

**Comment by chrismaltby** [comment]
Thanks @marcosecchi This is fixed now as of commit 7048d388ecf7a0d8968ab77b07ddf7e6627e6c17
