### ISSUE TITLE
Colour previews show desired colours, not actual

### ISSUE THREAD

**Issue by Polyducks** [chrismaltby/gb-studio#341]
**Describe the bug**
Gameboy colour encodes colours in 5bit. When saving your new colour from a hex, the preview shows the raw hex code, not the processed colour.

**To Reproduce**
1. Go to settings, colours
2. paste hex colour into box
3. press 'convert hex'
4. colours don't update to show processed colours.
 (#F1F2DA, #FFCE96, #FF7777 and #00303B are good examples for this)

**Expected behavior**
When you press 'convert hex', the colour preview should update with the processed colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/8634148/70091358-db709680-1613-11ea-89e5-fc51200b1d08.png)

**Platform (please complete the following information):**
 - OS: Win 8
 - App version 1.2

**Comment by Polyducks** [comment]
Further exploration shows that the preview colours are different to actual even when not converting the colours from hex. The following colours were set by changing the 0-31 values of the RGB. Above is the live game, below is the settings preview.

![image](https://user-images.githubusercontent.com/8634148/70091904-09a2a600-1615-11ea-8d67-45c4eee0faa4.png)

**Comment by chrismaltby** [comment]
I've had a go at fixing this in 707079b06b10bf12777de7ef0ba84d74cfd67ceb by reverse engineering the emulator to try and match the colours. The latest dev build seems to match exactly for me now, how does that look for you?

**Comment by Polyducks** [comment]
Thanks for getting to this so quickly, Chris,

![image](https://user-images.githubusercontent.com/8634148/70186746-82246800-16e4-11ea-9061-10ebe29fcca0.png)

The first thing I noticed was that the default colours are displayed differently to the actual. I'm not sure if that will cause confusion for the users.

You can mark this issue solved.

**Another potential issue stemming from this investigation**

_Quick_ disclaimer here - I've spent a lot of my time making and critiquing colour palettes for lospec, so the differences below will be minute.

When making the colour conversion from hex, the colours weren't as close to the original hex colours as they are if I adjust them manually. This might be a new, different bug - a problem with the hex colour conversion.

target colours:
![image](https://user-images.githubusercontent.com/8634148/70187079-4b028680-16e5-11ea-88b9-b50d5837951d.png)
(from here: https://lospec.com/palette-list/ayy4)

hex conversion:
![image](https://user-images.githubusercontent.com/8634148/70187334-d419bd80-16e5-11ea-81c6-fec37b237885.png)
![image](https://user-images.githubusercontent.com/8634148/70187055-41791e80-16e5-11ea-998c-ad00e8b840a8.png)
R	G	B
0	6	7
31	14	14
31	25	18
30	30	27

manually corrected version:
![image](https://user-images.githubusercontent.com/8634148/70187268-a92f6980-16e5-11ea-89f0-6c611b2ddc2c.png)
![image](https://user-images.githubusercontent.com/8634148/70187193-82713300-16e5-11ea-89a2-cc61691c256d.png)
R	G	B
0	4	7
31	14	9
31	27	18
30	30	27


It looks to my eye that the hex conversion part of the tool has a bias towards blue/green, but testing #FF0000 returns 31 0 0, #10FF00 returns 2 31 0 and #AAFF00 returns 21 31 0 - all as expected.

The above may all be the ramblings of someone who has spent too much time tweaking colour.

**Comment by chrismaltby** [comment]
Hi @Polyducks that first issue with the default colours was an easy fix. The other one less so.

The emulator was using the following function to determine the hex code to display depending on the 5-bit RGB values in an attempt to match how the colours appear on a real GBC display.

```
const rgbToGBCHex = (red, green, blue) => {
  const value = (blue << 10) + (green << 5) + red;
  const r = value & 0x1f;
  const g = (value >> 5) & 0x1f;
  const b = (value >> 10) & 0x1f;
  return (
    (((r * 13 + g * 2 + b) >> 1) << 16) |
    ((g * 3 + b) << 9) |
    ((r * 3 + g * 2 + b * 11) >> 1)
  ).toString(16).padStart(6, "0");
};
```

To allow you to enter a hex value and get the correct RGB value back I needed an inverse of this function which required solving those 3 equations
(((r * 13 + g * 2 + b) >> 1) << 16)
 ((g * 3 + b) << 9)
 ((r * 3 + g * 2 + b * 11) >> 1)
to get the values of r, g and b.

Finally managed to do that in PR #359 which is now merged into the develop build and given the palette you provided gives the values

R G B
0 4 10
31 17 9
31 31 13
31 31 26

Which while not exactly your manual values are much closer to what you were expecting.

<img width="480" alt="Screenshot 2019-12-10 at 23 58 09" src="https://user-images.githubusercontent.com/16776042/70579574-ff4e5200-1ba8-11ea-881f-821142518985.png">
