### ISSUE TITLE
Alt + Tab causes 'alt' to get stuck on editor on blur, causing 'add event' to be stuck on 'paste event'

### ISSUE THREAD

**Issue by Polyducks** [chrismaltby/gb-studio#343]
**Describe the bug**
The 'alt' button gets stuck as 'on' when using alt+tab to switch windows, causing the 'add event' to be stuck on 'paste event' until pressing and releasing alt again.

**To Reproduce**
1. Open the gb studio editor
2. Alt+tab to switch windows
3. Switch back to the editor
4. See the code sidebar, where 'add event' has been changed to paste.

**Expected behavior**
On blur and on focus, clear the keyboard button statuses.

**Screenshot**
![2019-12-04_21-22-53](https://user-images.githubusercontent.com/8634148/70182877-a2502900-16dc-11ea-8a62-6592000e815d.gif)

**Platform (please complete the following information):**
 - OS: Win 8.1
 - App version 1.2

**Comment by chrismaltby** [comment]
Hi @Polyducks this is now fixed in #358
