### ISSUE TITLE
Collisions no longer able to be placed

### ISSUE THREAD

**Issue by DylanJuran** [chrismaltby/gb-studio#351]
**Describe the bug**
Cannot place or remove collisions in editor in existing project. 
New projects allow collision changes.
Affects both Mac and PC versions in same project

**To Reproduce**
1. Open Project
2. Click on Collisions icon in sidebar
3. attempt to place or remove collision in any scene

**Expected behavior**
I expect a red tile to be added or removed when clicking the tile indicated. This was the behavior on v1.1, but is missing for me in this project in 1.2
[Archive.zip](https://github.com/chrismaltby/gb-studio/files/3934655/Archive.zip)

**Screenshots**

**Platform (please complete the following information):**
 - OS: macOS 10.14.6
 - App version 1.2.0

**Additional context**

**Comment by Polyducks** [comment]
Clarity: User reported this happened when taking a 1.1 project into 1.2, and doesn't occur on new projects made in 1.2

**Comment by DylanJuran** [comment]
Turning on "Show Collisions" resolved this issue,

**Comment by DylanJuran** [comment]
Turning on "Show Collisions" resolved this issue,

**Comment by chrismaltby** [comment]
This was actually a bug, with "Show Collisions" turned off you still should have been able to view/edit collisions but only when using the collisions tool. 
I've fixed this now in #356
