### ISSUE TITLE
Overlay event pauses timer events until removed

### ISSUE THREAD

**Issue by Polyducks** [chrismaltby/gb-studio#353]
Reported by @krümel (crumb) and tested/reproduced by Polyducks.

**Describe the bug**
'Overlay' events pause all timer events. If you have set a timer event and an overlay appears, it stops all timer events until the overlay is hidden. 

**To Reproduce**
1. Create new file
2. Create new scene
3. Create new actor
4. Reproduce code below

```
timer: set timer script
(countdown time in seconds: 0.5){
    if ($00$==true){
        $00$=false;
        actor_1(x=2, y=1)
    }else{
        $00$=true;
        actor_1(x=0, y=1)
    }
}
Overlay: show
black (x=0, y=4)
```

To see how the timer resumes when the overlay is hidden again, use Overlay:hide at the end of the above script.

**Expected behavior**
Unsure. Perhaps the overlay does not need to interrupt timer events - but if the overlay is computationally expensive it might make sense to pause all timer events. If so, this should be included in the documentation for events which interupt timer events (such as loop forever, multiple choice menus and overlay events).

**Platform (please complete the following information):**
 - OS: Windows 8.1
 - App version 1.2

**Additional context**
The same is true of multiple choice options and loop forever events - I expect this is by design to free up processing time. When the multiple choice menu is exited, or the loop is ended with stop script, the timer resumes.

**Comment by RichardULZ** [comment]
This can be closed now. :)
