### ISSUE TITLE
Text Speed changes after Choice event BUG

### ISSUE THREAD

**Issue by dyvap** [chrismaltby/gb-studio#361]
When i use the Multiple Choice event, or the Display Menu event, the speed of the text increases drasticaly.

**Comment by RichardULZ** [comment]
Fixed in #346
Please confirm in a dev build and close this issue.

**Comment by dyvap** [comment]
Thanks I will try it

**Comment by RichardULZ** [comment]
Please close this now that 1.2.1 is out.
