### ISSUE TITLE
German documentation

### ISSUE THREAD

**Issue by dataarchivist** [chrismaltby/gb-studio#362]
**Is your feature request related to a problem? Please describe.**
I wish to have a fully translated doc.

**Describe the solution you'd like**
If not planned, I would like to translate it.

**Describe alternatives you've considered**
See above. ;)

**Additional context**
Thanks a lot for this amazing prog, I love it!

**Comment by chrismaltby** [comment]
Hi @dataarchivist 
We do have German documentation available now at https://www.gbstudio.dev/de/docs/ big thanks to @locherunderscore for the effort translating everything
