### ISSUE TITLE
Variable Set Via Scene Init Not Correct?

### ISSUE THREAD

**Issue by SetsuneW** [chrismaltby/gb-studio#365]
**Describe the bug**
A strange bug I ran into while coding an elevator. During a room's init, I set the "Current Floor" to make sure it would know if it actually changed floors or not in a separate scene. However, I was getting an unexpected value that made no sense. I tried multiple solutions, but it seemed like the only fix, unless it was user error, was to move the Variable setting from the Initialization of the scene, to the trigger that switched to the Elevator scene. Same single line of code, everything worked fine.

**To Reproduce**
I streamed me struggling with (and solving) the process, it's the first 25 minutes of this video:
https://picarto.tv/videopopout/Setsune_2019.12.21.09.20.33_nsfw.flv
Or go to https://picarto.tv/setsune , click on Videos, and choose the 2019-12-21 video. There is some mild suggestive graffiti on the elevator doors, to warn you, but no other graphic content.

**Expected behavior**
On initialization (loading into the room), I expected it to set the Current Floor to 1. But instead it was consistently setting it to an improper value. I really did think it was User Error until I fixed it with the small change, and it might still have been.

**Screenshots**
See Video Link Above

**Platform (please complete the following information):**
 - OS: Windows 10 Home 1909
 - App version: Auto-Build of Commit 6231cce

**Additional context**
This MAY relate to processing Switch statement values out of numerical order (I originally started with 6-1-2-3-4-5 due to the floor ordering, with "0" being used to cancel out of the elevator), but the bug did not correct itself when I changed this to 1-2-3-4-5-6, only when I changed the variable to be set on Trigger, not Scene Initiation did it suddenly start working.

**Comment by RichardULZ** [comment]
Tried my best but can't reproduce this, I don't think i can test this without a known broken example project zip.

It did look like, as you say, setting your variable in the scene Initialization was different to setting it on a trigger in the same room, but that seems specific to your setup.

When trying to find a problem with variables, I usually draw text with $20$ or the variable to test in places where something may be going wrong.
For faster debugging, the P key will change your start position to anywhere on any map, unless you have variables to set up.

For Gameplay, i'd recommend adding a last option with cancel, just in case people don't know about B.

In future streams, i'd turn down the game audio, and turn up your voice, those crash noises are loud...

**Comment by chrismaltby** [comment]
I've pieced together an image of the full script used from screenshots of the stream, nothing jumps out as being obviously wrong, but I'm going to try recreating this in a project and see if I can reproduce the issue.

![elevator_script](https://user-images.githubusercontent.com/16776042/71322148-4fd48200-24bc-11ea-96fe-dbb01b62e709.png)

**Comment by RichardULZ** [comment]
AHAAAA!
23 minutes dead, the trigger was always setting the room to 5, then you change it to 1 and it starts working, the poor scene init was being over written when you walked in. 
Problem solved, it was 3am brain. ;)

 ![image](https://user-images.githubusercontent.com/34431457/71322408-20f5f480-252c-11ea-9db7-0942a73548a3.png)

**Comment by SetsuneW** [comment]
That's weird, I thought I didn't add that trigger until later on... urgh, user error, of course. Sorry for the trouble. And noted about the mic issue, Windows had reset my recording levels.
