### ISSUE TITLE
using [] in creating a project 

### ISSUE THREAD

**Issue by Veund** [chrismaltby/gb-studio#368]
if you use [] in the name of a project it wont let you add scenes making it impossible to make a project, i haven't tried other special characters

windows 7 64 bit 

gb studio 1.2 release

**Comment by thomas-alrek** [comment]
Maybe something like this could be used to validate the input?
https://www.npmjs.com/package/path-validation

**Comment by chrismaltby** [comment]
I've just pushed a fix for this on the dev build.

@thomas-alrek thanks for the module. I already had a `stripInvalidFilenameCharacters` function but it was missing a few characters, I've used the list of characters from there to make this fix in #371
