### ISSUE TITLE
Crash probably linked to Invoke Script command

### ISSUE THREAD

**Issue by Atnik** [chrismaltby/gb-studio#369]
I've run into a strange bug, which I don't understand myself, so I've attached the project below.

When you run the game, a battle sequence starts, but once the character Hugo finishes his move, the game crashes. This only happens with this character and I've checked the script several times, but it should work like the other characters.
But when you copy the script of the actor Hugo into the "Battle Loop" part in the scene init script it works again (at least it did after I removed the "If Variable has Flag" command at the start of the character script and added it again).

Before trying to find a solution, I got crashes that looked like this:
![grafik](https://user-images.githubusercontent.com/9643886/71745967-072da900-2e6c-11ea-9fbb-74d63b0681a7.png)

But now the game just stops without messing up the graphics.

Here's the project: [Dropbox](https://www.dropbox.com/sh/387nw3mx5dnlrdl/AAAc8e5uuodBLpVio4dzpwZBa?dl=0)
If you go to the scene init script and disable the invoke script command labeled Hugo and enable the one below, you can see that the same script works in the main script.

OS Version: Windows 7 64bit
GB Studio 1.2 (also happens in the dev build)

I know this is all super vague, but I hope it still helps to find the bug.

**Comment by RichardULZ** [comment]
A minor oversight with **Invoke actor**, nothing to do with labels fortunately.

To return after an actor was invoked, we stored up too 8 last `script pointers`,
Later we also stored the `start script pointers`, as that's used as an offset for IF or Switch events,
But i didn't think about actor scripts that might be so long they are in another bank,

So while invoking actor used the standard *start this script* function, which set the `script ptr`, `start ptr`, and `script bank`, we never stored the previous `script bank`s to reload, thus on return, loading garbage data from the new bank, and crashing.

It was lucky it happened with a long script to give me a lead, as it could just as easily happen somewhere where we randomly ran out of space and switched banks, and i would have been stuck digging through labels.


On a different note, the BANKED_DATA_TOO_LARGE warning is pretty vague, should probably error with what script is too large? You can reproduce this with this project file by copying all the actor scripts back into the start script.

**Comment by RichardULZ** [comment]
Added some more tests for BANKED_DATA_TOO_LARGE, now tells you by how much, what script, and to try splitting with invoke actors instead.

**Comment by RichardULZ** [comment]
Merged! Try out the dev build in the github readme and close this issue please.

**Comment by Atnik** [comment]
Tested it and everything worked! Thanks a lot for the help! :)
