### ISSUE TITLE
Possibly wrote twice at addr AKA Too much music in same bank

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#388]
**Describe the bug**
Too much music in one bank, music is only stored in banks 16 to 23, and then looped over with no regards for if they will fit.

**To Reproduce**
1. Add and use Tons of reasonably complex music, up to 40 tracks
2. Try to compile
3. Watch it recycle banks 16 - 23 after 8 tracks
4. If songs were too long/complex to fit in the same looped bank, you should see `Wrote twice at addr` error and failed compile.

Projects on discord under additional context.

**Expected behavior**
Wrote twice at Addr error also mentions "Possibly too much music data".
Music is compressed into banks in sequence, so space is not wasted or overflowed, and banks are expanded beyond 16-23 if required, or lower if not required. 
Extra: 
Music keeps at least some of the original file name for debug/identification purposes instead of random only.
Mod2GBT checks if there are unused patterns from trackers like milkytracker and warns? 
(Mod2GBT update, latest mod2gbt is smaller in console logs too, will look into this)

**Screenshots**
![image](https://user-images.githubusercontent.com/34431457/73147217-5c7f7200-411b-11ea-8de1-b2911973461a.png)
From Skittles REPRODUCIBLE PROJECT part 2

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - App version [1.2.1]

**Additional context**
#267 **Possibly wrote twice at addr**
#147 Music with space in their name (unique ids, too many tracks, not as related)

**User Skittles with the bug / project, part 1,**
https://discordapp.com/channels/554713715442712616/570925559346102273/668196313854378056
The SFX hurt secretly had 17 patterns with data, despite only using pattern 3, this was going over the bank limit after combining, milkytracker did not remove the data but openMPT cleaned it out and got the project working again...

**User Skittles WITH REPRODUCIBLE PROJECT part 2**
https://discordapp.com/channels/554713715442712616/570925559346102273/668615020485148692
This is directly related, but fixed with openMPT on all songs, which removed enough unused patterns in some songs, to fit in the banks again.

**lavallur user with the bug.**
https://discordapp.com/channels/554713715442712616/585023554085715979/670435940925308947
They are using OpenMPT and have hit the limit, therefore cleaning is not a sustainable solution.

**Comment by RichardULZ** [comment]
I've been thinking about how to tackle this problem, the easiest solution is simply exposing https://github.com/chrismaltby/gb-studio/blob/cc7506d940dfae4e2da0510a1e86990611ade5d0/src/lib/compiler/compileData.js#L46 in the settings page and, since the error is generated by sdcc, searching for `Possibly wrote twice at addr` and appending a `Try to Increase Music Banks` hint.

Finding out what size songs are going to be would let you fit more songs into same size carts, but would probably take too long to do, i guess you would compile them with the same bank number and then patch the new bank number afterwards.

The new Mod2GBT seems to run faster, and log less, so that will be a bonus.

**Comment by chrismaltby** [comment]
Ah I was hoping 8 music banks would be enough for anyone :D

Thanks for looking into this @RichardULZ 

Rather than expose the NUM_MUSIC_BANKS value directly I think I'd prefer to have it try to pack them into the smallest amount of banks automatically, like you say probably a little awkward to do, but it should be possible to read the compiled c data in, calculate how much space it will take in a bank and if it doesn't fit increment the `#pragma bank=N` line. I can have a look at this as part of the updates I'm working on.

On a related point I've been thinking about making the compiler scale the size of the ROM up and down based on the content, currently it's just fixed at 1MB, but I believe we could auto scale up to 8MB if you have a lot of content.

While I'm still working on the engine updates it might take a while to get to this though. If enough people are asking, maybe we go with your suggestion short term and can make this automatic later.

**Comment by Skittles666** [comment]
i have no idea what im doing or anything. coding is like trying to chip away at a brick wall for me lol help me pls ;-;
gb version 1.2.1
os windows 10 pro
![screenshot](https://user-images.githubusercontent.com/60951819/77491007-c6ee1f00-6df9-11ea-876b-431546593f0f.png)

**Comment by RichardULZ** [comment]
It was indeed a too much music, to few banks issue. 
Link to their project file. https://discordapp.com/channels/554713715442712616/570925559346102273/691429723665858590

I created a windows build of my new gbt wip branch, and upped the music banks to 16.
https://discordapp.com/channels/554713715442712616/570925559346102273/692182458485178381
 https://drive.google.com/file/d/1u0qWurXW1t7J5zm2GF6h9RLMpblCbDhp/view?usp=sharing

I think exposing this to the options would be a good stopgap solution for now, and will work even if we don't change how music is sardine packed.

In other news,
Superdisk is investigating a converter for GBT mod files to their new, more advanced player format hUGE Tracker (uses a lot less data too, since you can reuse a channels pattern)
Not so sure what to do with my GBT upgrades right now, but might try to get them in anyway.

**Comment by pau-tomas** [comment]
I can take a stab at exposing the max num banks in to settings (maybe in an `Expert` section*) if that's ok for Chris as a quick solution while he works on the current refactor.

* calling it `advance` might confuse people into thinking those are options for GBA!

**Comment by RichardULZ** [comment]
Working on **modifying music bank allocation**, just fs.fileread and write to change the bank, since music compile happens after bank data ptrs generation, will have to read and write that file with new banks after music compile too.

Already fitting more songs in less banks without issue, most of these are caused by a few big songs, and lots of little songs.
Song length is currently an estimate by taking the compiled file length divided by 5, so it will always over estimate, but that's not a bad thing as there's more data that gets bundled upon lcc link.

Related to the topic, @chrismaltby 
At some point we swapped to **uuid** music names, but it shouldn't be any problem if naming starts from 101 right? The random names are way harder to debug, as files are processed alphabetically.
https://github.com/chrismaltby/gb-studio/commit/2f7d8f31de90f138bb12cbeaa85910fb95152667
```
dataName: 'music_${uuid().replace(/-.*/, "")}${index}'
```
```
dataName: (`music_track_`+ (index + 101))
```

**Comment by RichardULZ** [comment]
Wohoo! This bug is fixed! 🎉 (tested on at least 3 projects with the same issue before)
