### ISSUE TITLE
[Request] Tile based movement

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#39]
Is it possible to implement tile based movement (like e.g Pokemon Red & Blue)?

**Comment by Level0gamedev** [comment]
I would love this to be implemented, even as an option.
I would also prefer have an option for the length of the tile - either full 16px, or by 8px.

**Comment by AsherGomez** [comment]
Same.

**Comment by Level0gamedev** [comment]
@AsherGomez - already requested in #10 ;)

**Comment by AsherGomez** [comment]
Ah, thanks.

**Comment by WAUthethird** [comment]
Requested on Reddit: [https://www.reddit.com/r/gbstudio/comments/bqlm56/is_there_a_way_to_make_the_player_walk_one_whole/](https://www.reddit.com/r/gbstudio/comments/bqlm56/is_there_a_way_to_make_the_player_walk_one_whole/)
