### ISSUE TITLE
Can't export or run on Linux

### ISSUE THREAD

**Issue by terminaltux** [chrismaltby/gb-studio#398]
Hello,

**Describe the bug**
While trying to Run or Export ROM my project on Fedora 31, GB studio just hangs.

When I choose Run or Export ROM, the Build & Run screen will say "Done!" at the bottom, but nothing happens. The Run icon in the top right keeps turning.

After a fresh install of GB Studio, it may Run or Export the project successfully once. But, further attempts fail.

**To reproduce**
1. Start a new Sample Project on a Fedora computer and save it.
2. Try to Run or Export the project
3. If successful, close GB Studio, launch again, and try again.

**Expected behaviour**
GB Studio will export a ROM file, or load the emulator to run the game.

**Platform**
- OS: Fedora 31 (Linux)
- App Version: 1.2.1

**Additional Information**

1. Often, on the Build & Run screen, GB Studio stops at "Copy code bank_7.c".
2. It's possible that Ubuntu works, but Fedora doesn't because Fedora has a newer version of **gcc** (7.5.0 vs 9.3.1) and **make** (4.1 vs 4.2.1). After a fresh install of Fedora, GB Studio worked, but after updating the OS, it stopped working.
3. On an up-to-date Ubuntu LTS 18.04.4 computer, GB Studio will fail with the error:

```
/bin/sh: 1: make: not found
127
```

This can be resolved in Ubuntu by installing gcc and make, ie:
`sudo apt install gcc make`

4. I tried installing the development tools in Fedora, but it didn't resolve the issue, ie:
`sudo dnf install @development-tools`

**Comment by zdurgan** [comment]
I attempted to reproduce your issue on a fresh install of Fedora 31, and after updating and installing the developer tools, as you mention, the Sample Project runs even after closing and launching GB Studio a few times. Are you still having this issue and if you are can you provide some additional information?

**Comment by terminaltux** [comment]
Thanks for looking into it @zdurgan . Unfortunately, yes I am still having this problem.

I think the real issue is, I haven't been able to find a way to get an error message in Fedora. At least with Ubuntu, it displayed an error in GB Studio, so I could find the solution. In Fedora, it just hangs. I've tried running GB Studio from the command line with:
```
gb-studio --help
gb-studio -help
man gb-studio
```
but it didn't provide any info other than:
```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
No language pack for user setting, falling back to en
Add a language pack by making the file src/lang/en-GB.json
```
Did you install Fedora in a Virtual Machine, or on actual hardware? 
Did you use Gnome Software to install the rpm package, or via the command line?
The stable version, or a more recent build?

**Comment by zdurgan** [comment]
I am currently running Fedora in a Virtual Machine.
I am using the 1.2.1 Fedora rpm package downloadable on the itch.io website.

I have tried installing GB Studio with Gnome Software, rpm, yum, and dnf then running through your reproduce steps, and I can't seem to get the hanging error and the game runs and exports as expected. 
I followed these [instructions](https://www.gbstudio.dev/docs/installation/), but replacing the package name with the current version when first trying to install with rpm.

I also tried Ubuntu and get the same error as you until I install make. When I deliberately uninstall make on Fedora using

`
sudo rpm -e --nodeps make
`

then run or export, neither hang and I get the same error as you get on Ubuntu.

**Comment by terminaltux** [comment]
I've uninstalled and reinstalled GB Studio many times, both according to the instructions you linked to and via Gnome Software, unfortunately the most I get is one successful "run" or "build" before it starts to freeze again.

I was able to reproduce the error in a Fedora 31 Virtual Machine, but only once.

1. Log out
2. On the login screen click on your user
3. Click on the small gear icon that appears below the user and select "Gnome on Xorg"
4. Type in your password and login
5. Launch GB Studio and try the Export ROM and the Run functions

The freezing only happened once in the Virtual Machine, but is constant on real hardware. It doesn't seem to matter if I choose a Gnome (Wayland) session or Xorg. Perhaps it's related to libxscrnsaver or the display driver?

I appreciate you taking the time to look into this. I understand you can't fix the issue if you can't reproduce it.

My current work around is to run GB Studio in an Ubuntu 18.04 virtual machine and sync my files via Mega.

**Comment by asiekierka** [comment]
If your reproduction is semi-consistent, as it was for me, could you please test the bugfix in https://github.com/chrismaltby/gb-studio/pull/420 ?

**Comment by terminaltux** [comment]
> If your reproduction is semi-consistent, as it was for me, could you please test the bugfix in #420 ? At least for the "Often, on the Build & Run screen, GB Studio stops at "Copy code bank_7.c"." part of the problem.

I tried the Development Build packages available for download, as well as the yarn method of cloning the Git repository (I am new to testing dev builds, so I am not sure about the process). 

On my Fedora 31 desktop: 
1. The development build/package has been slightly more successful than previous builds. It will still hang, but I was actually able to get a few successful runs & builds with it.
2. The yarn/git version either hangs, or launches the emulator with nothing but a black screen.

On my Fedora 32 desktop:
1. The development build/package was inconsistent. It successfully built the ROM, but would hang on further attempts. The emulator would either fail to launch, or bring up a black/white screen.
2. The yarn/git version would always get stuck at "Copy cod bank_7.c"

**Comment by terminaltux** [comment]
This bug is no longer an issue with the recent versions of GB Studio and updates to Fedora.
