### ISSUE TITLE
I want to use more colors.

### ISSUE THREAD

**Issue by wrt0302** [chrismaltby/gb-studio#4]
The sentence is awkward because I used Google Translator. please understand.

I would like to create a gba or gbc game with colorful colors.
This project unfortunately only supports gb, and appears to be limited to four colors.

Is it possible to create a game with lots of colors through a program that ignores documents on the official homepage and arbitrarily puts a lot of colors into the game and then converts the output gb file to gba/gbc? If not, do you plan to support rom file output for gba/gbc?

I've been waiting for these tools to come out into the world.
The dream finally came true. Thank you.

**Comment by AlmondWhite** [comment]
This suite is specifically designed for GB, thus the color formats available are only those supported by the actual platform itself. 

Considering the capabilities offered by GB Studio and it possesing an MIT license, I would imagine it won't be long before someone forks it for GBC or GBA, but for the meantime this is a GB dedicated platform.

**Comment by ISSOtm** [comment]
> I would like to create a gba or gbc game with colorful colors.
> This project unfortunately only supports gb, and appears to be limited to four colors.
> 
> Is it possible to create a game with lots of colors through a program that ignores documents on the official homepage and arbitrarily puts a lot of colors into the game and then converts the output gb file to gba/gbc? If not, do you plan to support rom file output for gba/gbc?

Colorization of a Game Boy game is impossible to do automatically (the most that can be achieved is what the Game Boy Color boot ROM does by default, ie. one palette for the background and two for the sprites). Even given the source code.
You'd need to design the game and the code specifically for the GBC.

Note also that GBA dev is **vastly** different from GB dev. (GB(C) dev is mainly done in ASM, GBA dev is rather done in C; and there much more.)

> I've been waiting for these tools to come out into the world.
> The dream finally came true. Thank you.

I would much rather recommend learning how to program the Game Boy itself -- this tool won't get you far, and GBDK will just peg the console *hard*. A good starting place is [awesome-gbdev](https://github.com/gbdev/awesome-gbdev).

**Comment by pinobatch** [comment]
To make this issue doable, can we restrict its scope to just support for just assigning particular GBC palettes to map objects and sprites?

**Comment by Lokathor** [comment]
While keeping the project to targeting Game Boy only, it would be possible for the games to have Super Game Boy enhancements programmed in, which would include _limited_ control of the colors.

**Comment by chrismaltby** [comment]
The latest dev builds now include a color palette selector created by @fydo allowing you to set your own colors (I think using the CGB enhancements that @Lokathor mentions)
