### ISSUE TITLE
[Request] Option select UI in the text area

### ISSUE THREAD

**Issue by mortocks** [chrismaltby/gb-studio#41]
It would be amazing to have a method of adding selection options to the text windows to give the player the ability to choose an option (that could be used in scripting to change a variable). 

Also the ability for a "next" button to link multiple text windows together in sequence or in a logic tree would be very helpful. 

See example from Pokemon UI in the bottom right corner

![image](https://user-images.githubusercontent.com/314196/56622489-b37b8680-6673-11e9-9def-74f875b93355.png)

**Comment by chrismaltby** [comment]
Have you seen the “Multiple Choice” event? It doesn’t do everything you want here but does let you make decision trees by setting variables. I’ve just seen a game made using it by https://twitter.com/mepstein01 at http://zeldamath.surge.sh/

**Comment by mortocks** [comment]
🤦‍♂️ Oh that’s perfect!

**Comment by ISSOtm** [comment]
If it's what you were looking for, can you please close the issue?

**Comment by mortocks** [comment]
👍
