### ISSUE TITLE
Sprites not displaying properly 

### ISSUE THREAD

**Issue by tofa2403** [chrismaltby/gb-studio#419]
Sprites are not displaying properly since I had an error occur involving bank 59, it said something about the initialiser, unfortunately I did not write it down, I restarted GB Studio and the error didn't appear when I compiled the game, however sprites were appearing incorrectly, either facing the wrong way or as a completely different sprite, when interacting with certain sprites they changed again to a completely different sprite. 

**To Reproduce**
compile the game and start in scene 351, the issue was also occuring in scene 346, other sprites in different scenes were also effected but had been fine days before.

**Expected behavior**
I expected the sprites to display properly, as you can see in the screen shots, in the project view, the sprite is a lady sitting down at the table, in game view the sprite is completely messed up

**Screenshots**

**Platform (please complete the following information):**
WINDOWS 10
![bug](https://user-images.githubusercontent.com/64530257/80586725-48465c00-8a0d-11ea-9425-8cbfa0e3c154.jpg)
![bug2](https://user-images.githubusercontent.com/64530257/80586730-4a101f80-8a0d-11ea-8ebe-7194974fe616.jpg)

**Additional context**

**Comment by tofa2403** [comment]
I have also noticed that some triggers are pointing to the completely wrong background now too

**Comment by tofa2403** [comment]
I have done some tests and the problem seems to be with the number of unique backgrounds that are included in the game, is there a way to increase the limit ?

**Comment by tofa2403** [comment]
I have also discovered that the sprite problem is not related to the background issue, there seems to be a limit on the number of unique sprites too, if I add a new unique sprite, it breaks the game but if I change that sprite to an existing one it is fixed, would be great if this limit can be increased too

**Comment by chrismaltby** [comment]
Hi @tofa2403 you were right that these were two different issues you hit at around the same time! There was a fixed limit of 256 unique sprites and while you should have been able to have over 256 unique backgrounds there was a bug that was causing some backgrounds to not load correctly once that amount was reached.

I've got a fix for both of these issues in #421 but I just need to do some more testing before I can merge it into the development build.

Here's how it's looking for me now:

<img width="592" alt="Screenshot 2020-05-02 at 21 42 32" src="https://user-images.githubusercontent.com/16776042/80892447-17428180-8cc2-11ea-9418-6f9e83e395b3.png">
<img width="548" alt="Screenshot 2020-05-02 at 21 56 18" src="https://user-images.githubusercontent.com/16776042/80892449-1a3d7200-8cc2-11ea-8a38-d3506a0912b6.png">

**Comment by chrismaltby** [comment]
Hi @tofa2403 these updates are now in the latest development builds. Do you want to try downloading the latest version and see if this fixes the issues for you?

**Comment by tofa2403** [comment]
@chrismaltby works perfectly ! Thanks again for your help !
