### ISSUE TITLE
Upgrade gbdk to a new updated version called gbdk-2020

### ISSUE THREAD

**Issue by CelestialAmber** [chrismaltby/gb-studio#424]
**Is your feature request related to a problem? Please describe.**
I discovered that someone has been working on an updated version of gbdk  (https://github.com/Zal0/gbdk-2020), which already has made numerous advances, such as upgrading to the latest version of sdcc (the compiler gbdk uses). I thought that it may be a good idea to consider switching to this newer version of gbdk while comparing the advantages/disadvantages it has and deciding based off this whether it would be a good idea.

**Describe the solution you'd like**
Update GB Studio to use this updated version of gbdk.

**Describe alternatives you've considered**
ISSOtm previously created an issue suggesting switching to using RGBDS instead, which could potentially still be a good alternative to this option. (https://github.com/chrismaltby/gb-studio/issues/78)

**Additional context**
N/A

**Comment by CelestialAmber** [comment]
The above issue is more active, so I’ll close this one.

**Comment by maxoakland** [comment]
> The above issue is more active, so I’ll close this one.

That issue was closed
