### ISSUE TITLE
Scenes and sprites aren't displaying.

### ISSUE THREAD

**Issue by rockinraccoongames** [chrismaltby/gb-studio#434]
I have come across a strange bug, in that my project scenes and sprites do not display whatsoever.
I have tried different things, such as multiple installations and trying both 32-bit and 64-bit, installer and standalone variants, and yet any project file I create, there is simply no display of my assets, and thus I have to guess where my collisions are going. Even in the sections other than the main editor, the assets aren't visible, and yet when the game is run through the built-in emulator, they are displayed.

I have no idea how I can help reproduce this error, as I haven't seen any other case of this, I don't know if it is my current computer :/. This has only happened recently, and when I updated to 1.2.1, it was initially fine, with that only happening when I wasn't connected to the internet, however it now happens regardless of an internet connection or not, and I am confused as to why. Again, it could be an error with the hardware I'm running, but this isn't a long-standing issue with the program, and I am hoping there is some solution to my issue.

Screenshots:
![gbstudio_error1](https://user-images.githubusercontent.com/66851035/84551453-9b4a4900-ad05-11ea-99cf-cd73a6e15416.PNG)
![gbstudio_error2](https://user-images.githubusercontent.com/66851035/84551454-9c7b7600-ad05-11ea-853d-ce35061d4746.PNG)
![gbstudio_error3](https://user-images.githubusercontent.com/66851035/84551456-9c7b7600-ad05-11ea-95c7-21e2d24a356e.PNG)

The OS and Application Version are as follows:
 - OS: Windows 10
 - App version 1.2.1

**Comment by RichardULZ** [comment]
Looks like missing files, is your project in a drop box and synced on demand? 
Try copying the project folder and opening that/checking the assets inside.
If the assets look fine outside of gbstudio, we'd need a zip of your project folder to test.

**Comment by rockinraccoongames** [comment]
> Looks like missing files, is your project in a drop box and synced on demand?
> Try copying the project folder and opening that/checking the assets inside.
> If the assets look fine outside of gbstudio, we'd need a zip of your project folder to test.

Thanks for commenting! I saved my project folder into a 'Game Projects' folder, and the assets are present are viewable perfectly fine outside of gbstudio, previews and in Photos.
![gbstudio_error4](https://user-images.githubusercontent.com/66851035/84774594-f619c400-afd5-11ea-888d-0b8f98ceeb0b.PNG)
![gbstudio_error7](https://user-images.githubusercontent.com/66851035/84775448-24e46a00-afd7-11ea-9ae3-1d271e7ca1de.PNG)
As mentioned in my last statement, when running the game in the built-in emulator, everything is visible as it should be too, this display error is just in the editor itself:
![gbstudio_error5](https://user-images.githubusercontent.com/66851035/84775570-4c3b3700-afd7-11ea-9b4e-a70d6324042a.PNG)
![gbstudio_error6](https://user-images.githubusercontent.com/66851035/84775571-4cd3cd80-afd7-11ea-8aae-e2a317243c30.PNG)
So concerning the backgrounds and sprite assets, they're all viewable outside of the editor. I'll upload my project folder for you to test and try and find a solution. And thanks again for seeing to this issue :)
[Jerry.zip](https://github.com/chrismaltby/gb-studio/files/4786739/Jerry.zip)

**Comment by rockinraccoongames** [comment]
A quick update:

I started a new project file, and the editor is now refusing to show that I have any sprites/background that aren't pre-made.

Here are the folders, to which I was starting a Legend of Zelda-inspired game. First is the Sprites folder:
![gbstudio_error9](https://user-images.githubusercontent.com/66851035/85213186-e6daa380-b352-11ea-9f22-d8489e156d76.PNG)
Next is from the Background folder:
![gbstudio_error8](https://user-images.githubusercontent.com/66851035/85213198-02de4500-b353-11ea-85b8-10b1762a1f92.PNG)
And then here are the respective sections in the actual program:
![gbstudio_error11](https://user-images.githubusercontent.com/66851035/85213208-26a18b00-b353-11ea-959d-97e0700d04df.PNG)
![gbstudio_error10](https://user-images.githubusercontent.com/66851035/85213209-2a351200-b353-11ea-9cae-5e4924f9b6fa.PNG)

**Comment by RichardULZ** [comment]
That is very odd, i've just opened your jerry.zip project and everything shows fine in the editor, tested on 1.2.1 and a dev build.
Perhaps try grab a dev build from https://github.com/chrismaltby/gb-studio#development-builds just to double check.

Also, curious if you used a zip or the installer for gbstudio, if they were working earlier, perhaps it's somehow corrupted and needs re downloading?

All your files are being compressed on disk (the 2 arrows on the icons), but i wouldn't expect that to be the issue, perhaps something more odd, like free disk space, or simply too long of a file path/weird characters in your user?

They *Shouldn't* be the issue, but you never know... i'd try copying the project folder somewhere lower level and opening it from there if a fresh copy doesn't work.

**Comment by rockinraccoongames** [comment]
> That is very odd, i've just opened your jerry.zip project and everything shows fine in the editor, tested on 1.2.1 and a dev build.
> Perhaps try grab a dev build from https://github.com/chrismaltby/gb-studio#development-builds just to double check.
> 
> Also, curious if you used a zip or the installer for gbstudio, if they were working earlier, perhaps it's somehow corrupted and needs re downloading?
> 
> All your files are being compressed on disk (the 2 arrows on the icons), but i wouldn't expect that to be the issue, perhaps something more odd, like free disk space, or simply too long of a file path/weird characters in your user?
> 
> They _Shouldn't_ be the issue, but you never know... i'd try copying the project folder somewhere lower level and opening it from there if a fresh copy doesn't work.

I legit moved it to the desktop where the shortcut is and it seems to be working again! I'm so confused, but thank you Richard for your help and advice...although I can't believe something so minor fixed my problem |:/

**Comment by RichardULZ** [comment]
So you moved the project to the desktop and that solved the editor issues? 
Would you be able to experiment with moving it back or renaming folders to reproduce the issue?
Seems like the [ ] characters or length of file path might be the issue, can't be username if it worked on the desktop, if we can find the cause we might be able to add a warning.

**Comment by rockinraccoongames** [comment]
I will try experimenting with it a little, I'll let you know the results :)

**Comment by rockinraccoongames** [comment]
Jeez, I haven't commented in a while xD
Yeah, as it seems, it was a folder structure and naming issue. Thanks for the advice @RichardULZ
