### ISSUE TITLE
Cant run Tests

### ISSUE THREAD

**Issue by 1MarioFan** [chrismaltby/gb-studio#436]
I keep trying to run test for this games i wanna make but everytime i do, i get this message
![truble](https://user-images.githubusercontent.com/67701754/86264200-35c4dc00-bb90-11ea-8f7b-e19290181d01.PNG)
Can you help my with my issues? heres a zip of my game
[Garfield Gameboyd - Copy.zip](https://github.com/chrismaltby/gb-studio/files/4858886/Garfield.Gameboyd.-.Copy.zip)

**Comment by 1MarioFan** [comment]
i forgot 1 thing. its unfinished.

**Comment by RichardULZ** [comment]
We finally diagnosed on gbstudio discord this was due to restrictions on their windows 10 computer that did not allow the use of cmd or command prompt, possibly set by a school.
