### ISSUE TITLE
Bug. getting error "TypeError: Cannot read property 'plugin' of undefined"

### ISSUE THREAD

**Issue by lynxieles** [chrismaltby/gb-studio#447]
When I try to compile a game to test some of the new features I'm getting an error that prevents it from finishing.
I cannot find any source of the issue and I'm unsure what to look for.
I have copied the code where it fails.

> Preparing variables...
> Preparing strings...
> Preparing images...
> Preparing ui...
> Preparing sprites...
> TypeError: Cannot read property 'plugin' of undefined
> 
> Warnings:
> - TypeError: Cannot read property 'plugin' of undefined

Edit: updating with the tracker template
[SCP.zip](https://github.com/chrismaltby/gb-studio/files/5114532/SCP.zip)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem:**
open a project I made in the 1.2.1 version in beta 2.0.
does not occur with a new project made in 2.0.
**What is the expected behavior?**
No error while building the project.

**What is the motivation / use case for changing the behavior?**
Being able to run my project

**Please tell us about your environment:**
Mac catalina version 10.15.4
GB Studio Beta 2.0

Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I have attached the project file for RichardULZ. I will likely remove it at a later date.

**Comment by lynxieles** [comment]
I have updated the issue with a bit more detail and uploaded a project zip as requested by RichardULZ.

**Comment by pau-tomas** [comment]
The issue is that the player spritesheet isn't assigned in the World Editor. Selecting the right sheet should make things work again.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/54246642/90985880-a4ae2800-e576-11ea-9d46-12f8301e7c40.png">

I still don't know why this happened, the 1.2 version of @lynxieles  project will be very useful for that. Thanks @lynxieles !

**Comment by lynxieles** [comment]
I'm not sure myself. It got wonky after I accidentally deleted a file I think. I thought I fixed the sprite sheet issue in the previous version but I must have missed one. That totally fixed it. here's the old one if you want to look at it. thank you so much for the help.
[SCP.zip](https://github.com/chrismaltby/gb-studio/files/5114668/SCP.zip)

**Comment by pau-tomas** [comment]
Interesting, the 1.2 project didn't have a Sprite Sheet selected for the Player but it was compiling fine (and, I guess, just selecting an arbitrary sheet? 🤷 ). I don't think we should support that case, but instead add a more clear warning to the compiler: 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/54246642/90986355-25baee80-e57a-11ea-9324-98bd316ad136.png">

**Comment by lynxieles** [comment]
Honestly in the old version I'd just manually set the sprite sheet myself so I really never noticed. I'm glad my mess up could help other people too.
