### ISSUE TITLE
[Position: Player] seems to calculate position incorrectly when camera is moving

### ISSUE THREAD

**Issue by Jeltr0n** [chrismaltby/gb-studio#453]
**Describe the bug**
When an actor is set to `move to Player Position X & Y `it seems to miscalculate the position when the camera is moving. 

**To Reproduce**
1. Make an actor have `Actor: Move To:` `X: Position: Player` `Y: Position: Player` as an update script
2. Move until the camera starts moving with you
3. See error: The actor will no longer follow the player properly and will overshoot the player

**Expected behavior**
The actor will continue to follow you without passing you

**Screenshots**
![follow error](https://user-images.githubusercontent.com/70062490/90956850-1ba0cf00-e458-11ea-8f44-e1baf14f8508.gif)

**Platform (please complete the following information):**
Windows 10
GBstudio 2.0 BETA

**Additional context**
-The scene was a 2d shooter scene when created but the bug persists when the mode is changed
-The scene is an ultrawide scene far exceeding the previous horizontal limitation of 256 pixels
-The scene has 230 unique tiles but does not display dialog
-I have attached the project file
-There is another actor in the scene with an update script

**Project File**
[Shooter experiment.zip](https://github.com/chrismaltby/gb-studio/files/5112390/Shooter.experiment.zip)

**Comment by RichardULZ** [comment]
This can be closed, as it was user error, moving actor that was pined to screen, to player world position.
