### ISSUE TITLE
[Beta] Migrating projects from 1.2.1 to 2.0.0 makes Actor: Push Away from Player react differently to collisions

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#465]
**Describe the bug**
I'm using the sample project to test this. In 2.0.0, a pushed actor using a migrated old project will only move 1 tile if it is within 2 tiles of hitting collision. This seems to be because the way that collision masks/actor origins work has been changed for 2.0.0 so the collision mask now makes more sense in relation to the background tile map.

Still, 2.0.0's migrated version of the 1.0 sample project makes pushed actors stop 1 space early from where they should be colliding, breaking most sliding puzzles such as the sample project's underground boulder puzzle.

**To Reproduce**
1. Create sample project in 1.2.1
2. Open 2.0.0 and load the project saved in 1.2.1
3. Click "migrate"
4. Run the project and try the boulder puzzle underground
5. The puzzle is incompletable, all boulders are trapped because they only move one tile before stopping.

**Expected behavior**
The boulder moves two tiles and then stops.

Here is what it looks like when all boulders are moved as far upwards as possible in 1.2.1's sample project:
![image](https://user-images.githubusercontent.com/47726614/91094337-847e7780-e60f-11ea-8c6f-007ab1fc5c8e.png)

And here's the editor window for underground in 1.2.1:
![image](https://user-images.githubusercontent.com/47726614/91094697-04a4dd00-e610-11ea-9ff8-95c91fe3bc81.png)

Here is what it looks like when all boulders are moved as far upwards as possible in 2.0.0 using the migrated sample project:
![image](https://user-images.githubusercontent.com/47726614/91094616-e2ab5a80-e60f-11ea-903e-491c476758e0.png)

And here's the editor window for underground in 2.0.0 Beta. The collision mask has not changed, but the behaviour surrounding them has.
![image](https://user-images.githubusercontent.com/47726614/91094560-d1624e00-e60f-11ea-83e5-8944cf8c6e81.png)

This does not apply to all Actors who use Push Away from Player, as this boulder works just fine in all directions:
![image](https://user-images.githubusercontent.com/47726614/91093848-d83c9100-e60e-11ea-9a10-7ef18118cef6.png)
It probably just has to do with how pushed actors see the collision mask.

**Platform:**
 - OS: Windows 10 64bit
 - App version 2.0.0 / 1.2.1

**My suggested fix:**
I notice that pushed actors and collision tiles are set up very differently in 2.0.0's native sample project, so I wonder if migrating should include bumping the collision masks up by one tile to compensate for the improved collision mask preview?
![image](https://user-images.githubusercontent.com/47726614/91095373-1dfa5900-e611-11ea-9a43-10a20841b179.png)

![image](https://user-images.githubusercontent.com/47726614/91095524-60bc3100-e611-11ea-9817-e8da655b4eed.png)

**Comment by RichardULZ** [comment]
I think this was noted in the changelog, and is intended, though perhaps migration needs a clearer message that push events use a 2x2 tile collision now during migration. 

Moving all collision will not fix the issue, they were 1x2 (same as player, very broken with other actors) and now 2x2.

**Comment by DeerTears** [comment]
Since we're in 3.0, I'll just close this issue about 1.0 to 2.0 migration
