### ISSUE TITLE
Issue with multiple shoot'em up scene in a row 

### ISSUE THREAD

**Issue by quentintamar** [chrismaltby/gb-studio#472]
When one shoot'em up scene start everything is fine, the auto scroll is working, 
but when you transport from one shoot scene to another there is no auto scroll. 
Even when you copy and paste the same first working scene, after the change there is no scroll.

**Comment by RichardULZ** [comment]
Are you setting the direction when you scene switch? This is required for shoot em up to know where to scroll.

Could try to make a warning about it but I'm not sure how.

**Comment by quentintamar** [comment]
It was indeed the problem  ! thanks ! i don't know why i didnt think about that,  its seems pretty logical now you said it :)

**Comment by RichardULZ** [comment]
Cool, good to hear it's working, please close this issue. 🙂
