### ISSUE TITLE
[Request] Animated background tiles

### ISSUE THREAD

**Issue by thomas-alrek** [chrismaltby/gb-studio#48]
Would it be technical possible to support animated tiles on the background layers? E.g for creating animated water?

**Comment by clsource** [comment]
I currently do not have much knowledge, but I believe this can be achieved by using sprites instead of backgrounds.

1 - Layer 1: Water
2 - Layer 2: Animated ripple effect.

**Comment by Lokathor** [comment]
that could work for just a few waves, but there's only 40 object slots and not much time during hblank.

a better plan is probably to just change the tile data at whatever position in tile memory every few frames

**Comment by HeyItsLollie** [comment]
GB Studio would definitely need a proper tile editor (or support for an existing tilemap format, for example: Tiled Map Editor's [TMX](https://doc.mapeditor.org/en/stable/reference/json-map-format/) or [JSON](https://doc.mapeditor.org/en/stable/reference/json-map-format/) map formats) in order for animated background tiles to be feasible _and_ user-friendly.

**Comment by arathron** [comment]
I was going to ask this same feature (animated tiles for background), like those used in zelda and pokemon.
With sprites only very few elements can be shown.  
I don't see why a tiled map editor would be needed, one can use an external one like Tiled.
Can this feature please be added? If not, why not? Is it technically too difficult?  Or is it just a matter of time?
Thanks.

**Comment by Ferk** [comment]
Support for tmx or json files from Tiled as backgrounds would also make it more convenient, so you don't have to export them to PNG when changed.
And when version controlling a GB project It would also make more sense to add the tmx/json files to git than the exported PNGs.
