### ISSUE TITLE
[Beta] "Enable Color Mode?" dialog can be hidden, appears to "freeze" the editor

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#492]
**Describe the bug**
Clicking on "Colorize" brings up the "Enable Color Mode?" dialog as expected. If you use Alt + Tab or click on the editor in the back, the dialog is temporarily hidden, but control is not fully restored to the editor. The editor is even able to keep track of all the requests to enable Colorize mode, resulting in a hilarious train of dialog boxes that keep popping up no matter how many times you accept/cancel the dialog.

**To Reproduce**
1. Create a project that does not have color mode enabled
2. Click on "Colorize"
3. Press Alt + Tab or click on the background window
4. Editor will appear to be frozen until the dialog is found again and resolved
5. The editor is also still receptive to further requests to enable colorize mode, stacks these requests and displays them after the current dialog is resolved

**Expected behavior**
Clicking the editor or attempting to do actions on the editor prevents me from hiding the dialog that's freezing the editor, making sure I take action on it before continuing. I expected something similar to the "Do you want to save the changes you made?" dialog when you try to close the editor with unsaved changes.

**Platform (please complete the following information):**
 - OS: Windows 10 64 bit
 - App version 2.0.0 Beta

**Additional context**
This is just an ease of use thing that will prevent headaches like I just experienced, when I was unsure if I wanted to enable color mode on my project. I hesitated to add color mode because I wasn't sure if adding it would kill compatibility with classic GB emulators/systems, which is a reassurance I'd appreciate also being added to the "Enable Color Mode?" dialogue if possible.

**Comment by chrismaltby** [comment]
Thanks for spotting this @DeerTears it's weird because macOS was treating that window as a modal and not allowing the main window to gain focus or accept clicks but I've found a fix which I've implemented in #493
I also improved the wording a little, hopefully should be clearer now!
