### ISSUE TITLE
Showcase section

### ISSUE THREAD

**Issue by cloudstudio** [chrismaltby/gb-studio#50]
Hey guys! I really love this!

It can be great to have a showcase or demos online, so we can check the games of the people.

Do you have something to show? comment here!

**Comment by chrismaltby** [comment]
Great idea we've now got a subreddit at https://www.reddit.com/r/gbstudio which I've linked from the README, needs adding to the site itself but that's a different repo.
https://github.com/chrismaltby/gb-studio-site
Would like to have a showcase page on the site too eventually, will maybe pick some every so often from the subreddit and discord and have a page linking off to them.
