### ISSUE TITLE
Add Search Hints to Events

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#509]
**Is your feature request related to a problem? Please describe.**

The event search is not very forgiving, it's easy to enter a search term for an event that you want, but sometimes no event name contains the term you searched for. Even if a search term accurately describes functionality that GB Studio already has, the event search gives no tips or suggestions on events you might have wanted. This presents an obstacle to new GBS users and also to experienced GBS users who are branching out to try new events.

![image](https://user-images.githubusercontent.com/47726614/91770097-6a0b4780-eb95-11ea-9030-153842133c30.png)
This blank search result screen is pretty common in my experience.

Trying to search for words like "teleport", "glide", "detach", "spritesheet", or "change sprite" returns no useful results, especially if the user doesn't look at their screen while they type, or they type too fast to see any hints along the way. In my experience I have very rarely scrolled through the entire list of events on the docs or in the editor to hunt for what I want because it's a lot of information to process.

**Describe the solution you'd like**

A new, optional String (or series of Strings) for the event data type, which could be pulled from the event search. If the entered text matched a word in an event's search hint, the corresponding event would display at the bottom of the normal search results.

**Example:** When the word "teleport" is searched, "Actor: Set Position" would have a matching search hint that would allow it to come up in results.

![image](https://user-images.githubusercontent.com/47726614/91770711-80fe6980-eb96-11ea-920d-f3ceb85e4bb4.png)

This would alleviate having to know **exact** words to access certain events. It may also result in fewer users asking about if certain features are possible even though they're already taking the effort to search for them.

Adding this feature would also mean the workload of adding a new thing to localize, if users in non-English languages find that the naming of certain events are also unexpected, vague or strange.

**Describe alternatives you've considered**
 
We could rename any misleading event names on an event-by-event basis to use more distinct and accessible language.
- "Actor: Set Position" could become "Actor: Teleport"
- "Actor: Move To" could become "Actor: Walk To"
- "Joypad Input: Remove Attached Script" could become "Joypad Input: Detach Script"

And then the docs would be updated accordingly to follow these name changes. I don't know if this would mean needing to re-translate any event names that would've been changed in English, but I figure this alt solution might be easier to implement than search hints.

**Comment by RichardULZ** [comment]
Second this, many people ask about Random too, as it is under Math.

**Comment by chrismaltby** [comment]
Completely agree on this, I'll start looking at it soon!

**Comment by DeerTears** [comment]
I feel this has been sufficiently added in 2 beta 5. The root of my issue was the difficulty I had in finding the events I want, now 2 beta 5 has search hints. Although search hints currently aren't in 3.0.2, it's much easier to find the events you want thanks to the categories and favourites system.

Maybe in the future someone will suggest fuzzy searching or search hints even with the much better Add event menu, but for my purposes I'm satisfied. Thanks for all the hard work you guys. 💙
