### ISSUE TITLE
GBStudio 1.2.1: I recieved an error called Error: spawn C:\Windows\system32\cmd.exe\ ENOENT -4058

### ISSUE THREAD

**Issue by GoldDa** [chrismaltby/gb-studio#520]
I was trying to run the test project template of GBStudio. Then I received an error of the code saying 
Error: spawn C:\Windows\system32\cmd.exe\ ENOENT
-4058
This is what it looks like 
![code](https://user-images.githubusercontent.com/70769154/92263111-1c9b1d00-eeaa-11ea-80fa-3aca7a1cba28.PNG)

Any suggestions on how do I fix this issue?

**Comment by RichardULZ** [comment]
Can you open command prompt cmd at all?
If not it is likely an issue  with being a locked down school computer, or antivirus.

**Comment by GoldDa** [comment]
> Can you open command prompt cmd at all?
> If not it is likely an issue with being a locked down school computer, or antivirus.

No actually. And yeah I think you're right since I'm using a laptop that's given by me from the school. Is there no way to fix this?

**Comment by RichardULZ** [comment]
No way to fix this, you must have access to cmd to compile a game.

One idea is to try place gbstudio on an external usb or hdd drive, there is a slim chance of it working if the drive decides it has elevated permission, however this is an issue with admin restrictions.

**Comment by GoldDa** [comment]
> No way to fix this, you must have access to cmd to compile a game.
> 
> One idea is to try place gbstudio on an external usb or hdd drive, there is a slim chance of it working if the drive decides it has elevated permission, however this is an issue with admin restrictions.

Dang, that's a shame. I also found another solution sort of. I installed GBStudio with the 32-bit ver. on my 64-bit laptop to see if it will have the same issue. Apparently it works but the only problem is the loading time with running a game. Does the engine usually take long to run a game? It takes around 1 or 2 mins.

**Comment by RichardULZ** [comment]
If you are using 2.0 beta, the compiler takes longer as it generates more optimized code, however we try to cache the built files so then next build should be fast, using more variables may require a recompile unfortunately.

**Comment by GoldDa** [comment]
.

> If you are using 2.0 beta, the compiler takes longer as it generates more optimized code, however we try to cache the built files so then next build should be fast, using more variables may require a recompile unfortunately.

Ah ok, thank you for the information and trying to help!
