### ISSUE TITLE
[Request] Additional Features

### ISSUE THREAD

**Issue by AsherGomez** [chrismaltby/gb-studio#53]
@chrismaltby
Hey! I really love what you are doing with GB Studio but I think that it lacks some features.
I know that some of these are probably in another issue but here they are anyway.

• Built-in tileset/sprite editor
• Built-in map editor
• Text-based scripting
• Collision detection (For enemies)
• Health and damage
• Popup menus (When a certain button is clicked)
• The ability to control more aspects of the game
• To have GB Studio be an all-in-one tool for GG game development
• Custom overlays instead of just black and white
• A "Follow Actor" event

Other than that it's an awesome piece of software. I'm making a game with it at the moment.

**Comment by AsherGomez** [comment]
@danielegrattarola What's the thumbs down for?

**Comment by danielegrattarola** [comment]
Because some of the requests you made are quite broad and not really constructive. 
To answer some of your points:
- [Sprite editor](kelapp.com)
- [Map editor](https://www.mapeditor.org/)
- Battle dynamics were requested in #33 
- Menu and "Follow actor" functionalities were requested in #24 
- Different color palettes were requested in #4 and #11 

Cheers, 
Daniele

**Comment by AsherGomez** [comment]
`"I know that some of these are probably in another issue but here they are anyway."`
^ Is at the beginning of my request. I wasn't going to search through all of the issues to see if it was already mentioned. I'm currently using Tiled for my map editor and Krita for sprites.

**Comment by danielegrattarola** [comment]
I think it's better if we try to keep things simple for the only main developer of this project. 
If everybody opened a new issue with requests for a specific subset of features, it would quickly become messy.

It's better to use Github's search function and comment with "+1" or putting a thumbs up on issues that you feel are important. In this way, the dev can have a sense of how to prioritise development, based on how many people "liked" a feature request.

**Comment by AsherGomez** [comment]
`• Different color palettes were requested in #4 and #11`
I wasn't asking for a different color palette here:
`• Custom overlays instead of just black and white`
I was asking that we can create custom overlays for things like maps, objectives, etc.
