### ISSUE TITLE
Camera is not centered on player

### ISSUE THREAD

**Issue by m-masaa** [chrismaltby/gb-studio#533]
**Describe the bug**
Since the beta, the player character isn't centered on the horizontal axis on large scenes.

**To Reproduce**
1. Make a large scene with a player character.
2. See error

**Expected behavior**
The player should be centered on screen (except when nearing the edges of the scene).

**Screenshots**
![unknown](https://user-images.githubusercontent.com/46198493/92880163-03e0b900-f40e-11ea-8dea-977b62d8a013.png)
The above screenshot was provided by eishiya, which shows the misalignment.

Below is a comparison between the Beta (Top) and version 1.2 (Bottom):
![Offcentered](https://user-images.githubusercontent.com/46198493/92880542-689c1380-f40e-11ea-8954-3d5cbad06352.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version: Beta 2.0

**Comment by chanunnaki** [comment]
I noticed this also, although I didn't realise it's demonstrating different behaviour from v1.

**Comment by chrismaltby** [comment]
Oops! I've just pushed a fix for this in dda49f21f8a3bd0ad524ae16a457bc04be258711 which now matches the camera alignment from 1.2.0 This fix will be available in the next beta release.

<img width="592" alt="Screenshot 2020-09-15 at 18 23 11" src="https://user-images.githubusercontent.com/16776042/93243908-c9b24700-f780-11ea-9bef-37c9c84963ac.png">
