### ISSUE TITLE
Ram viewer/modifier 

### ISSUE THREAD

**Issue by ChaoticPumpkin** [chrismaltby/gb-studio#540]
So this idea is a little far fetched but I was thinking about the gameshark for gameboy, it had a feature for making cheat codes, [See wikipedia](https://en.wikipedia.org/wiki/GameShark#GameShark_for_Game_Boy) and it would be very interesting if gb studio's emulator had this, for testing by adding lives, etc, and I haven't found any emulator on macOS or any os that could do that.

**Comment by RichardULZ** [comment]
Emulators like BGB or Sameboy should have a vram viewer and debugger that lets you modify the ram, but finding what ram address is your health variable could be pretty tricky.

**Comment by chrismaltby** [comment]
On the Discord @untoxa introduced me to https://emulicious.net/ which does have support for this kind of debugging and works on a Mac too :-) It looks like we need to update SDCC to a newer version to get the most out the source mapping functionality (as well as getting double the performance on the generated code!!) and this is on my todo list.

From the source maps that get generated right now when you export a ROM in `game.map` it lists the memory address of the script_variables array

```
_script_variables	CC40
```

and GB Studio knows the order that all your variables are in that array and the names you gave them, technically it should be possible to build either an additional `.gbs_map` file with some specific data that the inbuilt emulator can use or to include it within the existing sourcemap. Was speaking with Pau about this the other day IRL, with the current inbuilt emulator it might be a bit tricky to add a debug mode but it's definitely something I'd like to explore, especially as people start to customise their engines.

**Comment by untoxa** [comment]
for BGB you just need a symbol file which is produced by GBDK. so you just "go to" to _script_variables in data view window of the BGB debugger. newer versions of SDCC do not generate *.sym files, but they generate *.noi files. those *.noi files can be converted into *.sym very easily. here is an example of a conversion script: https://github.com/untoxa/hUGEBuild/blob/master/tools/noi2sym.py

for Emulicious you just add a watch in vs.code and enjoy, but you need a new SDCC. newer version of GBDK with support for the latest SDCC is about to come recently, as soon as @Zal0 makes LCC support the newest toolchain.

I suggest to switch GB Studio to that coming update as soon as it is released.

**Comment by ChaoticPumpkin** [comment]
Thanks for the help guys!
