### ISSUE TITLE
Timer script not called due to actor On Update script

### ISSUE THREAD

**Issue by pau-tomas** [chrismaltby/gb-studio#555]
**Describe the bug**

The timer script isn't being called, if there's an actor in the scene that has an `On Update` script (without a `Wait` event)

**To Reproduce**

Download [TestTimerScript.zip](https://github.com/chrismaltby/gb-studio/files/5258509/TestTimerScript.zip) and jump to point 7

or

1. Create a new project
2. Add a new scene
3. Add a `Set Timer Script` event to the scene `On Init`. The content of the script doesn't matter, but using something that is easily visible (like an Emote event) would be good.
4. Add an actor to the scene
5. Add one event to the actor `On Update`. I tested with `Variable: Set Flags`. Optionally: comment that event.
6. Build & run

7. Observe that whatever Event the timer was suppose to run isn't being called (ie: The player emote isn't showing every 1 second)

**Expected behavior**

The timer script to be called at a regular interval.

**Platform (please complete the following information):**
 - OS: macOS 10.15.5 (19F101)
 - App version 2.0.0 beta 2

**Additional context**

If a `Wait` event with a value different than `0` or `0.1` is added to the actor `On Update` all seems to work fine.

**Comment by pau-tomas** [comment]
After doing some debugging the reason why the timer isn't being called is because the check for an active script is always false:

https://github.com/chrismaltby/gb-studio/blob/8c777c612efdbb24f81cd6868b80ce9a96272de3/appData/src/gb/src/core/ScriptRunner_b.c#L158

Timer is being called in the attached script if that condition is removed, and the actor `On Update` seems to be called properly too. However I'm not sure of the side effects that it might have in other cases. @chrismaltby, could you think of any?

**Comment by pau-tomas** [comment]
Also, should the call to `ScriptTimerUpdate` be wrapped in `if (!ui_block)`? This is a change from the 1.2 behavior where dialogues where blocking the timer, right? Maybe we could offer it as an Event flag

https://github.com/chrismaltby/gb-studio/blob/8c777c612efdbb24f81cd6868b80ce9a96272de3/appData/src/gb/src/core/Core_Main.c#L185

**Comment by pau-tomas** [comment]
After some conversation with @RichardULZ an alternative to remove the `active_script_ctx.script_ptr != 0` check would be to replace it with `script_ctxs[0].script_ptr != 0` the assumption here being that `script_ctxs[0]` is only used for non background scripts so it'll never be true if a `On Update` script is running.

**Comment by mxashlynn** [comment]
@pau-tomas I'm curious how the 2nd issue, whether or not to check ui_block, was resolved?
