### ISSUE TITLE
BG Color & Collision BUG

### ISSUE THREAD

**Issue by ELV13Stm** [chrismaltby/gb-studio#558]
After coloring the BG Screen with pallets and applying wall collisions and saving and exiting, the engine treats it like it didn't happen. Basically , when you open the project again the colored BG with collisions are gone.

**Comment by ELV13Stm** [comment]
[BG Color Collision BUG.zip](https://github.com/chrismaltby/gb-studio/files/5259477/BG.Color.Collision.BUG.zip)
BUG FOUND ON A WINDOWS 10

**Comment by chrismaltby** [comment]
Hi @ELV13Stm I've just added a fix for this in #566 the developer releases on Github should be fixed now and this will updated in beta3.

**Comment by ELV13Stm** [comment]
thats great, thank you
