### ISSUE TITLE
[2.0.0 Beta 2] Pinned Actors set to Hide appear without being asked in a large scene

### ISSUE THREAD

**Issue by JamesParkNINJA** [chrismaltby/gb-studio#561]
**Describe the bug**
Pinned actors hidden on init in a scene larger than the initial viewport will pop back into view as soon as the player enters the viewport range where the pinned actors reside without any event calling them.

**To Reproduce**
1. Add a tall/wide scene
2. Pin actor/s to top of scene (or wherever is out of viewport of your player)
3. Set events, or set a custom event to hide the actor/s on scene init
4. Preview game, and walk towards pinned area
5. Actors will pop into view 

**Expected behavior**
Hidden actors to remain hidden until Actor: Show is applied.

**Screenshots**
![ITD-error-004](https://user-images.githubusercontent.com/6178652/94042170-21753180-fdc3-11ea-894f-efc71fc546b1.gif)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 2.0.0 Beta 2

**Sample Project**
Included is a simplified version of the issue.
[Test Pin Bug.zip](https://github.com/chrismaltby/gb-studio/files/5269633/Test.Pin.Bug.zip)

**Comment by chrismaltby** [comment]
Hi @JamesParkNINJA I've included a fix for this issue in beta3 now
