### ISSUE TITLE
[2.0.0 Beta 2] Custom Event title changes to EVENT_CALL_CUSTOM_EVENT in all scenes after edit

### ISSUE THREAD

**Issue by JamesParkNINJA** [chrismaltby/gb-studio#563]
**Describe the bug**
When you edit a Custom Event, the name of the event reverts to EVENT_CALL_CUSTOM_EVENT, which will be very confusing for multiple Custom Events.

**To Reproduce**
1. Create A Scene
2. Create A Custom Event and name it
3. Add the Custom Event to the Scene's Init
4. Edit The Custom Event and do something (toggle a tab, or change a value)
5. Return to the Scene
6. See the default title

**Expected behavior**
Title permanence, it should not change.

**Screenshots**
![ITD-error-006](https://user-images.githubusercontent.com/6178652/94051704-d1e93280-fdcf-11ea-82b5-ff67ed0a63ab.gif)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 2.0.0 Beta 2

**Sample Project**
[Test Custom Events.zip](https://github.com/chrismaltby/gb-studio/files/5270113/Test.Custom.Events.zip)

**Comment by patrickmollohan** [comment]
Can replicate with Ubuntu, same app version.

**Comment by chrismaltby** [comment]
Hi @JamesParkNINJA theres a fix for this issue written by Pau that is now included in beta3
