### ISSUE TITLE
Adjust actor limit counter from 10-30 based on scene size

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#569]
**Is your feature request related to a problem? Please describe.**
Only stated in the changelog, new users sometimes expect their single screen scenes to allow up to 30 actors at once, where the limit is 10.

**Describe the solution you'd like**
Dynamically change the displayed actor limit between10 when a scene is 144-160, 360 tiles large, to 30 when over 1080 tiles? (3 screens tall?)

**Describe alternatives you've considered**
Figuring out if a scene has more than 10 actors in a screen width to warn? 
Or a simpler compile time warning? 

**Additional context**
I suppose advanced users could hide and show actors within a single screen, working around the 10 actor at once limit, but the limits being 30 per map, and 10 on screen is confusing to document either way.

**Comment by maxoakland** [comment]
> I suppose advanced users could hide and show actors within a single screen, working around the 10 actor at once limit, but the limits being 30 per map, and 10 on screen is confusing to document either way.

I'm actually doing that in my game right now!
