### ISSUE TITLE
When renaming a background it corrupts the project.

### ISSUE THREAD

**Issue by RedstoneGuyLol** [chrismaltby/gb-studio#574]
**Describe the bug**
When ever i rename one background, the background in the application turns black and some of the actors, collisions, and triggers change their X and Y positions

**To Reproduce**
1. Go to the project
2. Click on assets then click backgrounds
3. rename any background (it has to be used)
4. Go back to the GB Studio application 

**Expected behavior**
The background getting set to default.

**Screenshots**
![error1](https://user-images.githubusercontent.com/63218795/94467162-88fafa80-0190-11eb-8831-72e8ce2ab596.PNG)
![error2](https://user-images.githubusercontent.com/63218795/94467164-88fafa80-0190-11eb-8209-ef31843287f4.PNG)

**Platform (please complete the following information):**
 - OS: Windows
 - App version: 2.0.0 Beta

**Comment by chrismaltby** [comment]
Hi @RedstoneGuyLol I've had an attempt at fixing this here #576 I just need to test this on all the different platforms and make sure it doesn't break anything but so far seems promising.

**Comment by RedstoneGuyLol** [comment]
> Hi @RedstoneGuyLol I've had an attempt at fixing this here #576 I just need to test this on all the different platforms and make sure it doesn't break anything but so far seems promising.

Ok, i hope this will get patched soon.

**Comment by chrismaltby** [comment]
Hi @RedstoneGuyLol I've merged this fix into the latest dev build and it's going to be included in beta4 :-)

**Comment by RedstoneGuyLol** [comment]
> Hi @RedstoneGuyLol I've merged this fix into the latest dev build and it's going to be included in beta4 :-)

Thanks!
