### ISSUE TITLE
Retention of Variable Names and Event allocated Actors upon Scene duplication

### ISSUE THREAD

**Issue by JamesParkNINJA** [chrismaltby/gb-studio#578]
**Is your feature request related to a problem? Please describe.**
When duplicating a Scene, the Local Variables are stripped of their names, and all events pertaining to Actors are defaulted to the Player Actor, rendering the Events useless until manually corrected. For large Event queues, this is extremely time consuming to fix.

**Describe the solution you'd like**
The Variable names should be retained, and Actor UIDs should be updated accordingly in the Scene's Events. This remove the frustration of duplicating an Event-heavy scene and having to go through every event to check for misnamed Variables and incorrect Actors.

**Describe alternatives you've considered**
The only alternative for the moment is manual replacement.

**Additional context**
![ITD-error-007](https://user-images.githubusercontent.com/6178652/94597882-12d8bf80-0286-11eb-8abc-72b745fcf4c4.gif)

**Comment by chrismaltby** [comment]
Hi @JamesParkNINJA I've implemented this now in #585 so the next release should keep variable names and actor references correctly when copy pasting! :-)
