### ISSUE TITLE
about i18n

### ISSUE THREAD

**Issue by FormatToday** [chrismaltby/gb-studio#58]
It's vary happy to see the fantastic tool.i'm from China,and i want to bring gb-studio to gb players in China.So can I translate it into Chinese?
It is wonderful to hava **a button or menu to choose language**,and give us a way to i18n this great tool.

**Comment by chrismaltby** [comment]
Duplicate of https://github.com/chrismaltby/gb-studio/issues/43 but definitely want to get this implemented soon
