### ISSUE TITLE
Make "Set Background Palette" options clearer

### ISSUE THREAD

**Issue by coasterspaul** [chrismaltby/gb-studio#591]
**Is your feature request related to a problem? Please describe.**
In the `Palette: Set Background Palette` event, leaving a slot as "None":
![image](https://user-images.githubusercontent.com/11203426/95098555-720a5a00-06f4-11eb-9ebb-26417b40bee6.png)
actually sets it to the scene default. [Thanks to um3k for the clarification.] This is pretty useful for stuff like palette cycling - you don't have to set every single palette in every event - but a lot of people don't seem to know it's there.
(I think some people assumed "None" just meant the DMG palette, which isn't helped by the color preview.)

**Describe the solution you'd like**
Change the text for "None" to "Scene default" or similar. And change the color preview - either:
- hide it entirely
- set it to all white, which would look the same as getting rid of it entirely in the light theme, and it'd probably still make sense in other themes
- somehow actually get it to show the scene default for that palette slot, if that's even possible

**Describe alternatives you've considered**
Also, a "Keep As-Is" option, leaving a palette set the same instead of resetting to the default, would be useful for even wilder color-changing, assuming that's possible with how the event's set up. Since there'd be no way to tell what colors that would be ahead of time, just either:
- hide the preview entirely
- set it to all white, which would look the same as getting rid of it entirely in the light theme, and it'd probably still make sense in other themes

**Comment by chrismaltby** [comment]
Hi @coasterspaul I've just made an update to improve this in #596 which should hopefully work better now. I just need to do some testing before I merge that but from a quick try it seems to be working much better.

A keep-as-is feature would be quite nice, I think it might be a bit tricky with they way palettes are handled though.

**Comment by coasterspaul** [comment]
And yet you managed to add the keep-as-is feature to beta 4 anyway? Thanks so much!

**Comment by chrismaltby** [comment]
Hah, yep I figured out a way to do it without changing too much in the end :-D
