### ISSUE TITLE
Set Sprite Event Changing when copied from a Scene

### ISSUE THREAD

**Issue by 1337Edrick** [chrismaltby/gb-studio#598]
**Describe the bug**

I have a scene where there is an event that changes an actor (not the player) sprite sheet. When this scene is copied, the new event switches it to the players sprite that is being set (instead of the actor that was on the original scene).

**To Reproduce**
1. Set up a scene where an actors (not the players) sprite is being set to a different sprite sheet.
2. Copy the scene
3. Paste the scene
4. See that the sprite being changed is now the players sprite sheet instead of the actor in the original scene.

**Expected behavior**
When you copy the scene, it should keep the same actor's sprite sheet that is being updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/72537335/95413041-a98d2800-08e7-11eb-9973-6bb9445a7344.png)
![image](https://user-images.githubusercontent.com/72537335/95413089-c75a8d00-08e7-11eb-9594-490333da7a23.png)

**Platform (please complete the following information):**
 -Windows 10 (19041.508)
 - App version 2.0.0-beta2

**Additional context**

**Comment by RichardULZ** [comment]
Thanks for the thorough write up, clear screenshots, and noting the version!
Could you please test the latest v2beta development builds and confirm this issue is fixed by #585
Link to builds.
https://github.com/chrismaltby/gb-studio/tree/v2beta#beta-builds

**Comment by 1337Edrick** [comment]
Thanks Richard, I just confirmed that #585 did fix this issue.

I don't test software or use Github, so I apologize. I should have searched through the issues first before submitting.
