### ISSUE TITLE
Toggle Player Actor Animation on Movement

### ISSUE THREAD

**Issue by manyheadedmonster** [chrismaltby/gb-studio#601]
**Problem:**
~~_Animation controls for player actor are based on assumption of RPG style walking character. If player actor has a multi-image spritesheet there is no way of preventing it animating on movement. You can slow down the walking animation, but can't set it to 0. It is possible to swap in a single image spritesheet but this is very clumsy and has limitations when used for complex item pick up/drop functionality (for example). Including the ability to toggle player animation on movement would allow for more flexibility in player actor usage (can act more easily as cursor with conditional states, can 'pick up' frame of another actor on interaction, actor can 'slide' or float over set spaces)._~~

EDIT: Actually realised what was happening was slightly different than first thought. You _can_ set player speed to "none" with the Actor: Set Animation Speed component but player actor will still use separate frames for facing different directions. Will close this request and open a new, more accurate one.
 
**Suggestion:**
Option to toggle off animate player actor on movement.

**Alternative:**
Global option to set player actor animation speed to 0.

**Additional Info:**
This may also lead into ideas around more complex player actor animation controls (e.g: defining different frames to be used under different conditions) but that's a more involved suggestion that should be it's own request.

Thanks a lot!!

**Comment by RichardULZ** [comment]
I believe this change made it into 2.0beta, where you can set the animation speed or cycle while stationary, specifically to allow or disable animation with moving objects.

**Comment by manyheadedmonster** [comment]
Ok I'm going to adjust my request a little as I think what's happening is actually a little different. There IS an option to set the player animation speed to "none" with an **Actor: Set Animation Speed** component, but it will still use separate frames for facing left, right, up and down. What we maybe need then is the option to ignore rotation.

**Comment by manyheadedmonster** [comment]
Request is actually based on different issue than first thought, so closing this to make a more accurate request.
