### ISSUE TITLE
Tab 'on update' can be hidden accidentally

### ISSUE THREAD

**Issue by beatbesmer** [chrismaltby/gb-studio#605]
**Is your feature request related to a problem? Please describe.**
In the german translations, the naming of the sidebar tabs showed only 'on interact' and 'on init'. The 'on update' wasn't visible trough the width of the translated strings let the third Tab dissapear. After reading a hundred times the docs and by changing the width of the sidebar, the missed Tab appeared. 

**Describe the solution you'd like**
Let the User See if there is another Tab hidden in the sidebar.

I know, this might happen rarely. But it would avoid others to waste their time with the same problem

**Comment by RichardULZ** [comment]
Can you post a screenshot of the issue and what version of the 2.0 beta this is in? 
Is this only when the tab is smaller than usual with the German translation/other long translations?

Your suggested solution doesn't really describe a solution.
Possible solutions, 

1.  Shorten the length of translation? 
2.  Provide a horizontal scrollable tab?
3. Sack the tabs underneath when too long?
4. If tab lengths are too long, shorten the text with a ... To make sure all tabs fit on the side bar?

**Comment by beatbesmer** [comment]
Thank you for the reply and concrete examples of what is required

**Versions tested**
Tested 2.0.0 b3 and b4

The _problem_ can be seen in the following two screenshots. The tab is hidden at the right side of **Zur Interaktion**, **Beim Initialisieren**
![image](https://user-images.githubusercontent.com/17173365/95688093-def78580-0c07-11eb-824f-da4b9a22c0e0.png)
![image](https://user-images.githubusercontent.com/17173365/95688096-e323a300-0c07-11eb-90f7-f946d27dcb96.png)

**How to reproduce**
I used to work with the default width of the sidebar (screen resolution is 1680 x 1050), so far there wasn't any manual adjustment. As soon as the sidebar gets wider, you can see previously hidden tabs.

**Possible solution**
A. Center the focused tab (if not the first or latest) and shorten the outer tabs (if needed) with "..." as showed in the following picture and let the list of tabs be scrollable / dragable horizontally
![image](https://user-images.githubusercontent.com/17173365/95688471-b02ede80-0c0a-11eb-86fc-153174ee075f.png)
B. Put them into a dropdown
![image](https://user-images.githubusercontent.com/17173365/95688441-7231ba80-0c0a-11eb-960f-4805880c6f1f.png)

**Comment by RichardULZ** [comment]
Thanks so much!
This is slightly ignorant of me being an English speaker, but would a translation of "Beim Initiale" be acceptable? (is Beim correct? should it be Szene?)
I think we use Scene Init in english, which is a gross shortening of initialize. 

I agree a solution that allows for any size text should be looked into, 
Version A may work without the need for scrolling if the tabs have a minimum collapsed size, and the selected tab is expanded. 
Not so keen on option B, as it makes things quite hidden / difficult to navigate, but that could be expanded into 2 rows.

**Comment by beatbesmer** [comment]
> This is slightly ignorant of me being an English speaker, but would a translation of "Beim Initiale" be acceptable? 

Yep, i think so. IMHO the german loalization is verry accurate, i can easily work with 👍

> (is Beim correct? should it be Szene?)

There are many ways to translate this. `Beim Initialisieren des Szene` would be the most precise i guess... (when the scene is loaded) `Beim Szenenstart` or `Szenestart` a shorter version. (german allows you to combine an nearby endless amoun of nouns together 😄). But befor we get bogged down in this discussion about translation, i'd prefer to open a seperate issue if you agree.... if there is a need. 

About the tab- issue, i have nothing to add. I already enjoy my _discovery_ 😃

**Comment by chrismaltby** [comment]
Would something like this work maybe, the active tab shows the full text, all others will crop and show an ellipsis. Then also when you hover over a tab that one expands and then the others all contract so you can read them without needing to click.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16776042/95783896-aff61800-0cca-11eb-8722-360410d01c72.gif)

If this works I've got the code ready to merge in c149b5539efd2045bbe8a810779dc50f7f0bc3be

**Comment by beatbesmer** [comment]
This was resolved fast, you should be called Barry Allen. I like this solution.

**Comment by beatbesmer** [comment]
Nothing to add for the Moment. Thank you for this fast implementation
