### ISSUE TITLE
Adventure scene type movement is broken

### ISSUE THREAD

**Issue by coasterspaul** [chrismaltby/gb-studio#611]
**Describe the bug**
In the Adventure scene type, pressing just up, down, left, or right on the D-pad results in diagonal motion instead, which makes it impossible to move straight vertically or horizontally. Until you get stuck on a wall (see my demonstration) - but even then the other directions will lock you into only moving diagonally again.

**To Reproduce**
1. Set a scene's type to Adventure (pressing shift to make that option show if it's not already of course) and run it.
2. Try moving around.

**Expected behavior**
I should be able to move in 8 directions, not just the 4 diagonal ones unless I get stuck on a wall.

**Screenshots**
Here's a demonstration of me pressing one direction at a time - with an actor updating to show the direction I'm pressing in case that helps make things clearer. 
![example](https://user-images.githubusercontent.com/11203426/95806553-91455080-0ccd-11eb-9850-fdaccea56eba.gif)

**Platform (please complete the following information):**
 - OS: Windows 10.0.19041
 - App version: 2.0 beta 4

**Comment by Animacreep** [comment]
The adventure scene type is known to be buggy, that's why it's hidden.

**Comment by coasterspaul** [comment]
Yeah, but this is still a pretty big regression - the movement used to _mostly_ work and now it's very clearly broken, so it seemed worth reporting.
