### ISSUE TITLE
error: address overflow

### ISSUE THREAD

**Issue by numonkeys** [chrismaltby/gb-studio#613]
Hi again --

I wrote a few months ago with a build error that we resolved (https://github.com/chrismaltby/gb-studio/issues/404). Many more months of more work done, always keeping my scripts within limits.

Just did a clean install of GBStudio on a brand new MacBook Pro, copied over my files from my old decrepit MacBook, and -- voila -- I'm getting a new error on build, likely related to issue #404. The strange thing is that the game file builds & runs fine on my old computer, but won't build on the new one.

Installing fresh GBStudio included downloading & installing latest Xcode from apple developer site, not sure if the bug is related to new Xcode build from Apple.

**Describe the bug**
Crashes on build (see screenshot).

**To Reproduce**
1. Click "build"
2. See error

**Expected behavior**
Build & test game locally.

<img width="1018" alt="Screen Shot 2020-10-13 at 8 55 47 PM" src="https://user-images.githubusercontent.com/3458886/95942198-70e1c880-0d97-11eb-9040-8bd7f7a18673.png">

**Comment by RichardULZ** [comment]
It is imperative to provide the version of gbstudio you installed, as part of the bug report template.
If this is 1.2.1, the develop branch has fixes and improvements to be in legacy 1.2.2, such as dynamic and larger rom sizes.
2.0 beta also has dynamic rom sizes, but still has a minor migration issue with timer or attached scripts.

**Comment by numonkeys** [comment]
Hi Richard

1.2.1 was installed today.

I checked for updates but looked like everything is up to date (though the 1.2.1 build was back in Jan). Can you point to updates? Is there a 1.2.2 like, or should I move on to 2.0 beta?

thx

nick

**Comment by RichardULZ** [comment]
1.2 development builds https://github.com/chrismaltby/gb-studio#development-builds
2.0 beta development builds https://github.com/chrismaltby/gb-studio/tree/v2beta#beta-builds
You would have been using a 1.2 dev build if you were over 64 banks in your project (130??? that's over a 2mb cart!)

The updater will only update to official builds, no use for development or betas.
If you make a copy of your project folder, and try a v2beta build, you may notice a lot of improvements and features like fade to black, but also need to test for any errors, might be best to stick with a 1.2 dev build until we add more options to attached scripts for compatibility.

**Comment by numonkeys** [comment]
Awesome, the latest 1.2 dev build has fixed the problem. Thx!

Yes, the project file is clocking in at 200mb right now. The final game file is only 2mb when it's done building, but it's safe to say there's a lot of data / game world. We might be going for the biggest retro rpg, when it's all done it will hopefully take players months if not years to get through the game.

In the meantime, spinning off the first mini-game shortly. Focussed on just the combat system, the mini-game is helping to really dig in and polish this aspect of the game.

Fun times, thanks again for the feedback. Closing the bug.
