### ISSUE TITLE
Folder exist check.

### ISSUE THREAD

**Issue by Overide-sys** [chrismaltby/gb-studio#616]
I'm making a game where the story branches off at two parts. One where a file called "Game7" is in a folder called "Documents" and one where it isn't. I'm planning to distribute the game in a folder already with the file.
Is there a way for me to code a way for the game to check if the file exists in the directory the game is in?
Or a way for me to add a script that does? 
I'm still quite new to GB studio and not sure if this is the right place to put this.

**Comment by BowersFam** [comment]
I don’t think there is a way. The GameBoy only has room for one ROM file so you would not be able to play it on a GameBoy. I don’t know what your game is about but if you want it to branch off you can do that with variables. Hope that was helpful. PS: First game should use some variables so you can learn how they work.
