### ISSUE TITLE
Playtest bug from Reddit: game crashes

### ISSUE THREAD

**Issue by numonkeys** [chrismaltby/gb-studio#630]
Did an early launch of a mini-game still in active development on itch.io. Play tester discovered a rather serious bug (game crash):

**Describe the bug**
From reddit post:
[–]Saffron-Basil 1 point 14 hours ago 
I had been farming spells. All my gold had gone into getting riddles once I had a set of magical gear. So I kept using prayer and focus until they gave me spells or, if they refused, killed them with fight to get gold for more riddles. After learning Control Weather (I think I had learned all other spells, this was the last), the screen went blank and even after a full minute, the menus didn't come back. No sound, no button inputs, just crashed.
If I had to wager a guess, I probably overloaded some form of memory by learning the last spell

**To Reproduce**
1. Play Dragon Battle (https://apt18.itch.io/dragon-battle)
2. Learn all the spells (via dragons in battle, temple between battles)
3. Game crashes

**Expected behavior**
Player continues playing with all their spells.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Game was built/compiled in MacOS
 - App version: 1.2.2

**Additional context**
Have been doing some initial marketing & play testing with early players on reddit and elsewhere. One of our reddit players noticed this bug where the game crashed (blank screen) after they learned all the spells possible in the game. I've double-checked the code and don't see anything out of the ordinary, esp nothing that would cause a full game crash.

Thx for the help solving this.

Let me know what I can do to help.

**Comment by RichardULZ** [comment]
It's unusual for a game crash to be perfectly black, 
Do you have any scenes that are full black it could have accidentally transferred to? 
If you have personally reproduced the error, a video might show if it is an overflow or incorrect/bad scene jump.

As this is 1.2 series and not the v2beta, there is an issue with unregulated loops (label define: loopstart, events that don't wait (eg increment), goto loopstart) 
loop forever has a built in wait next frame to solve that, and the 2020 compiler seems to have fixed it in v2, but a wait 0 might work if this is the issue in 1.2.2(dev).

We can't really help without an easily reproducible version, if you are sure it is related to spells, try adding a test room where you can add each spell in succession to try and reproduce the issue with less hassle. 

There's not much to go on if it can't be reproduced, and the next step after that is looking at the code to create a minimal example.

**Comment by numonkeys** [comment]
Hi Richard

Took your advice and built a spell hack to active all game spells. Game ran fine after that. I'm wondering if maybe the reviewer was play testing while I was updating a live production build or something.

Nothing in the code to warrant the black screen crash.

Closing this bug.

thx again

**Comment by RichardULZ** [comment]
That's unfortunate, while I'm sure the user did encounter the bug somehow, there's not much anyone can do until the bug is more easily reproducible.

It could be a combination of all the stats, gold, riddles, how you track other stats, or how long the game was running for/interactions gone through since it seems mostly 1 scene? No easy way to tell. 

Though there's still some quirks of 1.2 > 2.0 migration to solve, it has a much newer compiler and may be worth a shot at some point.

Good luck and hope the launch goes well!
