### ISSUE TITLE
Make PNG editor configurable

### ISSUE THREAD

**Issue by trevorparscal** [chrismaltby/gb-studio#644]
A way to configure which app to open PNG files in when the edit button is clicked. Because PNG files are so commonly used for so many other purposes, most operating systems correctly open a viewer, not an editor, for this file type. Changing this setting system-wide is possible, but then leads to many problems since most of the time a viewer is what you want.

This setting could be controlled by the user by adding a field in the settings window to set a path to an app for editing PNG files, rather than the system default.

Another option would be to follow the system's preference on a per-file basis - which at least macOS supports.

**Comment by chrismaltby** [comment]
This is a good idea, I've just implemented it in #672 :-)
