### ISSUE TITLE
Error: EPERM: operation not permitted, open 'C:\Users\(Username)\AppData\Local\Temp\tileset_0.png'

### ISSUE THREAD

**Issue by BugTellingFairy** [chrismaltby/gb-studio#645]
So, here is my bug: when I try to build a game, it will say this:

Error: EPERM: operation not permitted, open 'C:\Users\VRFAN\AppData\Local\Temp\tileset_0.png'

When I opened it, it looked like a corrupted image. Is there a solution?

**Comment by BugTellingFairy** [comment]
In the first line, I forgot to put: when I try to build **and run** a game

**Comment by RichardULZ** [comment]
@BugTellingFairy Please follow the submissions template which includes version and os, it keeps bug reports clean and organized.

Your issue is most likely a lack of admin privilege, try to run gbstudio as admin, or reboot your computer.

**Comment by BugTellingFairy** [comment]
I rebooted my pc and tried to run it, and used admin, but still won't work. btw I'm on a Windows 8.1 Build 9600

**Comment by BugTellingFairy** [comment]
Case dismissed. I deleted tileset_0.png and reinstalled the program.
