### ISSUE TITLE
[Request] Set Actor Sprite Sheet

### ISSUE THREAD

**Issue by Shokupanda** [chrismaltby/gb-studio#65]
So there's a "Set Player Sprite Sheet", but how about a "Set Actor Sprite Sheet" too? :-)

Cheers!

**Comment by chrismaltby** [comment]
It's definitely a good idea.

Internally it's a tiny bit more awkward as there's only a small amount of sprite memory available, I can't just replace the sprite as any other actors in the scene with the same sprite sheet would also switch. I think I'd need to, per scene, find calls to "Set Actor Sprite Sheet" and add those sprite sheets to the list of sprites that gets loaded at the scene start. Calls to "Set Actor Sprite Sheet" would also then count towards your per scene frame count. It's all definitely doable though and could be very useful.

For setting the player sprite sheet it was a bit easier as I reserve 6 frames for the player at all times and switching them won't affect any other actors.
