### ISSUE TITLE
Error de %appdata%

### ISSUE THREAD

**Issue by Alangamer124** [chrismaltby/gb-studio#653]
Buenas ayer en la noche usando gb studio al iniciar el juego me aparecía un error que decía - Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Equipo\AppData\Local\Temp\_gbsbuild' y ese error no me deja correr el juego ¿tienen una solución?.

**Comment by RichardULZ** [comment]
GB Studio version? 2.0 Beta 4? 
Windows 10?

Can you try to delete the Temp_gbsbuild folder yourself, or see if restarting the computer helps.

**Comment by Alangamer124** [comment]
ok pero mi computadora es windows 7 voy a intentar eliminar el archivo

**Comment by Alangamer124** [comment]
> ¿Versión GB Studio? 2.0 Beta 4?
> Windows 10?
> 
> ¿Puede intentar eliminar la carpeta Temp_gbsbuild usted mismo o ver si reiniciar la computadora ayuda?

muchísimas gracias me funciono eliminando el temp_gsbuild se lo agradezco

**Comment by Alangamer124** [comment]
gracias se arreglo mi error.
