### ISSUE TITLE
[Game World / Colorize] Show used palette for a concrete tile

### ISSUE THREAD

**Issue by beatbesmer** [chrismaltby/gb-studio#656]
**Is your feature request related to a problem? Please describe.**
When you'd like to colorize a scene and you're using several similar palettes in this scene, it is hard to determine the palette used for an already colored tile.

**Describe the solution you'd like**
Let the palette chooser highlight the used palette for a tile where the mouse is over. In the example, i used a blue line under the palette concerned. I guess there will be nicer variants like hovering the entire palette maybe... A SHIFT-Click or something similar could directly select the highlighted palette
![image](https://user-images.githubusercontent.com/17173365/98928057-9a4a5d00-24d9-11eb-9485-316293435fb0.png)

**Describe alternatives you've considered**
Add an **color- picker- like** tool to get the palette used by clicking on the concrete tile
![image](https://user-images.githubusercontent.com/17173365/98927984-7f77e880-24d9-11eb-9fb5-b90d88494135.png)

**Comment by chrismaltby** [comment]
Hey @beatbesmer this is a good idea! I've just implemented it in #664 

I had to use Alt+Click rather than Shift+Click as that is already being used while painting to draw lines but other than that it's pretty much as you requested :-)
