### ISSUE TITLE
Fade settings event not being present in the latest dev build

### ISSUE THREAD

**Issue by Animacreep** [chrismaltby/gb-studio#657]
**Describe the bug**
The latest dev build (2.0.0-beta5) doesn't feature the `Fade: Change Settings` event that previous versions had.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/34885906/98962027-7f421200-2506-11eb-835a-f475c850579c.png)
![thy](https://user-images.githubusercontent.com/34885906/98962063-89641080-2506-11eb-8c27-4b8c86d355b3.png)

**Platform (please complete the following information):**
 - OS: Windows 7 Ultimate x64 SP1
 - App version: 2.0.0-beta5 (Dev Build)

**Comment by pau-tomas** [comment]
It's been replaced by `Engine: Field Update` and select the `Fade Style` property.

**Comment by Animacreep** [comment]
Oh, I didn't know that. Thanks!
