### ISSUE TITLE
[Question] Are The Events Based On ASM Or C?

### ISSUE THREAD

**Issue by AsherGomez** [chrismaltby/gb-studio#66]
Hi, I'm wondering if the events are based on Assembly or C.

**Comment by chrismaltby** [comment]
Hi Asher,
The events compile down to an array of data that get interpreted by C at run time. Something like this
```
0x02, // Display Text
0x00, // High bits of text string index
0x01, // Low bits of text string index
0x08, // Set active actor
0x00, // Player index
0x10, // Active actor move to
0x08, // X Pos 8
0x10, // Y Pos 16
0x00, // Script end
```
The code that builds this is in https://github.com/chrismaltby/gb-studio/blob/master/src/lib/compiler/compileEntityEvents.js 
Potentially a simple language could be written to compile to this format as an alternative to the UI too.

**Comment by AsherGomez** [comment]
What code would I have to look at to add an event?

**Comment by chrismaltby** [comment]
Check out the recent commits by thomas-alrek that are merged into develop.
https://github.com/chrismaltby/gb-studio/pull/61
https://github.com/chrismaltby/gb-studio/pull/56

**Comment by AsherGomez** [comment]
How would I build the source for MacOS to test it?

**Comment by thomas-alrek** [comment]
AsherGomez, just clone the repository and install dependencies using yarn.

```bash
git clone https://github.com/chrismaltby/gb-studio.git
cd gb-studio
yarn
yarn start
```
