### ISSUE TITLE
[Background] Allow single Tiles to be swaped

### ISSUE THREAD

**Issue by beatbesmer** [chrismaltby/gb-studio#666]
**Is your feature request related to a problem? Please describe.**
Caused by Actor / trigger limits, we're not able to implement a digging- function which can be used on the entire screen, like there are in the Zelda Oracle / Awakening Titles (https://youtu.be/FpPGI0Ujl8I?t=515)

**Describe the solution you'd like**
Add a function which let replace some tiles (8x8 or 16x16) of the current- screen without fading out / fading in the entire screen, 

**Describe alternatives you've considered**
Usage of actors, but we'll be limited to only a few spots per scene

**Additional context**
There will be the problem of "how to know", when this function is allowed to be executed and when not. Not every tile in a screen should be able to replaced. Maybe this could be solved by an condition which depends to a tile concrete used on the screen: if tile on position x/y matches one on the list, then return TRUE. This maybe would require another new function to GB studio, which maybe pre-render the screen and show a selection of used tiles to the User (maybe i can upload a graphical mock-up one day)

**Comment by RichardULZ** [comment]
See this for a thread on tile manipulation and problems each type needs to address 
https://github.com/chrismaltby/gb-studio/issues/499#issuecomment-683777362

**Comment by beatbesmer** [comment]
@RichardULZ So, this seems more or less a duplicate?

**Comment by PRobbie** [comment]
I just made a post requesting a matrix/array system. Would that type of system I requested help your program? If so, to comment there would be great. It will show people examples of why it would be very very handy,
