### ISSUE TITLE
I cannot export a project

### ISSUE THREAD

**Issue by EpicGamerKermit** [chrismaltby/gb-studio#669]
![image](https://user-images.githubusercontent.com/58113779/99761341-4a8a1800-2b0f-11eb-80da-7dae8ede4cfb.png)
This is what I get. how do I fix this?

**Comment by RichardULZ** [comment]
I don't know how you created a blank issue report, it should give you the option for bug or feature request.
You are missing essential information like gbstudio version (2.0 beta 4? Beta 5?), OS, and any steps to reproduce.

Was this with a new sample project?

Have you tried restarting, running gbstudio as admin, or re downloading gbstudio?

This is not an error I've seen before, but seems like it might have a bad image asset in the project.

**Comment by EpicGamerKermit** [comment]
> I don't know how you created a blank issue report, it should give you the option for bug or feature request.
> You are missing essential information like gbstudio version (2.0 beta 4? Beta 5?), OS, and any steps to reproduce.
> 
> Was this with a new sample project?
> 
> Have you tried restarting, running gbstudio as admin, or re downloading gbstudio?
> 
> This is not an error I've seen before, but seems like it might have a bad image asset in the project.

@RichardULZ I made this project it is not a sample project

**Comment by EpicGamerKermit** [comment]
FIXED: I added a photo that was not pixelated
