### ISSUE TITLE
Wall Climb

### ISSUE THREAD

**Issue by TheRetroRoomRoo** [chrismaltby/gb-studio#677]
**Describe the bug**
I am trying to create a wall climb effect comparable to Metroid. Using the "If Joypad Input Pressed" on several triggers that lay on the wall.  

**To Reproduce**
<img width="207" alt="wall climb" src="https://user-images.githubusercontent.com/75143454/100484482-9ec26880-30ca-11eb-8de5-6fafad9948f6.png">

**Expected behavior**
Smoothly climbing the wall much like in Metroid 

**Screenshots**
The wall climbing has the character dip inward and doesnt run very smooth. Luckily it works good but unfortunately doesn't look great. I have tried everything to make it smooth. 

Here is a slow motion GIF of the issue.
![Dip 1](https://user-images.githubusercontent.com/75143454/100485193-2b6e2600-30cd-11eb-9352-6fedd99c754d.gif)

**Platform (please complete the following information):**
Gbstudio 2 beta 4
**Additional context**

**Comment by RichardULZ** [comment]
An image of the scene, showing how you have placed triggers and collision might help. As well as the x,y coordinates of the wall.
Most likely the tile values for each moveto are off by 1, As you said there are multiple triggers in the walls, mistakes are easy.

You should have better results with Larger thin triggers on walls (triggers can be resized), 
and Move Relative events, which move + - an amount of tiles, relative to the players last position, simplifying a lot of code.

For the top/corner, you could either use a new trigger for the top, or as part of the wall trigger, check If Player is at X, Y.

**Comment by TheRetroRoomRoo** [comment]
> An image of the scene, showing how you have placed triggers and collision might help. As well as the x,y coordinates of the wall.
> Most likely the tile values for each moveto are off by 1, As you said there are multiple triggers in the walls, mistakes are easy.
> 
> You should have better results with Larger thin triggers on walls (triggers can be resized),
> and Move Relative events, which move + - an amount of tiles, relative to the players last position, simplifying a lot of code.
> 
> For the top/corner, you could either use a new trigger for the top, or as part of the wall trigger, check If Player is at X, Y.

I tried everything under the sun. on multiple walls. It is definitely a bug. The relative movement option doesnt work as well

> **Describe the bug**
> I am trying to create a wall climb effect comparable to Metroid. Using the "If Joypad Input Pressed" on several triggers that lay on the wall.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> <img alt="wall climb" width="207" src="https://user-images.githubusercontent.com/75143454/100484482-9ec26880-30ca-11eb-8de5-6fafad9948f6.png">
> 
> **Expected behavior**
> Smoothly climbing the wall much like in Metroid
> 
> **Screenshots**
> The wall climbing has the character dip inward and doesnt run very smooth. Luckily it works good but unfortunately doesn't look great. I have tried everything to make it smooth.
> 
> Here is a slow motion GIF of the issue.
> ![Dip 1](https://user-images.githubusercontent.com/75143454/100485193-2b6e2600-30cd-11eb-9352-6fedd99c754d.gif)
> 
> **Platform (please complete the following information):**
> Gbstudio 2 beta 4
> **Additional context**

This worked like a charm. Thank you so much!
