### ISSUE TITLE
Dialogue box cuts off when using several variables

### ISSUE THREAD

**Issue by Anima-SodoDev** [chrismaltby/gb-studio#683]
**Describe the bug**
The dialogue event enforces a lower limit when the developer uses variables in the same box. Bastani, developer of the plugins included in the zip below believes that variables are treated as 2 characters.

**To Reproduce**
[Variable Problem.zip](https://github.com/chrismaltby/gb-studio/files/5647769/Variable.Problem.zip)
Open the project and try typing something on the dialogue box. Ignore plugins, they do not affect the outcome.

**Expected behavior**
The dialogue box should not limit the characters.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/34885906/101261797-141ce180-373a-11eb-9d81-6e93a07166ad.png)
Dialogue box at its buggy limit. Notice the character counter.

**Platform (please complete the following information):**
 - OS: Windows 7 Ultimate SP1 x64
 - App version: 2.0 Beta 5

**Comment by pau-tomas** [comment]
The character count seems correct to me: variables always count as 3 characters as that's the maximum amount of characters that a variable can take (255) and there's no way to know the value of the variable from the editor.

**Comment by Animacreep** [comment]
But most of the variables I'm using are strings, they should only take up one character.

**Comment by pau-tomas** [comment]
Ah, wait, I think I misunderstood. Is the problem that you can't add more characters once the counter gets to 41?

**Comment by Animacreep** [comment]
Something like that, yeah, I can't add more characters because string variables count as 1 character in the editor and the game but count as 3 characters in GB Studio.
