### ISSUE TITLE
Gameboy Color Support

### ISSUE THREAD

**Issue by Hydra84034** [chrismaltby/gb-studio#690]
Hi,
Can you add support for the Gameboy color? I want to add more colors to my game and I'm sure others want to too. Also can you make a separate export for more powerful devices? Basically take away some limitation if you want to export to phone or pc.

Please and Thank you

**Comment by entozoon** [comment]
Version 2 does support color! https://github.com/chrismaltby/gb-studio/tree/v2beta

**Comment by Hydra84034** [comment]
But isn't there a limit on how many colors I can use?

**Comment by entozoon** [comment]
Of course yeah, the Gameboy Color has very specific hardware limits .. but it is quite a lot:
A 3-color palette for each sprite, and backgrounds allow 6 four-color palettes per scene - using a different palette for every 8x8 tile if you like.

![eg](https://i.imgur.com/Iq5mgXt.png)

**Comment by entozoon** [comment]
Part of the fun is thinking of creative ways to overcome technical challenges, in my opinion. Otherwise you'd just use Unity or something.
This issue should be closed tbh
