### ISSUE TITLE
Link Cable Support in GB Studio

### ISSUE THREAD

**Issue by tguy7890** [chrismaltby/gb-studio#703]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem. It is a request for a new feature.

**Describe the solution you'd like**
I would like GB Studio to have support for making multiplayer games via the game link cable.

**Describe alternatives you've considered**
1. Making single-player games

**Additional context**
The Game Link Cable for the Game Boy can handle real-time movement of 2 players. For an example of this, see Ballon Kid. (https://en.wikipedia.org/wiki/Balloon_Kid)

**Comment by tchaly-bethmaure** [comment]
Hi,

Don't know if it helps, yet a YouTuber makes a value exchange successfully : https://www.youtube.com/watch?v=OggAC5PoZHo&t=87s

Seems working when I test it (doesn't work evry time anyway, but some times it does well).

Next step should be a way to have a synchronisation routine for syncing x,y coordinates of player 1 and 2. Could be useful for a tag game.

Regards,
Tchaly

**Comment by DeerTears** [comment]
This has already been added, could you close this issue @tguy7890 ?
