### ISSUE TITLE
Invalid file signature

### ISSUE THREAD

**Issue by Pixelthegreat** [chrismaltby/gb-studio#713]
I decided to edit some of the png files in the assets/ui folder in my project, and now when I try to run my game or build it, I get an error: "Error: Invalid File Signature". I have tried copying those specific files from other projects, but that has not helped. I was really looking forward to getting it done, and I can't think of any way to anymore. Can anyone help me on this?

**Comment by RichardULZ** [comment]
@Pixelthegreat You didn't follow the issue reporting template.
But it is likely whatever you edited the asset in did not save as a .png, most likely saved as a jpeg with .png name at the end.
Please try to save the asset as a png correctly, or try a different image editor (piskel is a free online sprite tool, might help).

**Comment by Pixelthegreat** [comment]
I think you are right. I tried saving a normal png file with MS Paint and opening one of the files that doesn't work with notepad, and the new file with notepad as well, and I could definitely see a difference, even though I don't know what that difference means. Thanks for your feedback, I tried checking the file signature itself, and that was just fine, so it's a bit of a misleading error.
