### ISSUE TITLE
Reducing the amount of detail in an image

### ISSUE THREAD

**Issue by su-mi-su** [chrismaltby/gb-studio#715]
Made a title screen in Affinity Designer (160px x 144px, PPI 83) using GB Studio color palette and exported as PNG, but I get the following warning:

- Background 'titlescreen.png' contains too many unique 8x8px tiles (204 where limit is 192) meaning it may not display correctly. Consider reducing the amount of detail in this image.

How do reduce the amount of detail? I exported to PNG-8 (dithered) at 3.71 kB from PNG at 15.08kB to reduce the file size, but that didn't work. The title screen shows up, but it garbles the New Game/Continue selector. It still works, but looks bad (see pic). Logo.png loads correctly.

![Screen Shot 2021-02-16 at 12 17 19 PM](https://user-images.githubusercontent.com/55962897/108098414-54a9ad00-7051-11eb-9848-81fb2b32d43a.png)

**Comment by RichardULZ** [comment]
Keep the 8x8 tile grid in mind, moving your logo just a few pixels up or down, so there are more blank tiles, could put you under the limit again.

In this case, you have to shave off about 12 tiles. so Tiled map editor could load your background as a tile set, be pasted into a map, so that you can cherry pick similar tiles to replace. This would be good to learn for making your game anyway.

Alternatively if your software supports a grid, painting out a few pixels from tiles that are almost empty might work, or changing how far the drop shadow is.

**Comment by su-mi-su** [comment]
Gotcha. So there are too many pixels spread across too many tiles? I’ll try shrinking the logo or reducing the drop shadows and see if that works. I was using a 10x9 grid (16x16px per square), but I could change it to 20x18 (8x8px per square). If I multiply that then there are 360 squares to work with, but only 192 can be completely covered in pixels. Is that how it works?

I’m really enjoying GB Studio. I’ve already designed a couple of animated actors as well. It’s an amazing piece of software. I’m going to go back on itch.co and donate, now that I’ve worked with it for several days and I can see all of the possibilities.

Making a video game has always been a dream of mine, but I’m more of a designer, not a programmer. Now I can make that dream a reality! I’m also a Digital Arts instructor and I’m going to recommend your software to my students as well as the video game club. I’d love to teach a game design course someday.

I’m also looking forward to the Analogue Pocket. I missed the first pre-order, but I hope to get one I can work with this summer. With your software and that hardware we could be looking at a retro handheld revival.

Thanks for your help. Keep up the good work!

**Comment by RichardULZ** [comment]
Only 192 tiles can be unique, but that doesn't mean just blank. 
If you had repeated detail, 8x8 grid aligned, they would be reused too. Eg, the shadow under n and z is awfully similar, if they were identical, then the 6 tiles would only use 3. 

Maps and things often use tilesets to speed up workflow, and help stick to the limit, but gbstudio allows any png and cuts it up for you, so you can use any tool you want to make the map, as long as you keep the limits in mind.

Designers that can push right against the limits thrive in gbstudio, as hardware hasn't changed in 20 years, but design has. 
Keep tabs on the Discord if you need feedback/more general help. And close this issue if it's solved.

**Comment by su-mi-su** [comment]
I just shrank the logo somewhat and it worked! Thanks again. I'll hit up the Discord if I need any more help.
