### ISSUE TITLE
More frame in Player animation

### ISSUE THREAD

**Issue by Coleim** [chrismaltby/gb-studio#721]
Hello,

First of all, thanks a lot for the great work. I am currently using the v2beta version in order to be able to use the 2d plateformer feature.

For now, the player animation contains 2 sprites per side, whereas it could be great to have 4 per side.
For example, looking at the Kirby's game boy sprites (https://www.spriters-resource.com/fullview/2796/) you can see that the is 4.
It could be great to have it, especially in plateformer that's coming, as we may not use the down and up view.

Also, I don't know if it's possible to add a jump animation ?

Thanks a lot.

**Comment by RichardULZ** [comment]
Engine overhaul is still probably months away, will have a new metasprite animation system, and also allow you to reuse the mid frame like kirby (4 frames, 3 sprites), and flip sprites. https://twitter.com/maltby/status/1355904577065934850

**Comment by Coleim** [comment]
Awesome.
If I take the `develop` branch it's available ?

**Comment by RichardULZ** [comment]
develop is effectively 1.2.2, and v2beta is 2.0beta5.
These have cli builds in their readmes, but do not contain metasprites.
human_readable is the engine overhaul branch with gbvm, it is not ready for use yet.

**Comment by Coleim** [comment]
Ok then, will wait for the new engine :)
