### ISSUE TITLE
music track does not work

### ISSUE THREAD

**Issue by vel-vet** [chrismaltby/gb-studio#733]
**Describe the bug**
whenever I try to run a scene with a music track, I receive an error and the game doesn't start 
that happens also with the template track.

**Platform:**
I am using the last version of GB studio on a macOS catalina 10.15.4 

**error**
<img width="835" alt="Schermata 2021-04-11 alle 18 19 30" src="https://user-images.githubusercontent.com/82542561/114772743-15a08b00-9d66-11eb-8eac-92fc1d3e3abd.png">

**additional informations**
I already tried to take ownership of the folders

**Comment by RichardULZ** [comment]
@vel-vet Try to reboot your mac, it should clear out / fix the temp 😅

**Comment by vel-vet** [comment]
thank you, now is working
