### ISSUE TITLE
Joypad Input: Attach Script to Button

### ISSUE THREAD

**Issue by pie19988** [chrismaltby/gb-studio#739]
Joypad Input: Attach Script to Button does not function for me. I was watching a tutorial on how to change sprites when running and tried to make the B button to make it work, but it does not function. I am running GB Studio 2.0.0 Beta 4 for Mac. Mac Big Sur Version 11.2.3. 

I know this is a beta so bugs happen, but I tried again 1.2.1 on Mac as well and the function worked fine. To test I made it to where when I hit "B" it causes the player to emote "Shocked" and it worked on 1.2.1 and not on 2 Beta 4.

Unless I am doing something wrong which could be very possible.

**Comment by RichardULZ** [comment]
You should also try 2.0beta5, https://github.com/chrismaltby/gb-studio/tree/v2beta#beta-builds 
Last beta before the overhaul

**Comment by pie19988** [comment]
> You should also try 2.0beta5, https://github.com/chrismaltby/gb-studio/tree/v2beta#beta-builds
> Last beta before the "3.0" overhaul

I actually figured out my issue, it was my own stupidity, but I may still do that. I use it via itch.io and the latest is beta 4 so I didn't know!
