### ISSUE TITLE
Platformer Jump Frame Not Working (3.0)

### ISSUE THREAD

**Issue by Y0UR-U5ERNAME** [chrismaltby/gb-studio#757]
**Describe the bug**
The jump animation frames for Platformer Player do not work as expected. The jump right is replaced with the ladder climbing animation, and the jump left is invisible. 

**To Reproduce**
1. Open GB Studio.
2. Create a Platformer Player metasprite in the metasprite editor.
3. Run the game with the player's spritesheet set to that metasprite.
4. Make the player jump/fall.

**Expected behavior**
The player's animation frame should switch to the set jump animation frames when jumping.

**Screenshots**
![jump_frame_bug](https://user-images.githubusercontent.com/50276952/119414832-58874400-bcbe-11eb-802e-1b85d53c11c7.gif)

**Platform (please complete the following information):**
 - OS: Windows 10 x64
 - App version: GB Studio 3.0 alpha 0 (b7a045c)

**Additional context**
The jump frames work as expected when the sprite type is set to "Four Directions + Movement" and the "Moving Up" and "Moving Down" animations are set to the jump right and jump left frames, respectively. However, this causes the ladder climbing animation to be replaced with the jump right animation.

**Comment by gmarty** [comment]
This is fixed as per https://github.com/chrismaltby/gb-studio/commit/6ff187deb3f7cf3a9ba106bc74e7f5f87137f2fa!
