### ISSUE TITLE
V2 beta: Sprites in dialogue boxes have improper transparency

### ISSUE THREAD

**Issue by Boundarybreaker** [chrismaltby/gb-studio#759]
**Describe the bug**
Instead of having proper transparency to the background of the UI window, sprites displayed in a dialogue box use a white background color instead.

**To Reproduce**
1. Set the `assets/ui/frame.png` texture to the one provided at the bottom of the issue report.
2. Create a `Text: Display Dialogue` event, and set the sprite to any sprite containing the `#65FF00` transparency color.
3. Launch the game and activate the display dialogue event.

**Expected behavior**
The sprite's transparency should be used properly, displaying the texture in the middle tile of the frame texture. If this is infeasible due to GBC limitations, it should be possible to select the background color for sprite transparency elsewhere.

**Screenshots**
![Capto_Capture 2021-05-29_12-47-32_AM](https://user-images.githubusercontent.com/6722691/120062537-9d411100-c017-11eb-8e02-71eabdf9843c.png)

**Platform (please complete the following information):**
 - OS: MacOS 11.2.1
 - App version: 2.0.0-beta5 (6e0abd36)

**Additional context**
Sprite in example screenshot is the radio sprite from the example project. UI frame texture:
![frame](https://user-images.githubusercontent.com/6722691/120062582-d8434480-c017-11eb-9982-325f7c2a9ee2.png)

**Comment by Y0UR-U5ERNAME** [comment]
Avatars are not sprites. They are made of tiles, meaning that they should use the same colors that backgrounds use (`#071821`, `#306850`, `#86c06c`, and `#e0f8cf`) which does not include the `#65FF00` transparency color that sprites use.

**Comment by Boundarybreaker** [comment]
...why does it only let you use sprites, then?,,,,,

**Comment by Y0UR-U5ERNAME** [comment]
There isn't an `assets/avatars` folder, and the sprites are also 16x16. There should probably be an `assets/avatars` folder though.

**Comment by Boundarybreaker** [comment]
> Requirements
> 
> Sprite PNGs must only contain the following four colors:
> 
> #071821
> #86c06c
> #e0f8cf
> #65ff00

Is this just a docs issue, with nontransparent sprites for dialogue boxes being an undocumented feature?

**Comment by Y0UR-U5ERNAME** [comment]
It's a docs issue. It is wrong in saying that avatars are sprites.

**Comment by Boundarybreaker** [comment]
Looks like you're right! There should still be a way to determine what color the transparent color turns into so that you don't have to have two sprite textures for sprites that both get used in-world and in a dialogue screen, so I'll rewrite the issue when I've got time.

**Comment by Boundarybreaker** [comment]
actually since it's more of a feature request now I'm gonna close this one and open a new one.
