### ISSUE TITLE
Path slashes not converted between platforms in projects

### ISSUE THREAD

**Issue by asiekierka** [chrismaltby/gb-studio#772]
**Describe the bug**

Opening a .gbsproj saved on Windows in Linux will cause assets in subdirectories to not load.

**To Reproduce**

1. Add an asset, f.e. a background, to a subdirectory. (For example, "assets/backgrounds/Folder/Picture.png")
2. Use the asset in a scene.
3. Save the project on Windows.
4. Open the same project on Linux.
5. There's no background!

**Expected behavior**

A background!

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows on one side, Linux on another
 - Version: 2.0.0b5

**Additional context**

The issue can be seen by opening the .gbsproj file in a text editor, particularly the "filename" fields containing an escaped "\" slash.

**Comment by crutchcorn** [comment]
I can tackle this bug in a day or so

**Comment by chrismaltby** [comment]
Hi @asiekierka Thanks for reporting this, just came across this issue myself while working on #1147 just merged this fix  8393f64955c277df3a991f940e40deceac78114a which seems to be working, I've just followed these steps going from Windows to Mac and Mac to Windows and both are working now
