### ISSUE TITLE
Engine port to ASM?

### ISSUE THREAD

**Issue by ISSOtm** [chrismaltby/gb-studio#78]
I've tried to look into porting this away from the buggy GBDK and to RGBDS, as mentioned by the engine's README, but the generation of files based on those is missing, so I haven't figured out anything.

In short: what would need to be done?

**Comment by chrismaltby** [comment]
Hi Eldred,

So to attempt this you would need to rewrite everything in https://github.com/chrismaltby/gb-studio/tree/master/appData/src in RGBDS/ASM. 

The actual game data is generated from the JSON and images into a number of C files (mostly just big arrays of data that get read by the engine at run time) from here https://github.com/chrismaltby/gb-studio/blob/master/src/lib/compiler/compileData.js 

Then the project gets compiled with GBDK by running the make file (or on Windows a dynamically generated make.bat) from here
https://github.com/chrismaltby/gb-studio/blob/master/src/lib/compiler/makeBuild.js

I think that's probably enough to get started with. I'd assume the output of compileData.js could be quite similar, maybe just dynamically generating assembly instead.

**Comment by ISSOtm** [comment]
Rewriting the engine code would be the easy part, since it'd mostly be writing engine code to live in ROM0 and referencing assets stored in ROMX. (`BANK()` greatly helping there.)

With assembly, you could generate any sort of binary file and `INCBIN` it instead. Generating bin files has the advantage that you can post-process them, mostly for compression.
Also I don't understand how compileData.js works; I see it generates a .h file, but I don't understand what that file contains or how it's organized.

Compilation wouldn't change, though bundling `make` on Windows could be a good idea, since I've written [an automatic dependency system](https://github.com/ISSOtm/gb-boilerplate) that uses it.

**Comment by basxto** [comment]
compiling it to rgbds with the next sdcc release could be an intermediate step
