### ISSUE TITLE
Request: Ability to move location of text display

### ISSUE THREAD

**Issue by ChaoticPumpkin** [chrismaltby/gb-studio#796]
**Is your feature request related to a problem? Please describe.**
Currently you cannot move menus or dialog boxes to other places on the screen than the bottom right.

**Describe the solution you'd like**
A way to move the boxes to any available tile place on the screen (See image)

**Describe alternatives you've considered**
A more simplified version could be just allowing moving the boxes to a corner of the screen.

**Additional context**
<img width="592" alt="Screen Shot 2021-08-13 at 2 14 20 PM" src="https://user-images.githubusercontent.com/59938482/129419621-d97724c7-299a-481e-83e2-1258cb01c1db.png">
Example of what the feature would let you do

**Comment by maxoakland** [comment]
This has been requested many, many times, but it isn't possible. The text box uses a feature called the Window Layer. The window layer can be set to any X and Y and then draws the window all the way to the right and bottom. 

This is a hardware limitation. It will never be possible to make a window that only covers part of the screen horizontally. It's possible to use interrupts to stop the window layer at a Y value, but that will probably interfere with the parallax scrolling feature

**Comment by ChaoticPumpkin** [comment]
Thanks for responding, I should have looked into it more. I'll close this issue now
