### ISSUE TITLE
[Request] Sprite animation customization.

### ISSUE THREAD

**Issue by Level0gamedev** [chrismaltby/gb-studio#8]
It would be great if we were able to customize the types of animation per sprite. Apart from the current (no animation, facing and 2 frame facing walk cycle) I would love to have:
* Idle animation (2+ frames)
* Longer walk cycle

Both of those can be implemented by adding extra frames to the y axis on the sprite sheet (so idle 2 frame animation would be 16x32)

Making idle animations will really help create more enticing worlds.

**Comment by chrismaltby** [comment]
I agree, especially on the idle animation point, that's been on my backlog for a while but I didn't want to wait before releasing. Will be looking into this.

**Comment by Level0gamedev** [comment]
Awesome, waiting for those idle animations!

**Comment by Level0gamedev** [comment]
If more than just an idle animations are implemented, another awesome feature would be to have an option of "play animation" from the drop down menu in code.

**Comment by DuendeInexistente** [comment]
I'll pip in to say that just being able to change the timing of the animations would be great; Just that would make the walking look less hover-y, without needing to add support for custom framecounts yet.

That said, this is an awesome tool! I can't wait to see where it goes.

**Comment by chrismaltby** [comment]
Sprite animation with animation speed controls are now part of the 1.1.0 release :-)
