### ISSUE TITLE
Request: Make an option for update current max of triggers and/or actors

### ISSUE THREAD

**Issue by MonshouNoMarth** [chrismaltby/gb-studio#806]
I was making a dungeon game which uses more than 9 triggers (per scene) only for changing scene
so compiler takes down all of them to the current max that is 9.

The solution might be making an extra option on "Edit", like "Change Max of..." and then we
can change max number of both things.

The other solution could be universally update the max value, both to 20(T) and 15(A) .

Both solutions would be perfect for v3.0.
Keep doing great!!!

**Comment by maxoakland** [comment]
The maximum number of Triggers is 30

**Comment by maxoakland** [comment]
> > The maximum number of Triggers is 30
> 
> So I guess I'm using an outdated version (1.2.2) (for linux), and in v.Beta2.X (and above) is/will be 30. Thank you then.

Happy to help! Please close this issue since it's solved 😀
