### ISSUE TITLE
Error 4058 

### ISSUE THREAD

**Issue by SuperDog86** [chrismaltby/gb-studio#835]
Every time I try to run, I get the error "ENOENT-4058" 

I am unsure of what this means as this is my first time using Gb studio, I have read their was a similar situation in the past, which has been somewhat fixed. But when I tired it the same error happened. 

I am on a windows if this helps.

Would really appreciate if anyone could help, thank you in advance

**Comment by RichardULZ** [comment]
Do you have what version you're using? We have a bug template that we like people to use, the about version number is really important.

With ENOENT, it means "Error NO ENTry" from our c compiler, either from a locked down / school computer, or old version. 
The latest 2.0 is 2.0b5, but there's also 1.2.2 if you need legacy things. these are not on itch.io.
https://github.com/chrismaltby/gb-studio/releases

**Comment by SuperDog86** [comment]
I am using version 2.0 beta 4 and its not running on a locked down/ school computer

With version 1.2.2 are their any big difference between 2.0b5, Or Is it just a more stable build?

**Comment by RichardULZ** [comment]
Try 2.0b5, 1.2.2 was before any 2.0.
if 2.0b5 solves it, please close the issue

**Comment by SuperDog86** [comment]
Hasn't solved it but thanks for helping
