### ISSUE TITLE
Stop Build Button

### ISSUE THREAD

**Issue by maxoakland** [chrismaltby/gb-studio#837]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to stop a build before it’s over. A button in the Build View would be a great solution for this

**Describe the solution you'd like**
I want to be able to click a button to stop a build if necessary 

**Describe alternatives you've considered**
The only option now is to wait

**Additional context**
Possible reasons to need this feature:
- Accidentally hit the build button
- Realized you forgot to fix a bug 
- Realized you started the wrong type of build

**Comment by RichardULZ** [comment]
https://github.com/chrismaltby/gb-studio/commit/66bd4ac070630194a0e873daf36535a9afe29fe4 🎉 this can be closed now

**Comment by maxoakland** [comment]
> [66bd4ac](https://github.com/chrismaltby/gb-studio/commit/66bd4ac070630194a0e873daf36535a9afe29fe4) 🎉 this can be closed now

Awesome!
