### ISSUE TITLE
Doesn't compile on outdated Ubuntu   (resolved)

### ISSUE THREAD

**Issue by jackygoule** [chrismaltby/gb-studio#852]
Hello i try gb-studio 3 on my ubuntu 16.04 lts.
When i try to compile the exemple project ,i have a error.
/tmp/_gbstools/gbdk/bin/sdasgb: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_gbstools/gbdk/bin/sdasgb)
Thanks for your help

**Comment by jackygoule** [comment]
I try to compile my old project and i have the same error .

**Comment by jackygoule** [comment]
i upgrade my ubuntu to 20.04 whitout full reinstall and it's ok

**Comment by DeerTears** [comment]
Can you close your own issue if it's resolved? (And possibly rename your issue to say "Doesn't compile on outdated Ubuntu" ?)

**Comment by jackygoule** [comment]
Thanks i do this.
