### ISSUE TITLE
32bit ver of 3.0 cannot compile games, uses a 64bit lcc.exe in temp/_gbstools/gbdk/bin

### ISSUE THREAD

**Issue by DeerTears** [chrismaltby/gb-studio#857]
**Describe the bug**
When running on a 32bit windows machine, this error can come up (taken from @Alangamer124)

![gbs error](https://user-images.githubusercontent.com/47726614/145690390-e214a736-115a-49f2-a40d-a5f9745f0270.png)

No other console text is after this error other than the exit code on a newline: `-1`

"This version of C: \ tmp \ _gbstools \ gbdk \ bin \ lcc.exe is not compatible with the version of Windows you are running. Check your computer's system information to see if you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the publisher of the software."

"My pc is X86 (32 bits) so I downloaded the 3.0 standalone 32 bits"

I did this myself and got the same line of errors on the 32bit release, where as the 64bit release compiled empty projects and sample game just fine.

**To Reproduce**
1. Run 32bit standalone or installer on a 32bit machine
2. Compile empty or sample project
3. Find error in build and run log

Building games using 3.0 on a 64bit computer is otherwise fine.

**Expected behavior**
A 32bit version of lcc.exe (presumably from https://github.com/gbdk-2020/gbdk-2020) is included with the 32bit release of gb studio so that 32bit users can compile their games.

**Platform (please complete the following information):**
 - Windows 10 32bit
 - 3.0
 - both no installer and with installer feature this bug

**Comment by RichardULZ** [comment]
#855

**Comment by DeerTears** [comment]
This appears to be fixed now! Thanks!
