### ISSUE TITLE
Fade speed doesn't work in GB Studio 3.0

### ISSUE THREAD

**Issue by ChaoticPumpkin** [chrismaltby/gb-studio#870]
**Describe the bug**
Changing the fade speed on anything doesn't change how fast the screen fades

**To Reproduce**
1. Add `Fade screen out`, `Fade screen in`, etc.
2. Change the fade speed to 6
3. Run the game
4. Change the fade speed to 1
5. Run the game
6. The fade speed is the same both times

**Expected behavior**
The fade speed will change with the number

**Platform (please complete the following information):**
 - OS: MacOS 10.14.6
 - App version 3.0.0

**Comment by chrismaltby** [comment]
Just implemented a fix for this on the develop branch, going to be pushing a 3.0.1 release soon with this fix in place
