### ISSUE TITLE
TypeError: Cannot read property 'numTiles' of undefined

### ISSUE THREAD

**Issue by quentintamar** [chrismaltby/gb-studio#871]
**Describe the bug**
game stop compiling at the very beginning of compiling, with this error : TypeError: Cannot read property 'numTiles' of undefined
its a project ive created on V2 and migrate to V3 (first comiling in V3)  

**To Reproduce**
i don't really know its the only project having this issue

**Expected behavior**
Compiling and running 

**Platform (please complete the following information):**
-Windows 10
-V3

**Comment by RichardULZ** [comment]
Please always use the Issue template to keep error reports consistent.

**Comment by quentintamar** [comment]
> Please always use the Issue template to keep error reports consistent.

Ok sorry i changed that.

**Comment by chrismaltby** [comment]
I get the feeling this is caused by having an "Actor Set Sprite Sheet" event somewhere that links to a sprite that has been deleted. I've got a fix ready though and the next release shouldn't give this error anymore

**Comment by quentintamar** [comment]
OK the issue is gone since 3.01 thanks :)
