### ISSUE TITLE
Game crashes in scenes with 20 actors

### ISSUE THREAD

**Issue by Rebusmind** [chrismaltby/gb-studio#874]
**Describe the bug**
Currently games crash when there are 20 actors in the scene. On Discord toxa said that the 20 actor limit includes the player, but then the number under the scene should be 19 and not 20.

**To Reproduce**
Create a scene with 20 actors and start the game.

**Expected behavior**
The game should not crash or lower the amount of possible actors.

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0

**Comment by maxoakland** [comment]
Oh I was planning to report this. Thanks for doing it!

**Comment by Rebusmind** [comment]
Fixed in 3.0.1
