### ISSUE TITLE
3.0 download in GitHub

### ISSUE THREAD

**Issue by core-code** [chrismaltby/gb-studio#877]
itchi.io site mentions

`You can download on GitHub (along with all the previous releases) if you want too
`

however, i am unable to find version 3.0 on GitHub. where is it? :)

thanks!

**Comment by chrismaltby** [comment]
Oops sorry, I thought I'd done it but turns out the 3.0.0 release in GitHub was set as a draft so only I could see it!
It should be there now along with 3.0.1
