### ISSUE TITLE
No tile/empty sprite causes other actors vram be out by 1 8x8 tile

### ISSUE THREAD

**Issue by RichardULZ** [chrismaltby/gb-studio#883]
**Describe the bug**
A completely transparent 0 tile actor will still load a single 8x8 tile of vram, offsetting future tile loads.

**To Reproduce**
1. Remove all sprites from a sprite anim, or load a completely transparent sprite sheet
2. Place this empty actor in a scene
3. Place another actor that should work in the same scene

**Expected behavior**
actor either uses no vram or 2 8x8 tiles of vram to avoid corrupting other tiles.

**Screenshots**
![image](https://user-images.githubusercontent.com/34431457/146366466-2582ff2f-1ef8-4fc7-a16d-6a8227631f03.png)
![image](https://user-images.githubusercontent.com/34431457/146366577-e79fafd6-c68e-4b72-a8f3-74f998ae5687.png)
![image](https://user-images.githubusercontent.com/34431457/146366738-1cad57f7-6b73-455b-b723-749e29a10704.png)
Tileset generated no tiles with tile length of 1

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.1

**Additional context**
This is in relation to compileData2.ts line 768
https://github.com/chrismaltby/gb-studio/blob/4ef5e5eefaf969229028cdbb9328daf4674ff28c/src/lib/compiler/compileData2.ts#L762-L771 

Setting this to max of 0 causes the background to be filled with black, (24-vram tiles written?) as gbvm probably doesn't know what to do loading 0 data.
Setting this to max of 2 works but uses more vram instead of empty, Does not seem to break a tile set with exactly 1 tile (eg background) but will technically allocate 2 tiles. IDE still reports 0 sprite tiles used when placed. Overall quick fix to the issue, but hacky.

![image](https://user-images.githubusercontent.com/34431457/146368945-c3f5a543-26b1-42f6-bcb8-093781b8c08f.png)
Resulting tile sets with max of set to 2, shown on what should be a 0 tile set (no sprite), and 1 tile set (pure white background),
Quick patch, but not a great one. maybe good enough/better than glitches?

**Comment by untoxa** [comment]
it is a bug in data_manager.c: zero amount of tiles must be a valid value (now 0 for sprite tileset means 256 tiles). no need to workaround on the IDE side, and `max(1, ...` looks very wrong.

**Comment by RichardULZ** [comment]
https://github.com/chrismaltby/gbvm/commit/f18b2a33bdd8e99b3c09cbd6f1766d4939ab705e 
This means tileset can be max of 0 now!

**Comment by untoxa** [comment]
is tileset for sprites is generated separately from tilesets for everything else? if yes, then must be:  

`n_tiles: Math.ceil(tileset.length / 32)*2, ` 

assuming length is always positive and also assuming 8x16 mode, and byte array must be zero extended to the size of multiple of 32 byte, or else there will be some random garbage in the last 8x16 tile.

**Comment by RichardULZ** [comment]
i don't think so, it's separate somewhere earlier since it needs to handle pure green/transparent, but merges here.
