### ISSUE TITLE
TypeError: Cannot read property 'args' of null

### ISSUE THREAD

**Issue by BowersIndustry** [chrismaltby/gb-studio#892]
So I migrated my GBS v2.0 game to GBS v3.0 and I got this error,
TypeError: Cannot read property 'args' of null
The error goes away when I delete all of the Platformer scenes though...

And I'm on Windows 10 if that means anything...

**Comment by RichardULZ** [comment]
Please use the issue example template to keep bug reports consistent.

We will need steps to reproduce and/or a known broken project folder zipped up to test and investigate the issue.
Simply having a platformer scenes is definitely not going to reproduce the issue on our end.
