### ISSUE TITLE
[Platform Mode] Can’t Jump while in hitbox of Actor or Trigger

### ISSUE THREAD

**Issue by maxoakland** [chrismaltby/gb-studio#914]
**Describe the bug**
In platform mode you can’t jump if the player hitbox is overlapping the hitbox of an actor. Another user reported here (https://github.com/chrismaltby/gb-studio/issues/894#issuecomment-998158836) that they can’t jump while inside a trigger

**To Reproduce**
1. Create an actor with a hitbox
2. Run a scene it platform mode
3. try to jump while overlapping the actor
4. Can’t jump

**Expected behavior**
Should be able to jump at any time unless the game’s developer has specified otherwise

**Platform (please complete the following information):**
 - OS: Mac
 - App version 3.0.1

**Comment by Rebusmind** [comment]
Yeah, this bugged me as well. You can change it pretty easily by changing this line in platform.c.
![grafik](https://user-images.githubusercontent.com/9643886/146892197-578c6013-e77e-41b8-8304-d43f5097ecb0.png)

**Comment by maxoakland** [comment]
> Yeah, this bugged me as well. You can change it pretty easily by changing this line in platform.c.
> 
> ![grafik](https://user-images.githubusercontent.com/9643886/146892197-578c6013-e77e-41b8-8304-d43f5097ecb0.png)
> 
> 

Upload that and make a pull request 😀

**Comment by Rebusmind** [comment]
I haven't done that, yet, cause I'm pretty sure it's there for a reason, I just don't know what that reason ist. 😆
