### ISSUE TITLE
Variables used in If Math Expression are not added to Custom Scripts

### ISSUE THREAD

**Issue by Rebusmind** [chrismaltby/gb-studio#918]
**Describe the bug**
When you use the` if math expression` event in a custom script, any used variables won't be added to the list of variables.

**To Reproduce**
Create a new custom script, add the `if math expression` event and add a variable with $ to the expression.

**Expected behavior**
The expression should be evaluated and any used variables should be added to the list.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9643886/146893071-daabaebd-2643-4df8-8b14-074a0bf42457.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.2

**Comment by Rebusmind** [comment]
The same happens in the evaluate math expression event. (only the variable from the dropdown gets added)
![grafik](https://user-images.githubusercontent.com/9643886/146893385-fccd2012-de58-4b21-ae84-947bd7dd96ac.png)

**Comment by pau-tomas** [comment]
Fixed in #926

**Comment by Rebusmind** [comment]
It mostly works, but when you enter a variable in the text field and then click on it again to change it, the new variable doesn't get added to the list. (additional info: there are two different ways to select a variable: 1. a small selection box when you first enter $ and the variable name and 2. a larger box with suggestions when you click on an already added variable; the problem here lies in 2.)
![grafik](https://user-images.githubusercontent.com/9643886/147076918-11188663-d4e2-4c2e-9f32-f6fd0bcdff8d.png)

(also, the autolabeling only works as expected in the `Evaluate Math Expression` event)

**Comment by Rebusmind** [comment]
Works now. :)
