### ISSUE TITLE
Music tracker wave length stuck at 46

### ISSUE THREAD

**Issue by kimproductions** [chrismaltby/gb-studio#924]
**Describe the bug**

Cannot change wave length slider in the hUGE music editor after saving. The slider either reverts to 32 or 46. When I attach the music to the scene, the slider is still stuck.

**To reproduce**

1. Set length slider as desired.
2. Click on another uge template, restart gbstudio, or add music event to scene.
3. Length slider value will not be saved.

![asdf](https://user-images.githubusercontent.com/86948598/146947338-44fbf2df-555b-48c3-9469-727d7444d1c6.JPG)

**Platform:**

OS: [Windows 10]
GBStudio [Ver. 3.0.1]

**Comment by pau-tomas** [comment]
Is this only happening for the length or do other fields don't get saved also?
