### ISSUE TITLE
[BUG] Colorspace not checked on build

### ISSUE THREAD

**Issue by ParzivalWolfram** [chrismaltby/gb-studio#93]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
PNGs with odd, unmatching colors will be converted to the right palette for display. This is fine. However, having many different tiles, complex designs or many colors are turned into garbage tiles.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

![image](https://user-images.githubusercontent.com/30007617/56938171-087d2980-6ac6-11e9-81c4-ec554a9a015b.png)

* **What is the expected behavior?**

Rejection at build time or successful down-conversion. 

* **What is the motivation / use case for changing the behavior?**
Foolproofing, error catching, and such. I suppose it could also have some use in an edge case, but I seriously doubt it'd be useful.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: [Windows]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Catch PNGs with too many colors at build time and error out on them.

**Comment by thomas-alrek** [comment]
This could also be relatert to the max unique tile limit. Your image has a lot of entropy

**Comment by chrismaltby** [comment]
The latest builds handle converting the colours to the nearest supported one a lot better but the main issue here is the amount of detail in the image as Thomas says, each image can only have 192 unique 8px tiles as stated in the docs,
If you looked at the build console you'd have also seen this message
<img width="778" alt="Screen Shot 2019-04-30 at 10 12 16 AM" src="https://user-images.githubusercontent.com/16776042/56951730-7c541c00-6b30-11e9-8a30-21977caed044.png">
perhaps we should just make this a fatal error that stops compilation?

**Comment by RichardULZ** [comment]
> perhaps we should just make this a fatal error that stops compilation?
That's extreme, maybe switch to the log view when you get a warning?
I've successfully stored pictures with more than 192 tiles, and reduced it to only corrupt the text box, Which lets me use them for full screen graphics slides, forcing a fatal error would loose this.

**Comment by ISSOtm** [comment]
It's absolutely possible to get the Game Boy to display images with more than 256 tiles (this uses sprites but the BG is more than 256):

![Demonstration GIF](https://cdn.discordapp.com/attachments/311917081086001152/498830438526222336/motherboard.gif)

Thus making this a fatal error is something I'd support if and only if it can be disabled (CLI switch?)

**Comment by chrismaltby** [comment]
Yeah it's possible but the engine reserves a certain amount of memory for the window buffer and sprites in a scene. 192 is the amount available guaranteed to be available for background images in the engine.

**Comment by ISSOtm** [comment]
I meant that if people want to hack the engine for this purpose, they should be able to. (Not that I'd suggest them to keep using the engine, at this point, but someone's bound to try eventually :P)

**Comment by chrismaltby** [comment]
Commit ad7fe5719ed729ee6db15ae3019a0113e30b9701 now automatically switches to the build tab if there are any warnings/errors during build. It also displays all the warnings as the end of the build so they should be more obvious.

<img width="798" alt="Screenshot 2019-04-30 at 22 31 24" src="https://user-images.githubusercontent.com/16776042/56994743-e81d9f80-6b97-11e9-8923-c62b9a2359ed.png">

**Comment by ParzivalWolfram** [comment]
yay, one of my "i deliberately broke it, plz fix" issues actually helped
