### ISSUE TITLE
Add On Hit to the actors in all scene types so that we can detect collisions between actors and collision group

### ISSUE THREAD

**Issue by darkhog** [chrismaltby/gb-studio#935]
It would work like On Player Hit scene event except that it would check collisions for the specified actor. It would allow stuff like actors reacting to player bullets or the like without writing a complicated On Update code that checks for hitboxes and the like.

**Comment by darkhog** [comment]
Noticed shmup scene type has Actor hit event, hence the title change. IMO all scene types should have it (except maybe for logo because it doesn't allow actors, period.). Especially stuff like platformer - hard to make a megaman clone when enemies don't react to being shot at.

**Comment by pau-tomas** [comment]
Actors have On Hit script once you assign a collision group to them.

**Comment by maxoakland** [comment]
Hey Darkhog, this is already how it works. You just have to set a collision group for the actor and then it will respond to bullets that are set to hit that collision group

**Comment by darkhog** [comment]
Lol, that&#39;s why I&#39;ve closed the issue. Since couldn&#39;t delete it. Give it rest.  
            
          
     
      
       
        Dnia 25 grudnia 2021 03:59 Max Oakland ***@***.***&gt; napisał(a):
       
    
       
         
 Hey Darkhog, this is already how it works. You just have to set a collision group for the actor and then it will respond to bullets that are set to hit that collision group
