### ISSUE TITLE
Corrupted collision map when background is resized/removed

### ISSUE THREAD

**Issue by amysgames** [chrismaltby/gb-studio#94]
**Note: for support questions, please use one of the following channels**.

Reddit: [/r/gbstudio](https://www.reddit.com/r/gbstudio)
Discord: [Join Chat](https://discord.gg/bxerKnc)

This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
If you resize or rename/remove the background image for an existing scene, the collision map becomes corrupted.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
I trimmed some of the empty space from this background PNG in Photoshop, and when I switched back to GBStudio, the scene looked like this:
![Screen Shot 2019-04-29 at 9 59 31 PM](https://user-images.githubusercontent.com/50056913/56940484-f7371b80-6acb-11e9-995a-1bca0d940805.png)
(Something similar happened when I renamed a background image in Finder.)

* **What is the expected behavior?**
The editor should either attempt to preserve the collision map, or remove all collision tiles if the background changes size or is removed.

* **What is the motivation / use case for changing the behavior?**
It's not a huge issue, but it's annoying having to fix the collision every time.

* **Please tell us about your environment:**

  - Version: 1.0.0
  - Platform: macOS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Maybe there could be a prompt if the editor detects background changes in scenes with collision maps? (Could ask if you want to remove the scene if a background is removed, etc.)

**Comment by chrismaltby** [comment]
Good point, in 1bb2e94a3b172ec216e5a662e2b7c5efa6540e26 this will now clear the collisions array if the dimensions of the background image has changed
