### ISSUE TITLE
If device supports color doesn't work/

### ISSUE THREAD

**Issue by darkhog** [chrismaltby/gb-studio#944]
**Describe the bug**
The "If device supports color" event does not work as it returns true even when the game is run on a DMG.

**To Reproduce**
1. Make a project with color mode enabled (the event is pointless to use otherwise)
2. Make event like this in the init scene (make sure scene change events points to two different scenes): ![image](https://i.imgur.com/oop1b7O.png)
3. Build the game and flash to the flashcart
4. Run on a DMG
5. The game will load into the scene that was in the "true" block instead of the else one (the game thinks it's on GBC even when it's not).

**Expected behavior**
The game should correctly detect whether it runs on a DMG or the GBC.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows
 - App version 3.0.2, but it happened ever since GBS 2 betas

**Additional context**
I'll provide a ROM file that can be flashed into a cart that demonstrates the issue (don't attempt to play it, it's buggy and unfinished). The correct screen you should have seen after the logo is the following: ![image](https://cdn.discordapp.com/attachments/573779673037799434/924954901086359562/gbc.png) - instead you will see the title screen of the game.

**Comment by darkhog** [comment]
[game.zip](https://github.com/chrismaltby/gb-studio/files/7779511/game.zip)

**Comment by pau-tomas** [comment]
I can't reproduce this with a simple use case (the if device supports color event and two dialogue boxes) 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/54246642/147462050-ff70f70f-f5dd-4c19-8a99-c858e8b4d925.png">

Could you share the project you're using to test?

**Comment by darkhog** [comment]
[Krótka gra na gameboya.zip](https://github.com/chrismaltby/gb-studio/files/7781603/Krotka.gra.na.gameboya.zip)

**Comment by pau-tomas** [comment]
The init script of the first scene is changing scene to Title Screen before calling the `If Device Supports Color` event. So it'll **always** change to that scene no matter what device you're using because `If Device Supports Color` will never be called.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/54246642/147510461-d07519ab-eadd-4e9a-a4ac-d01075b66609.png">
