### ISSUE TITLE
VM_LOAD_PALETTE on DMG sets the second and third colors to the same color

### ISSUE THREAD

**Issue by Y0UR-U5ERNAME** [chrismaltby/gb-studio#950]
**Describe the bug**
The `VM_LOAD_PALETTE` command in GBVM, when using a DMG palette, sets the third color to what the second color is set to. (Backgrounds can only have three unique colors and sprites can only have two unique visible colors.)

**To Reproduce**
1. Add a "GBVM Script" event.
2. Insert this code that should invert the background palette and OBP0:
```
VM_LOAD_PALETTE         0x01, ^/.PALETTE_COMMIT | .PALETTE_SPRITE/
    .DMG_PAL            3, 2, 1, 0

VM_LOAD_PALETTE         0x01, ^/.PALETTE_COMMIT | .PALETTE_BKG/
    .DMG_PAL            3, 2, 1, 0
```
3. Run the game (without Color Mode on).
4. See error.

**Expected behavior**
The second and third colors for DMG palettes should be able to be unique from each other.

**Screenshots**
<img width=500 src="https://user-images.githubusercontent.com/50276952/147713071-ad51859e-fc09-474c-88c2-b1be95c565cc.png">

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.2

**Comment by untoxa** [comment]
thank you, nice catch! https://github.com/chrismaltby/gbvm/commit/b6f4da16a9d0993e6406240ac5554e38c0e764a8
