### ISSUE TITLE
Got Error on Loading Game Data

### ISSUE THREAD

**Issue by dxkill** [chrismaltby/gb-studio#958]
**Describe the bug**
When i tried to load Game data from slot 1 the screen from the screenshot appeared.

**To Reproduce**
-

**Expected behavior**
I expected the Game to Load the Data i saved in Slot 1.

**Screenshots**
![Error](https://user-images.githubusercontent.com/79058365/147856917-c777259b-ba74-471f-a15d-4fb0d1f575e1.PNG)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro for Workstations 19042.1415
 - Version: GB Studio 3.0.2

**Additional context**
-

**Comment by maxoakland** [comment]
This happens when you load an outdated save

**Comment by godai78** [comment]
@maxoakland - not really. IF you have a saved slot then it works, but if you don't one, it will kernel panic. Also using the "if game data saved" even seems to not work and the result is fail if you try to load when no saves are present (instead of displaying a message).

**Comment by dxkill** [comment]
I see, Thanks!
