### ISSUE TITLE
Platformer interaction input hard-coded to A

### ISSUE THREAD

**Issue by Rebusmind** [chrismaltby/gb-studio#963]
**Describe the bug**
The input for interaction seems to be hard-coded to the A button right now, no matter what you set it to in the settings. 

**To Reproduce**
In platform.c the interaction input is defined as BUTTON_A. 

**Expected behavior**
It should take the input defined in settings. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.2

**Comment by pau-tomas** [comment]
Does this happen even after Cleaning the build cache?

**Comment by Rebusmind** [comment]
I haven't tried that, but as it defines it as INPUT_A in platform.c I would've thought it's hard-coded.

**Comment by pau-tomas** [comment]
```#ifndef INPUT_PLATFORM_INTERACT
#define INPUT_PLATFORM_INTERACT    INPUT_A
#endif
```

`platform.c` defines `INPUT_PLATFORM_INTERACT` to INPUT_A only if it isn't already defined. `states_defines.h` is included at the top of `platform.c` and contains the constants as configured in settings, if `INPUT_PLATFORM_INTERACT` is in that file then it'll never be defined in `platform.c` (the file is generated at compile time).

**Comment by Rebusmind** [comment]
Okay, then I misunderstood it. I will try to empty the cache and see if the issue is still there.

**Comment by Rebusmind** [comment]
Clearing the cache fixed this issue. Sorry for jumping to conclusions. 😅
