### ISSUE TITLE
Actor does not follow the player

### ISSUE THREAD

**Issue by godai78** [chrismaltby/gb-studio#967]
**Describe the bug**
When using the script where the actor should approach the player using their coordinates, the actor only moves vertically.

**To Reproduce**
1. Use move actor action, add player coordinates as the destination.
2. Actor follows the player vertically only, does not really approach them.

**Expected behavior**
Actor follows the player and tries to reach their position on both vertical and horizontal axis.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Win 7
 - App version 3.0.3

**Additional context**

**Comment by godai78** [comment]
Never mind, found a solution.

**Comment by codyjb** [comment]
Recommend re-opening this

This is reproduceable by using the player properties in the move to parameters. 
![image](https://user-images.githubusercontent.com/7562466/148804081-0a95e53f-3e5b-497f-b05d-87e7c5e3afa7.png)


The work around mentioned is to store the player position in a variable and then immediately use that in the move to parameters 
![image](https://user-images.githubusercontent.com/7562466/148804048-f68dfb2f-b13e-41de-b73b-c434bb0badbe.png)

**Comment by godai78** [comment]
I used the second solution. It does work but generates efficiency problems. But I basically have some efficiency problems with NPCs and they are random sometimes the same script will work and sometimes slow down, seemingly depending on the scene size.

**Comment by codyjb** [comment]
> I used the second solution. It does work but generates efficiency problems. But I basically have some efficiency problems with NPCs and they are random sometimes the same script will work and sometimes slow down, seemingly depending on the scene size.

I moved the variables out of temp, idk if its placebo, but holding them in local or global seems to make it function reliably. 

This was not scientific, i was changing a lot in my actors functionality, but the move to is the same and the only difference is the var spaces used

**Comment by godai78** [comment]
I'll test it over the weekend and let know.

**Comment by godai78** [comment]
Nope, looks like the framerate drops anyway. But this is very strange, I have efficiency drops even with a simple move to x,y and back actors. I used this kind of movement in a game I made before and it did not display this kind of behavior. I wonder if this is not to do with the size of the scene background?
