### ISSUE TITLE
Player->Actor Collisions not working in Adventure scene style

### ISSUE THREAD

**Issue by Rebusmind** [chrismaltby/gb-studio#979]
**Describe the bug**
In scenes that use the adventure type the player can move through actors.

**Expected behavior**
If I'm not mistaken, in 3.0alpha the collisions worked fine in adventure type scenes.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9643886/148741255-048f54d6-be7c-4408-bf70-a0bdf8886eb4.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - App version 3.0.2

**Comment by ChaoticPumpkin** [comment]
Can confirm this is still an issue in 3.0.3, tested on MacOS 1.14.6.

This is the same scene in Top Down 2D compared to Adventure

**Top down 2D**
![Top Down 2d](https://user-images.githubusercontent.com/59938482/152460741-febd472b-06d7-4921-98de-e3bfc8373fea.gif)

**Adventure**
![Adventure](https://user-images.githubusercontent.com/59938482/152460777-46bc9af5-a6da-40ca-a361-f231450b9b39.gif)

**Comment by maxoakland** [comment]
It would be great to be able to pick per actor if you want them to have collision or not

**Comment by jessemillar** [comment]
Did this ever work in adventure scenes? This PR exists (https://github.com/chrismaltby/gb-studio/pull/1037) that adds actor collisions to platformer AND adventure scenes. I'm newer to GB Studio though so maybe it did work at some point and the PR is just a refactor...?

**Comment by maxoakland** [comment]
> Did this ever work in adventure scenes? This PR exists (#1037) that adds actor collisions to platformer AND adventure scenes. I'm newer to GB Studio though so maybe it did work at some point and the PR is just a refactor...?

It’s never been implemented

**Comment by Rebusmind** [comment]
Maybe that PR wasn't implemented, but there used to be a pretty simple implementation for actor collisions in adventure scenes. I digged it up for my game and it works pretty well. The only downside is that when you move diagonally and collide with an actor, the player stops instead of going in at least one free direction. 

Here's the code that adds actor collision to the adventure scenes (line numbers should give an indication where the code goes, but these might have changed by now).

1. Save the current position of the player before updating it
![image](https://user-images.githubusercontent.com/9643886/193201229-4c2192eb-4cb7-470e-b54f-1a766c572c01.png)

2. If you detect a collision, set the player back to that saved position so it doesn't get stuck in the actor
![image](https://user-images.githubusercontent.com/9643886/193201506-fdedd711-c850-4eab-851e-1aa4b0bdb0ef.png)

Hope this helps.

**Comment by maxoakland** [comment]
> Maybe that PR wasn't implemented, but there used to be a pretty simple implementation for actor collisions in adventure scenes. I digged it up for my game and it works pretty well. The only downside is that when you move diagonally and collide with an actor, the player stops instead of going in at least one free direction.
> 
> Here's the code that adds actor collision to the adventure scenes (line numbers should give an indication where the code goes, but these might have changed by now).
> 
> 1. Save the current position of the player before updating it
>    ![image](https://user-images.githubusercontent.com/9643886/193201229-4c2192eb-4cb7-470e-b54f-1a766c572c01.png)
> 2. If you detect a collision, set the player back to that saved position so it doesn't get stuck in the actor
>    ![image](https://user-images.githubusercontent.com/9643886/193201506-fdedd711-c850-4eab-851e-1aa4b0bdb0ef.png)
> 
> Hope this helps.

Can you implement this and do a pull request?

**Comment by jessemillar** [comment]
We might not need another PR. PR #1037 adds the described collisions and supports diagonal sliding in adventure mode. Chris also has done some groundwork changes prepping for that exact PR. I'm no maintainer though so I defer to higher powers.
